### ISSUE TITLE
Saving credentials for https or using macOS keychain not working?

### ISSUE THREAD

**Issue by craftey** [git-up/GitUp#1000]
I recently tried to push with GitUp. It asks me for creds but never saves them. My git cli uses macOS keychain to save and use my credentials, which works fine.
I also tried  ~/.git-credentials without success.
I am trying to connect to gitlab.com via https and with username and a repo token generated in my gitlab profile. It seems to work with the auth dialog but it asks me on every action.

So how can I get GitUp.app to not ask for credentials?

Thanks for any idea you might have.
Kindly, craftey

**Comment by Cykelero** [comment]
Weird! GitUp is indeed supposed to remember your credentials.
It's supposed to save these in the macOS keychain. Could you check if they're getting created at all?

Open Keychain Access.app, and search for gitlab.com. You should get at least one entry.
Of these entries, at least one of them should have GitUp in its allowlist:
 
![image](https://github.com/git-up/GitUp/assets/2979318/dd447cff-683c-427a-a558-9072526fd051)

**Comment by craftey** [comment]
Thanks for your "works for me" comment. With that I looked a bit closer into my Keychain Access.app. I recently had to update my gitlab token, because they enforce a token expiry policy now ☹️.
Anyway in the process of updating my token I somehow got two entries for "gitlab.com", the new one and the old one. In this situation git-up asks for creds again and again.

After deleting the old entry, git-up works normally. It asks once to access the existing keychain entry where I was able "always allow" to read the keychain entry. It adds the application to the allow list in the new keychain entry, done. Git-up does not ask for creds anymore, as desired.

**Comment by Cykelero** [comment]
Awesome! Glad you found the fix.

If I recall correctly, when GitUp queries the keychain, it only requests a single item; my guess is that it would always retrieve the older, incorrect one. Those credentials wouldn't work for authenticating, so the app would proceed to ask for new credentials. Saving them back to the keychain had no effect because the item was already there, simply ignored during the query.

**Comment by phraktle** [comment]
I experienced this as well after updating my git credentials. Had to remove the older entry from Keychain. I would suggest treating this as an open bug, since it's not obvious for the user and GitUp could probably handle it better.
