### ISSUE TITLE
[Feature request] Add a branch view with all commit message displayed

### ISSUE THREAD

**Issue by goulvench** [git-up/GitUp#1001]
I mainly use Gitup to reorder, split and merge commits before pushing PRs, which is way more practical than using Git itself, so kudos! This allows refactoring/fixing typos while keeping history clean —which is easier than uncluttering my desktop 🙃.

However, when working on a branch, I'd love to be able to view all commits messages from that branch, so that I can easily move to where they belong, without having to count key presses. 
In fact, I rarely switch from one branch to another using Gitup, that's something I do on the command-line, or using Fork (which I enjoy for its branching/remote/commit/stash UI).

My current workflow is:
1. Select the branch I've been working on
2. Find a fixup commit that needs to be moved
3. Count the number of key presses until the commit to merge into
4. Go back up to the fixup commit
5. Press `d` until the fixup is just above its parent
6. Press `f` to merge it where it belongs
7. Repeat from step 2…

A one-branch view with all messages listed would make steps 2 to 6 much easier.

**Comment by wadetregaskis** [comment]
Duplicate of https://github.com/git-up/GitUp/issues/192?

**Comment by goulvench** [comment]
@wadetregaskis Indeed, I had searched but not found issue #192. Command-D does just what I need!
