### ISSUE TITLE
Add option to not show Welcome screen on startup

### ISSUE THREAD

**Issue by sindresorhus** [git-up/GitUp#102]
I only open git repos from the command-line into GitUp and having the Welcome screen appear is kinda annoying when I would never use it.

**Comment by sindresorhus** [comment]
@swisspol Would you prefer to have such option in `Preferences...` or directly in the Welcome screen UI? I've seen examples of both on OS X.

**Comment by swisspol** [comment]
I think it should be in preferences?

**Comment by larry-xmos** [comment]
+1

**Comment by samchesney** [comment]
I'd appraise this as I do the same - start GitUp from the command-line, and then have to close the welcome screen that has opened on top of other windows on my other monitor.

**Comment by sindresorhus** [comment]
In 1.0.5 it became considerably more annoying, as it's now shown every time GitUp is activated, not just on startup...

**Comment by mtrudel** [comment]
Perhaps it belongs in preferences as well, but I think it's a reasonable default to not display it when invoked from the command line. Chances are overwhelming that you'll want to be interacting with the git folder implied by where the command was invoked, and so displaying the welcome screen isn't relevant.
