### ISSUE TITLE
Auto-update error while extracting archive 1.4.0 -> 1.4.2

### ISSUE THREAD

**Issue by arru** [git-up/GitUp#1021]
After download completes, this message appears. Tried 3 times. with re-launch. Manual download (of 1.4.2) from objects.githubusercontent.com extracts and runs fine though. 

OSX 14.5 MacBook Pro M3

<img width="372" alt="Skärmavbild 2024-08-13 kl  09 38 57" src="https://github.com/user-attachments/assets/e40715dc-0e41-4f8b-9c50-99e3594cb330">

**Comment by lucasderraugh** [comment]
Ya this makes sense. We had to rotate keys and we didn't have the EdDSA key in the 1.4.0 build. You'd have to go from 1.4.1 to 1.4.2 to make the transition smoothly. Not sure if there is a way to set that up in the app cast to direct you to download 1.4.1 first or not but I'll think about it.
