### ISSUE TITLE
Can't undo stage/unstage

### ISSUE THREAD

**Issue by mik01aj** [git-up/GitUp#103]
When I stage something and press `Cmd+Z`, I expect it to undo the staging, but instead it undoes previous action (commit in my case). Seems like a missing functionality.

**Comment by swisspol** [comment]
For reasons that are too complex to explain Ina few sentences, undo / redo of staging operations is not something that is compatible with the undo system of GitUp. Furthermore, it's not something that can be reliably undone / redone when considering it has to work also with whatever people do outside of GitUp with other Git tools while GitUp is running.

**Comment by jscheel** [comment]
@swisspol whew, I got hit by this today. It mixed my working directory with the last commit, which was a massive diff, and made everything confusing :) I understand the reasons for not being able to undo the staging of a commit, but how would you feel about disabling the undo in the commit view if there are changes in the working directory?
