### ISSUE TITLE
gitup hogs CPU during remote operation

### ISSUE THREAD

**Issue by sesam** [git-up/GitUp#104]
I got hang during remote operation. MFA enabled. OSX Keychain. Slightly, but not too much, similar to #75 

Before the hang I'd get the credentials popup and fill it in (for each remote op, and only for one out of 3 private repos).

Console debug (keychain error - can't save internet password) lead to
WORKAROUND: cleanup stored internet password records with key https://github.com and my username.

My keychain had "internet passwords" stored for the github website intermixed with personal access tokens - one I generated yesterday and one new after I regenerated (= invalidated) the old token, thinking the token was incorrectly stored.

Bugfix: ???. Maybe the problem comes from storing personal access tokens as an "internet password"? But why 2 repos out of 3 work fine with no problems at all is beyond my imagination. Maybe gitup internally handles credentials differently for different repos.

Also, gitup shows no error message when it fails to store my supplied token, it's just the failure on the command line.
Related feature request: I'd prefer gitup to give a heads up for any kind of previously unseen error, and maybe put them in a "grab-bag" of past errors for me to look through together with some expert later on.

**Comment by swisspol** [comment]
Let's consider this a dup of #75. Please put put any extra info over there instead,
