### ISSUE TITLE
The UI breaks: sometimes the "chain" is not visible, only the nodes

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#1044]
Here are a few UI glitches that I've noticed:

<img width="370" alt="Screenshot 2024-12-31 at 5 29 35" src="https://github.com/user-attachments/assets/6b222c80-7339-4f85-a6a8-2003bf614062" />
<img width="118" alt="Screenshot 2024-12-31 at 5 28 59" src="https://github.com/user-attachments/assets/3c9ee4ff-1032-4947-b0dc-b2a2d7aa75b3" />

Very likely this is due to large number of nodes displayed.

M1 Max, 32 G

**Comment by lucasderraugh** [comment]
I think this is the same as #1042

**Comment by richardtop** [comment]
Correct, I'm closing this as a duplicate.
