### ISSUE TITLE
b1015 reports some submodules as renamed even if not

### ISSUE THREAD

**Issue by kballard** [git-up/GitUp#105]
In v1.0.5, GitUp has started listing two completely incorrect entries in the staging area for submodules we have. `git status` in the terminal correctly indicates that there's nothing dirty in my repo, but GitUp is showing 4 spurious entries for 2 submodules. Each submodule has one Deleted entry showing the New Submodule Commit as "(missing)" and 1 Unknown entry that shows both the Old and New Submodule Commits as "(missing)".

![screen shot 2016-03-31 at 3 23 55 pm](https://cloud.githubusercontent.com/assets/714/14192769/9d80ac0c-f754-11e5-836e-91a4ba9b0996.png)

Needless to say, having bogus dirty entries in GitUp completely breaks most of the app's functionality (you can't edit history beyond rewording commit messages when the working copy has changes, and of course this also screws with trying to stage new changes).

I have no idea why GitUp is treating these two submodules this way. The project has 4 submodules total, and the other two are working just fine.

**Comment by kballard** [comment]
Is there any way to roll back to v1.0.4 short of building the app myself? The GitHub Releases doesn't have compiled apps, and of course GitUp automatically updates itself anyway.

**Comment by swisspol** [comment]
That's apparently a problem in libgit2, which I just updated to the latest release in b1015: https://github.com/libgit2/libgit2/issues/3713

1.0.5 is pre-release - just be on the stable channel in the Preferences, then re-download GitUp.

**Comment by kballard** [comment]
I didn't realize I'd switched to the Continuous channel on this computer. I'll do that now.

**Comment by swisspol** [comment]
Fixed in c33225c05159a2ee43c01fb25949f292d54f0211 and b1016.
