### ISSUE TITLE
Can't commit when there is a pre-commit hook (Couldn't posix_spawn: error 8)

### ISSUE THREAD

**Issue by mik01aj** [git-up/GitUp#106]
This happens when I try to commit:

![image](https://cloud.githubusercontent.com/assets/3027415/14203917/0ee60c28-f801-11e5-86df-a2a150d3f8cb.png)

This is because I have a pre-commit hook in `.git/hooks/pre-commit`. After I remove it, committing works again.

I think it's an issue with GitUp, because the `pre-commit` hook works fine from the command line.

**Comment by mik01aj** [comment]
I just noticed that for *some* pre-commit hooks it works...

The working one had a shebang line on top, the other didn't. Adding `#!/bin/bash` at the top of the hook file fixed it.

But I still wonder, is there anything that GitUp could do to make the behaviour consistent with the console?

**Comment by swisspol** [comment]
Git hooks need to be executable to work with GitUp. Because GitUp handle hooks directly and not through the Git tool, it can't support as many cases. See https://github.com/git-up/GitUp/wiki for details.

**Comment by mik01aj** [comment]
Good point, I didn't read that. On the other hand, a more informative error message in this case would help *a lot*. Like, "Couldn't run pre-commit hook (posix_spawn: error 8). Please read the docs about GitUp limitations: [link]"
