### ISSUE TITLE
Can't push from Gitup

### ISSUE THREAD

**Issue by grobmeier** [git-up/GitUp#107]
Hi,

I would love to push from GitUp, but the items are grey. I have to move to the cli to push.

I am on 10.11.3

git --version
git version 2.6.2

![screenshot 2016-04-01 13 15 18](https://cloud.githubusercontent.com/assets/873786/14205503/e43cde9c-f80b-11e5-8211-c4c23f7befe9.png)

Any ideas?

Thanks!

**Comment by swisspol** [comment]
Looks like you already have a background operation in progress:
https://github.com/git-up/GitUp/blob/master/GitUpKit/Views/GIMapViewController.m#L650

**Comment by grobmeier** [comment]
Hi

thank. Despite I did not understand what you said from the source code, I was able to find out what was the issue: I am using Atom which runs a process called com.github.atom.ShipIt 

Even when Atom is closed, ShipIt would run and prevent Gitup from working as expected.

This is worth to document or at least Gitup should warn. In my case, the ShipIt process is related to Atoms auto update and has nothing to do with my repos. From user pov it just looks like Gitup was broken, while it is just conflicting with an unrelated service.

Cheers
Christian

**Comment by swisspol** [comment]
That's very puzzling. What makes you think this is the cause?

GitUp push menu cannot conflict with anything since it doesn't depend on anything external.

**Comment by grobmeier** [comment]
Ok, I can reproduce this issue now.

I open IntelliJ, then GitUp: buttons are disabled.
When I open GitUp, then IntelliJ: buttons are enabled.

You mentioned there should be no conflicts, but there are.

**Comment by swisspol** [comment]
Are you talking about the buttons at the bottom right of the Map view, or the menu items? Are both affected?

Are you sure the HEAD is not detached?
