### ISSUE TITLE
Show menu view options not persistent

### ISSUE THREAD

**Issue by JamesBucanek** [git-up/GitUp#108]
I'm hoping this it the right place to report this.

The Show pop-up menu/button at the bottom left corner of the map view works just fine, but none of the settings are persistent. Every time I reopen the project, all of these view settings get reset back to their original values.

I'm running GitUp 1.0.4 (1012) on Mac OS X 10.10.5.

**Comment by swisspol** [comment]
That's not a bug, it's simply never been implemented :smile: Already tracked by #85.
