### ISSUE TITLE
Feature request: Show logs of git hooks

### ISSUE THREAD

**Issue by maxhoffmann** [git-up/GitUp#109]
Is it possible to add the output of git hooks to the popup, when something goes wrong? I normally use git hooks to setup linting and testing before pushing or committing. It would be great to see what went wrong right in the app.

**Comment by swisspol** [comment]
This should already be the case: the stdout and stderr is captured and returned in case of non-zero exit, and finally displayed in the UI:
https://github.com/git-up/GitUp/blob/9e447327c8601e1b086f9b154957b8063585e5a1/GitUpKit/Core/GCRepository.m#L247

**Comment by maxhoffmann** [comment]
![screen shot 2016-04-04 at 11 44 03](https://cloud.githubusercontent.com/assets/1227441/14245644/9c021ea2-fa5a-11e5-8e10-df536cc423fb.png)

I guess this is a bug report then. This is what I get, when linting fails. The error message are shown in the command line, in Tower and in SourceTree, but not in GitUp.

**Comment by maxhoffmann** [comment]
@swisspol So it looks like stdout is not captured when there is an error. The error got displayed as soon as I updated the implementation to always log to stderr. Looks like this is fine. :+1:
