### ISSUE TITLE
Show alternative Git commands when using GitUp

### ISSUE THREAD

**Issue by benmcrae** [git-up/GitUp#110]
When using GitUp, it would be great to see what commands are potentially being run underneath.

For example, editing your last commit would display the following output into a console window.

`git commit --amend -m "Updated commit!"`

I am assuming you are using libgit2 which may not make this so straight forward.

Thanks.

**Comment by swisspol** [comment]
GitUp doesn't use the Git tool at all but libgit2 so there are no commands to speak of.
