### ISSUE TITLE
explicit permissions from sharedRepository config not honored

### ISSUE THREAD

**Issue by mroi** [git-up/GitUp#112]
The git configuration option `sharedRepository` can be used to explicitly specify permissions of newly created files by setting it to `0xxx` with the `xxx` part giving the permission bits in the usual octal notation.

I have a repository with `sharedRepository` set to `0750`, but GitUp commits create new objects with world-readable permissions. I currently fix that using scripts, but it would be great if GitUp could support `sharedRepository` permissions directly.

**Comment by swisspol** [comment]
This would be at the https://github.com/libgit2/libgit2 level, not GitUp (which can't do anything about it). A quick look appears to show that indeed they are not considering this Git config option.

**Comment by mroi** [comment]
Thanks for that information. I’ll take this bug over there, then.
