### ISSUE TITLE
Cannot sign commits with gpg

### ISSUE THREAD

**Issue by domoritz** [git-up/GitUp#116]
## Reproduce:
* Set up gpg signing for commits (https://github.com/blog/2144-gpg-signature-verification)
* Enable global signing `git config --global commit.gpgsign true`
* Try to make a commit

## Error:

Cannot commit and get the following error

<img width="532" alt="screen shot 2016-04-10 at 17 00 00" src="https://cloud.githubusercontent.com/assets/589034/14413934/c93e629e-ff3d-11e5-8604-f62a3694a8bb.png">

**Comment by swisspol** [comment]
GPG commit signing is not supported by GitUp: see #42.
