### ISSUE TITLE
GitUp incorrectly shows file as deleted in Working Directory

### ISSUE THREAD

**Issue by clemper** [git-up/GitUp#117]
Hi,

I have a git repository checked out onto my Mac running OS X 10.11.4 using the default file system with "Is case-sensitive" = "No".  The repository has a directory containing 2 files that differ only by the case of a single character (i.e. "site-24x7.png" and "site-24X7.png").  At the terminal "git status" reports "nothing to commit, working directory clean"; however, GitUp indicates that the file "site-24X7.png" was deleted in the Working Directory pane of the Commit view.

Thanks,
@clemper

**Comment by swisspol** [comment]
GitUp is actually correct, while Git is not: you have 2 files with with conflicting casing in the Git tree, but only one can be checked out on a case-insensitive file system, so by definition is other one is missing i.e. deleted from the workdir.

See #93 for a similar issue and solution.

**Comment by clemper** [comment]
Thanks for your reply.  I'm not clear on the solution here.  I can't delete the file and I can't really use GitUp with this repository with it showing that it should be deleted.  Thanks again for your help.
