### ISSUE TITLE
Disable switching to Map view while reviewing merge/rebase conflicts

### ISSUE THREAD

**Issue by mcdado** [git-up/GitUp#119]
While the toolbar icons disappear, it's still possible to <kbd>cmd</kbd> + 1 to switch the the Map view. This can lead to crashes or state mess, since there is a merge situation, or detached heads, or unresponsive UI.

GitUp version b1016

**Comment by swisspol** [comment]
Fixed in 780e1b2ca08fd8acb54099073a8f3fa3bb92a925
