### ISSUE TITLE
Failed connecting to "origin" remote while trying to pull

### ISSUE THREAD

**Issue by dabd** [git-up/GitUp#127]
When I try to pull I get the following error: 

> Failed connecting to "origin" remote: error authenticating: failed connecting with agent

It works fine from the command line.

What could be causing this?

**Comment by swisspol** [comment]
Seems like an SSH authentication problem. What's the full URL of your remote?

Also read https://github.com/git-up/GitUp/wiki

**Comment by swisspol** [comment]
Make sure your SSH private keys are either in `~/.ssh/` or better added to the SSH agent, which you can do with `ssh-add -K ~/.ssh/my_private_key`.

**Comment by dabd** [comment]
I have my private key at ~/.ssh/id_rsa but for some reason gitup doesn't seem to be picking it up. I've been using it for some months now and it is the first time this happens.

**Comment by gihrig** [comment]
I too have my private key at ~/.ssh/id_rsa. 
I have added my to SSH agent
I have confirmed ssh access to github ssh -T git@github.com.

GitUp asks for user name and password. I would like to use my ssh key.

**Comment by swisspol** [comment]
Your git URL must be an SSH one, not HTTPS.

**Comment by jt3k** [comment]
the same problem. The ssh-key is in order.
if I do push from the console then there is no problem.

**Comment by SergioMP** [comment]
Reading this comments I found out that I was loading the incorrect set of ssh keys. Once I loaded the correct ones in GitKraken everything started working again. Thanks!

**Comment by leotm** [comment]
For me, despite initially granting access, after checking here: https://github.com/settings/connections/applications/a7557949433b7d282a76
It was revoked, so I had to just re-grant access.
