### ISSUE TITLE
Add support for Emoji in commit messages

### ISSUE THREAD

**Issue by torbjornvatn** [git-up/GitUp#129]
Wouldn't it be cool to render Emoji inline in commit messages just like on [Github](http://www.emoji-cheat-sheet.com/)?

**Comment by swisspol** [comment]
Emojis already render today through the regular OS X text rendering system. Maybe yours are not valid UTF8?

![image](https://cloud.githubusercontent.com/assets/627915/14835968/c427b554-0bc1-11e6-8353-d371a27376e0.png)

**Comment by torbjornvatn** [comment]
I was thinking about parsing the emoji codes found here http://www.emoji-cheat-sheet.com/, like `:smile:` :smile:

**Comment by swisspol** [comment]
I see. This would be way too complicated to support at this time as this requires adding support for markup rendering everywhere.
