### ISSUE TITLE
Config value 'user.name' was not found

### ISSUE THREAD

**Issue by cage1016** [git-up/GitUp#131]
when i edit commit message and save will get `Config value 'user.name' was not found` error.

<img width="420" alt="blank_skitch_document" src="https://cloud.githubusercontent.com/assets/678607/14888604/b2f0be66-0d8d-11e6-87d8-d69b3ee273e0.png">

**Comment by kileras** [comment]
Well it seems that you don't have a git username define so it won't allow you to do a commit as it cannot put your username on it :D

You can go to Repository > Edit Git Configuration and there add a new entry with user.name as key and you username as the value. You may also want to do the same for user.email too.

**Comment by cage1016** [comment]
@kileras. Thanks lot. It does work after adding new config user.name/user.email in `Repository > Edit Git Configuration`.  I have to manual add user.name/user.email config every time when i start a new git repo. Is it possible inherit those information from git global config?

**Comment by swisspol** [comment]
See https://help.github.com/articles/setting-your-username-in-git/
