### ISSUE TITLE
esc key doesn't act properly in edit mode with Browse sidebar open

### ISSUE THREAD

**Issue by mcdado** [git-up/GitUp#132]
Running [b1017](https://github.com/git-up/GitUp/releases/tag/b1017)

Steps:
1. select a commit in map view
2. press <kbd>cmd</kbd> + <kbd>D</kbd> to open sidebar with HEAD Ancestors (same for tags and reflogs)
3. click again on the commit to set the focus.
4. press <kbd>e</kbd> to enter edit mode
5. in this situation, pressing <kbd>esc</kbd> once closes the Browse sidebar, twice deselects the commit in the map view, third time on  does nothing.

Pressing <kbd>esc</kbd> with edit modal open should only dismiss the modal.

**Comment by mcdado** [comment]
Pressing <kbd>esc</kbd> to leave the `Create Branch…` (<kbd>B</kbd> shortcut) works, it's just the `Edit Message…` (<kbd>E</kbd> shortcut) that does not.

**Comment by antons** [comment]
Fixed by #360. /cc @swisspol
