### ISSUE TITLE
UI hangs when switching views

### ISSUE THREAD

**Issue by jasonrm** [git-up/GitUp#135]
Screen capture of view switching in [gitup](https://s3.amazonaws.com/jasonrm/2016/video/bc094c94cf0886893d627a9695126f0ed265531f528679a6e0c14d3e3113fe29.mp4) and [tower](https://s3.amazonaws.com/jasonrm/2016/video/75f17927d33a07951d2da763ef1d766d66664c64abcf3b1035dc2aa1458705f8.mp4) while working with the [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) repo.

I've done a shallow clone of the nerd fonts repo, but it appears to behave the same with a private repo with 64k+ commits.

sample process output during a 'hang' for a [private repo](https://gist.githubusercontent.com/jasonrm/b561028858c9a99d2d83a500220e6f7b/raw/b8910df8297b3114c7c9aa4b2a994e2fd9be5070/private-repo.txt) and for the [nerd-fonts repo](https://gist.githubusercontent.com/jasonrm/4dc6ad61cae6deabb999e124c021d2ca/raw/42b417586cda0bf90857888221595c37789e6a79/nerd-fonts.txt)

Was seeing this in 1.0.4 as well as the current 1.0.5 version.

**Comment by jasonrm** [comment]
Ah, looks like a possible duplicate of #83

**Comment by swisspol** [comment]
GitUp is indeed computing a diff and libgit2 is taking its time... How many files in that repo? The number of commits is irrelevant here.

**Comment by jasonrm** [comment]
nerd-fonts repo
```
$ git ls-files | wc -l
3308
```

a private repo
```
$ git ls-files | wc -l
14647
```

I wouldn't say it takes much longer in my private repo to switch views. Certainly didn't feel like a 4x difference.

**Comment by swisspol** [comment]
Definitely sounds like a dup of #45 or #83.
