### ISSUE TITLE
operation buttons all at top is better to use

### ISSUE THREAD

**Issue by yayowd** [git-up/GitUp#140]
I like GitUp, because is simple and modern style.
But in my use, I often move mouse pointer from left top to right bottom in GitUp, if move all buttons to top of GitUp, maybe is better to use.

Sorry for my poor English.

**Comment by swisspol** [comment]
The layout of buttons is not going to change in GitUp. However, you can work very fast by using keyboard shortcuts - see the wiki pages for info: https://github.com/git-up/GitUp/wiki.

**Comment by yayowd** [comment]
thanks
