### ISSUE TITLE
difftool.<tool>.path does not work

### ISSUE THREAD

**Issue by edwingeng** [git-up/GitUp#142]
I use Araxis Merge as my diff tool, which is not a build-in option. I have to choose 'Git Tool', but GitUp does not recognise difftool.\<tool\>.path and shows up the following message:

> Git diff tool requires both 'diff.tool' (or 'diff.guitool') and 'difftool.<tool>.cmd' to be defined in your Git configuration.

Here is my .gitconfig:
```
[diff]
	tool = araxis
[difftool "araxis"]
	path = /Applications/Araxis Merge.app/Contents/Utilities/compare
[difftool]
	prompt = false
```

**Comment by swisspol** [comment]
`difftool.<tool>.path` can only provide the path to the tool, not any optional arguments, so GitUp prefers  `difftool.<tool>.cmd` - see https://git-scm.com/docs/git-difftool.
