### ISSUE TITLE
Failed writing snapshots on non-HFS volumes

### ISSUE THREAD

**Issue by sjackman** [git-up/GitUp#144]
I frequently get the error message "Failed writing shapshots"
How can I troubleshoot this error?

**Comment by swisspol** [comment]
Only thing I can think of is that you're out of disk space? There might be more info in the console log.

Worst case, build and run app from Xcode and put a breakpoint on this error.

**Comment by ccodewa** [comment]
same problem for me on 1.05 (1017).
Happens only on git repos mounted on NFS.
1.0.4 works fine.

**Comment by swisspol** [comment]
I'm guessing that's because non-HFS volumes don't support `exchangedata()`: d78d6d3868e8b725238b13a56522bf387f6f4a67

**Comment by swisspol** [comment]
Note that using GitUp on repos which are not on HFS volumes is not supported anyway. File monitoring might not work correctly anyway.

**Comment by ccodewa** [comment]
Thank you Pierre.
What about disable the browse snapshot button and menu item on non-HFS filesystems repos instead of the "Failed writing shapshots" popup error?

**Comment by sjackman** [comment]
Even if it's not officially supported, `GitUp` has been working just fine for me up until now on a NFS file system.

**Comment by stigkj** [comment]
I get the same error on OpenZFS. The com.apple.mimic_hfs flag is set, but does not help. Just in case anyone is wondering :-)

**Comment by neeklamy** [comment]
I’ve just received this error on making a commit.

The repository is on an ext4 filesystem, and I’m connecting over SSHFS.

Could [fcntl](https://www.freebsd.org/cgi/man.cgi?query=fcntl) F_FULLFSYNC be used? I found this nugget of information:

> fsync may be really slow, but if it is not reliable that is a defect in the filesystem, block layer, or disk drive. On Mac OS X, fsync is documented not to be reliable, but there is at least a way around it using an F_FULLSYNC fcntl. On Linux (relatively recent versions anyway), fsync is documented to be reliable, i.e. to accomplish the purpose one might have for calling it in the first place.
> – butlerm ([direct](https://lwn.net/Articles/668353/)), from [Files are Hard](https://lwn.net/Articles/667788/)

Maybe this would be helpful too? [Everything You Always Wanted to Know About Fsync()](http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/).

**Comment by szhu** [comment]
For now, can you make that error a non-interruptive alert/flash message/banner? Like, there's nothing I can do about it anyway, so I'd rather not press OK every time this happens

**Comment by CrouchingMuppet** [comment]
I also get this error with a git repo hosted on a windows virtual machine and connected with smb://...

Seems to also affect launching the app as no window is displayed until using the context menu to reopen the repo.

**Comment by philip-wernersbach** [comment]
I'm getting this as well with a repo located on an NFS volume. Looking at commit d78d6d3, there's probably something else Gitup could fall back to if `exchangedata()` fails. For instance, symlinks are pretty atomic on all major UNIXes, filesystems, and NFS even has a LINK protocol operation, so maybe we can Getup can fall back to using symlinks?

**Comment by salutis** [comment]
This error message pops up all the time on APFS (macOS 10.13 Beta 1) too.

**Comment by matoelorriaga** [comment]
Same in macOS 10.13 High Sierra

**Comment by mcdado** [comment]
For what it's worth, I watched this morning the [WWDC 2017 video about APFS](https://developer.apple.com/videos/play/wwdc2017/715/) (timestamp 32:10), and saw that `exchangedata()` is deprecated ([see PDF file of slides](https://devstreaming-cdn.apple.com/videos/wwdc/2017/715gk347h3udl/715/715_whats_new_in_apple_file_system.pdf), page 81 or search for `exchangedata`).

Related: https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/ToolsandAPIs/ToolsandAPIs.html#//apple_ref/doc/uid/TP40016999-CH7-DontLinkElementID_15

**Comment by revansdxr** [comment]
I get this using 10.13 with the repository located in the iCloud Drive folder.

**Comment by jatins** [comment]
+1 Getting it on starting the app, and every commit operation in High Sierra. I second the short term fix of making it less intrusive than a popup since the intended operation succeeds.

**Comment by swisspol** [comment]
This should be fixed by #324

**Comment by swisspol** [comment]
I just released 1.0.9 with that fix.

**Comment by mcdado** [comment]
I think you mean https://github.com/git-up/GitUp/pull/351

**Comment by iest** [comment]
Thanks so much @swisspol!!
