### ISSUE TITLE
I can not get GitUpKit.framework (iOS)

### ISSUE THREAD

**Issue by GintokiS** [git-up/GitUp#146]
I download the zips from 
1. [git-up/GitUp](https://github.com/git-up/GitUp)
2. [git-up/libgit2](https://github.com/git-up/libgit2)
3. [git-up/Libraries](https://github.com/git-up/Libraries)
4. [swisspol/XLFacility](https://github.com/swisspol/XLFacility)
and unzip and copy 2, 3, 4 to the 1's  path "GitUp-master/GitUpKit/Third-party".
In Xcode, I set active scheme to "GitUpKit (iOS) > Generic iOS Device" and press cmd+b to build. Build success but no framework file in the folder. The "Products" in Xcode is "red".

I need some help. Thanks!

**Comment by swisspol** [comment]
Start by doing `git clone --recursive https://github.com/git-up/GitUp.git`, it's the only way to guarantee everything is set up correctly?

**Comment by swisspol** [comment]
Then try building and running "iGit" in the examples.

**Comment by GintokiS** [comment]
So slowly my netwoke is! Thans a lot, it works! @swisspol
