### ISSUE TITLE
.gitignore being ignored or misinterpreted

### ISSUE THREAD

**Issue by eseres** [git-up/GitUp#148]
Given the following .gitignore file:
```
/.*
/*
!/.gitignore
!/.gitmodules
!/subdirectory
```
And the following .gitignore file in above referenced 'subdirectory':
```
/.*
/*
!/.gitignore
!/src
```
Building the application, a '_build' directory is created in 'subdirectory' at the same level as 'src' directory is. And .DS_Store is also present in the 'subdirectory'.

With the above setup, the _build directory and its contents as well as the .DS_Store file will show up as unstaged changes despite that neither is explicitly added to the don't-ignore list.

Just to double check, I have tested the above setup with another Git client and neither the _build directory nor the .DS_Store file showed up as unstaged.

Thank you,
Erik

**Comment by swisspol** [comment]
This is actually bugs in libgit2:
- https://github.com/libgit2/libgit2/issues/3133
- https://github.com/libgit2/libgit2/issues/3224
- https://github.com/libgit2/libgit2/issues/3535
- https://github.com/libgit2/libgit2/issues/3696
