### ISSUE TITLE
Gitup basic workflow

### ISSUE THREAD

**Issue by Benjamski** [git-up/GitUp#152]
Maybe I'm missing something obvious but I've been digging through the documentation for gitup and looking elsewhere to avail.

How do I just begin to use gitup?
I have the application and the CLI tools but as far as I can tell the CLI tools are just for updating bookmarks? Do I have to make a bookmark for each repo I want to use gitup with? Do I have to open the gitup application and add a repo to it every time I use it? I'm not sure if I'm encountering a bug or just doing something wrong--but I haven't got  a straight answer yet on how exactly one _starts_ using it.

**Comment by swisspol** [comment]
Just launch GitUp and do "Open" in "File" menu to start interacting with an existing repo.
