### ISSUE TITLE
Slow remote repo pushing over ssh

### ISSUE THREAD

**Issue by crispinb** [git-up/GitUp#156]
I've found Gitup to be noticeably slower than the git to push to remote repos (generally private Bitbucket or github, over ssh). Knowing gitup uses its own library, which may do many things differently from git, I haven't considered this a problem so haven't reported it.

This morning, however, a push was taking an inordinate time (> 30mins), and failed twice (sorry, didn't note error in heat of work pressure). For the third attempt I used git instead, and it happened in a flash. That particular commit was merging in a branch that was already up to date in the repo, so wouldn't (I think?) involve much real payload. The repo contains one small one-man project (< 200 files).

The rub is that right now I'm working on very slow and flaky rural ADSL, so the 2 failures could easily have been transient issues unrelated to Gitup.

So my questions are: should I expect Gitup to push more slowly than git? If not, and it does, what should I log or investigate further?

**Comment by swisspol** [comment]
All of this lives in [libgit2](https://github.com/libgit2/libgit2) under GitUp. There's nothing GitUp can do if libgit2 has trouble with "flaky" SSH connections, sorry.
