### ISSUE TITLE
commit message stays when "Amend HEAD" is uncheck

### ISSUE THREAD

**Issue by yang-wei** [git-up/GitUp#157]
Amend HEAD is super useful when I need to do `git commit --amend`

But after I check the "Amend HEAD" and decided to not amend my commit message, the commit message stay.

Is this a feature or bug ?

**Comment by swisspol** [comment]
Neither, that's just how it is implemented :smile:

**Comment by dsego** [comment]
I think it should not behave like this, very counter-intuitive and annoying.
