### ISSUE TITLE
Any plans on porting it to Windows

### ISSUE THREAD

**Issue by RohithKumbharkar** [git-up/GitUp#158]
I really like the features of GitUp as I've seen on the website http://gitup.co/ but as its currently only limited to Mac & I'm running Windows many like me need this kind of GUI on Windows. So, any plans on porting it to Windows ?

**Comment by swisspol** [comment]
There are no such plans, sorry.

**Comment by ajmcgarry** [comment]
Should have wrote it in Electron then

**Comment by fake-name** [comment]
> Work quickly, safely, and without headaches.
> The Git interface you've been missing all your life has finally arrived.

I'm on windows. How is this true?

Literally the second line of the homepage. Maybe make it 

> The (MacOS Specific) Git interface you've been missing all your life has finally arrived (if you use MacOS, otherwise you're hosed).

At least put the platform-specific dependency somewhere *other* then the very end of the homepage, in  tiny letters.

**Comment by salutis** [comment]
@ajmcgarry 

> Should have wrote it in Electron then

No.
