### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by severin-lemaignan** [git-up/GitUp#160]
I'd love to play with this tool on Linux. Is any porting planned? What would be the main challenges for a port (I imagine the GUI toolkit being the likely biggest -- only? -- issue)?

**Comment by swisspol** [comment]
GitUp is pretty much a 100% Mac app and is not portable. A complete rewrite is needed for another platform.

**Comment by niutech** [comment]
How about GNUstep? Is it possible to compile GitUp using it?

**Comment by swisspol** [comment]
Someone could try but I doubt it.

**Comment by brylie** [comment]
Hm, would the [Electron platform](http://electron.atom.io/) help to make this a multi-platform tool?

**Comment by salutis** [comment]
@brylie Electron apps are slow.

**Comment by brylie** [comment]
@salutis is there a benchmark for reference?

**Comment by salutis** [comment]
@brylie JavaScript, HTML, and CSS add additional levels of abstraction.

**Comment by niutech** [comment]
Electron is slow compared to native apps and they know it:
https://github.com/electron/electron/issues/5672. Most importantly, I
cannot imagine how GitUp could be converted to a JS app.

**Comment by brylie** [comment]
There are a lot of considerations when calling an application or framework slow.

> This has much more to do with how individual Electron-based apps are written than it does Electron itself. 
> -- @mnquintana 
> https://github.com/electron/electron/issues/5672#issuecomment-221610291

---
> you are assuming that the speed difference between native apps and Electron based apps is purely dependent on Electron itself. How the apps which run on Electron are designed and written has a huge impact on their performance.
> @sedwards2009
> https://github.com/electron/electron/issues/5672#issuecomment-221532541

**Comment by brylie** [comment]
I am not trying to start a flame war here, as it was a simple suggestion for a multi-platform development framework. If there are some specific suggestions as to what parts of Electron are slow, and how it would relate to GitUp, that might lead to a productive discussion.

GitUp looks really nice, and I think people would enjoy using it on other platforms.

**Comment by swisspol** [comment]
GitUp is not your average Git client, which just display a table of recent commits with a few branches drawn next to it, and therefore could be written in pretty much any language and toolkit and have acceptable performance.

For GitUp to be able to load and render the topology of an _entire_ repo of 50,000 commits in less than one second, and let you navigate around this fast, it has to be highly optimized across the _entire_ stack.

Electron would mean an 100 MB app instead of 5 MB, 10X slower, a UI that breaks many OX conventions, and let's not forget, a vastly more complicated and slower build system and write-run-debug development loop.

**Comment by brylie** [comment]
We are missing the point here. What might be a path towards cross-platform support?

**Comment by swisspol** [comment]
A rewrite.

**Comment by brylie** [comment]
Point taken.

**Comment by swisspol** [comment]
:wink:

**Comment by brylie** [comment]
What technologies would be worth considering for multi-platform suport?

For example, it may be of value to consider the web platform:
- [HTML5 canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API)
  - www.kevs3d.co.uk/dev/lsystems/
- [WebGL](https://www.khronos.org/webgl/)
  - http://threejs.org/examples/webgl_performance.html

**Comment by brodock** [comment]
@brylie most probably QT... I guess it's the only "viable" alternative.

**Comment by wmertens** [comment]
I found gitup through the interview @swisspol did with The Changelog, and I seem to remember that the app internally uses GitUpKit, which was meant to be a better git library.

I took a look at it and I presume that the super-cool features of GitUp, namely undo/redo and all sorts of tree manipulations, are implemented there. It is written in ObjC, but that is cross-platform, right? So it is only the commit display and the UI that would definitely require a rewrite?

**Comment by wmertens** [comment]
Actually, I'm wrong :) GitUpKit also includes a lot of view code. So, yes, a full rewrite…

**Comment by brylie** [comment]
Yeah. Unsubscribing due to the fact that Linux support is not likely.

**Comment by niutech** [comment]
Not necessarily a full rewrite. Apart from GNUstep, there is a GTK+ binding for Objective-C - [GTKKit](https://github.com/KyleCardoza/GTKKit) and [IUP](http://webserver2.tecgraf.puc-rio.br/iup/) (a portable native GUI) binding for Cocoa - [IupCocoa](https://github.com/ewmailing/IupCocoa).
Another way is to convert Obj-C to Swift using e.g. [Swiftify](https://objectivec2swift.com/) and use a GTK+ binding for Swift - [SwiftGtk](https://github.com/TomasLinhart/SwiftGtk).
Any volunteers?

**Comment by astubbs** [comment]
Anyone know a tool for Linux that has gitup's reflog viewer / navigator type functionality? I miss it :(

**Comment by wmertens** [comment]
@astubbs no reflog viewer but ungit is the closest I found. I have a pr in progress on there where eventually I hope to incorporate some of gitups ideas.

I'm also using libgit2 but encountering weird issues with diffs sometimes.

**Comment by KaKi87** [comment]
Hello there, some people talked about Electron, but I would like to suggest [Tauri](https://tauri.studio), which is a Rust-based alternative providing the same features without but outputting small and fast apps.

**Comment by wmertens** [comment]
@KaKi87 getting very off-topic, but Tauri doesn't seem to include NodeJS, which would be necessary for many of these kinds of apps?

**Comment by KaKi87** [comment]
No, because Tauri provides many APIs, including filesystem, shell and HTTP features, which should be enough to manipulate local and remote git repositories.

**Comment by codymikol** [comment]
Working on this over here if anyone is still interested: https://github.com/codymikol/git-down
