### ISSUE TITLE
Unable to Push/Pull with Error: authentication required by no callback set

### ISSUE THREAD

**Issue by bjg222** [git-up/GitUp#161]
I have a simple git repo that I cloned in the command line, then opened via GitUp.  I can push/pull via command line just fine, but when I try to the buttons in the lower right hand corner of GitUp, I get the error seen in the attached image.  My server is on my local work network and does require authentication via SSH, for which I have a trusted key set up for passwordless SSH.  I have been unable to find a setting that relates to push/pull that the error message could be referring to.

<img width="1006" alt="screen shot 2016-06-06 at 6 13 04 pm" src="https://cloud.githubusercontent.com/assets/11563394/15839714/edd24ace-2c12-11e6-81c0-4b262a1156e3.png">

**Comment by swisspol** [comment]
Make sure your Git remote URL uses a standard format and see https://github.com/git-up/GitUp/wiki.

**Comment by bjg222** [comment]
I've reviewed the known issues before posting, but I'm not sure how that helps me?  The page doesn't refer to the remote URL format at all.  Also, I do not control the remote server, but just use it.  The URL I am provided is this: server.company.com:/repo/tools

**Comment by libmaru** [comment]
@bjg222 You do have set up password-less authentication for SSH, but not for GitUp.

According to https://github.com/git-up/GitUp/wiki:
> * SSH config files (typically located at ~/.ssh/config) are ignored by GitUp since it uses libssh2 and not the ssh tool for SSH remote operations.
>   * GitUp first attempts to find SSH private keys using the ssh-agent
>   * It then tries all private key files in ~/.ssh/

GitUp found ssh-agent instance for your login session and ask for available private keys, which does not include your non-default SSH identity.
To solve your problem, `ssh-add -K <path_to_your_key>`.

**Comment by wprater** [comment]
I have a key added and Im still getting this error.  any ideas?

**Comment by LJeub** [comment]
I was having the same issue and running `git fetch` on the repo from the terminal resolved it for me. No idea why that worked?

**Comment by luongvo2009** [comment]
I believe a solution for this issue was discussed here https://github.com/git-up/GitUp/issues/35

**Comment by xtazz** [comment]
Still having this issue cause I have IdentityAgent configured in ssh config, but it's ignored by GitUp. Can I somehow config GitUp to make it work?

**Comment by SenHeng** [comment]
This is probably an old issue but it's the first result that pops up on google so for future google arrivers here is the issue.

MacOS has a habit of forgetting to restart the ssh-agent on boot, even after adding `UseKeychain yes` to the ssh config. The simple way is to trigger the ssh agent by running `git fetch` in the terminal, ssh-agent is then re-activated and GitUp will work again without any changes necessary.
