### ISSUE TITLE
add support for authentication using .netrc

### ISSUE THREAD

**Issue by ginader** [git-up/GitUp#163]
CLI git as well as GUIs like Tower or the Github app use this directly and I'm never prompted for a password. GitUp does. 
I LOVE GitUp and would love to use it as my main app. This is the only thing keeping me from doing so (I have to switch to CLI to push)

**Comment by swisspol** [comment]
What does "authentication using .netrc" exactly mean?

Note that these other software use the Git CLI tool, which itself uses the SSH CLI tool etc... GitUp doesn't use any of this but libgit2.

**Comment by ginader** [comment]
Oh I see! This probably means that I need to file this request with libgit2 instead. Thanks for the heads up!
BTW: "authentication using .netrc" means: adding a .netrc file with auth data (username and hashed password for a server) allows Git CLI to directly access the server without ever prompting for a password

**Comment by swisspol** [comment]
Over what protocols?

**Comment by swisspol** [comment]
It may or may not be in libgit2, libgit2 has a callback to ask the client for login/password for HTTP or key for SSH. GitUp implements them to look in Keychain for HTTP and `~/.ssh` for SSH, but that's it.

**Comment by ginader** [comment]
It actually doesn't store any protocol. My current .netrc file looks like this: 
`machine bla.com login email@domain.com password hAsHeDPaSsWoRd12345`
It allows me to access the machine via ssh or git prototcol

**Comment by sesam** [comment]
This with .netrc seems horribly insecure. Not supporting it is probably a good idea in these times of ransomware and stealer trojans. You can surely find a way to set up secure personal ECDSA or SHA2 keys instead, and use ssh-agent to enter the password less often (like once after every login).

Suggest closing this.

**Comment by lucasderraugh** [comment]
I agree, I think the days of storing passwords in plain text are pretty behind us.

**Comment by sirghi** [comment]
How does GitUp query the keychain because I introduced my credentials to Github once for a https remote, but I have to introduce them every time when I push. So somehow it's not finding the entry in the keychain.

P.S. ❤️ this app
