### ISSUE TITLE
Placing the commit message editor to the right of the files list

### ISSUE THREAD

**Issue by brechtm** [git-up/GitUp#168]
With the current layout of the Commit view, the message editor is about twice as wide as it needs to be. It would be better to have the file list (working directory / index) occupy the full height of the window, and place the message editor to the right of it. This will allow for more files to be displayed at once.

This could be made configurable, but I personally don't see a reason to have such a wide commit message editor.

**Comment by swisspol** [comment]
Thanks for your feedback but I have no plan to revise this UI.
