### ISSUE TITLE
Faulty unstaged changes

### ISSUE THREAD

**Issue by pihao** [git-up/GitUp#170]
Why gitup give the strange unstaged files ?

git status:
![git](https://cloud.githubusercontent.com/assets/3308394/16753741/effd85ca-481e-11e6-83cb-98c1819a0876.png)

GitX:
![gitx](https://cloud.githubusercontent.com/assets/3308394/16753745/f616025c-481e-11e6-9894-6803741a9ed0.png)

GitUp:
![snip20160712_7](https://cloud.githubusercontent.com/assets/3308394/16753835/aa0239ac-481f-11e6-8952-ccf48fa77780.png)

**Comment by swisspol** [comment]
See #117 and #93.

**Comment by pihao** [comment]
Thx!
I understand the reason you said.
But from the user's perspective, We hope GitUp have the same behavior with git command line client.
After all, It's a bad user experience if everyone should solve this `problem` like this.

**Comment by swisspol** [comment]
That would be a mistake: if you have a repo with 2 files named `A.txt` and `a.txt`, only one can exist in the workdir on HFS+ (and which one is undefined), so the other one is missing and therefore your checkout is **not** clean. That missing file could result in obscure issues and bugs in your product. Plain ignoring this problem and not reporting it to the user is what is bad user experience.

**Comment by pihao** [comment]
You are right if user expect case sensitive.
There is a git config 'core.ignorecase'. Is GitUp should case sensitive? Maybe should base on it?
