### ISSUE TITLE
Allow discarding of multiple file changes with one action

### ISSUE THREAD

**Issue by phraemer** [git-up/GitUp#176]
When selecting multiple files in the commit view it would be very useful to be able to discard changes in all the files with one action. Currently one must click on the gear icon beside the "Stage file" button and click "Discard file changes..." once for every file.

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View.

**Comment by phraemer** [comment]
Ahh ok. There is no GUI equivalent for this is there? I.e. it's not really a shortcut in the sense that it is bound to some menu or button?

**Comment by swisspol** [comment]
No GUI equivalent. GitUp is designed to be driven from the keyboard 😄

**Comment by phraemer** [comment]
Cool, makes sense. GUI aids with discover but yeah. Thanks for the good work 👍
