### ISSUE TITLE
Shortcut for "View in Diff Tool…"

### ISSUE THREAD

**Issue by szhu** [git-up/GitUp#178]
I accidentally activated the "View in Diff Tool…" feature today:

<img width="499" alt="screen shot 2016-07-26 at 5 00 22 pm" src="https://cloud.githubusercontent.com/assets/1570168/17159471/778765cc-5352-11e6-8f9a-34bb5f363177.png">

The thing is, I don't think I opened this menu as part of that accidental process, but I'm not sure. I'm wondering if there is indeed a shortcut that runs this command. (If not, there should be!)

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View.

**Comment by szhu** [comment]
Thanks! Is there any way these shortcuts can be displayed in the menu like they are for the Map View commands?

**Comment by swisspol** [comment]
Not easily as these shortcuts bypass the menu command system.
