### ISSUE TITLE
"Config value user.name not found" with global config only

### ISSUE THREAD

**Issue by junkblocker** [git-up/GitUp#180]
Tried to use GitUp for the first time. I have ``user.name`` and ``user.email``  in my git global config but not in local repository config but GitUp throws the error at me.

```
% git --version
git version 2.9.2

% pwd
/Users/xxxx/work/mine/xxxxxxxxxxx

% git config --show-origin user.name 
file:/Users/xxxx/.gitconfig     Xxxxxxxx Xxxxx
```

**Comment by swisspol** [comment]
GitUp doesn't deal with config files, it would be a [libgit2](https://libgit2.github.com/) issue I'm afraid.

**Comment by cstork** [comment]
I had the same problem and couldn't find anything useful googling for a libgit2-based solution.

Work-around in the local `.git/config`:
```
[include]
        path = /home/dir/.gitconfig
```
