### ISSUE TITLE
Beyond Compare can't be found

### ISSUE THREAD

**Issue by mikecrittenden** [git-up/GitUp#194]
I have Beyond Compare installed and working, but when I select that as my merge tool and click "Resolve In Merge Tool", it says that it can't be found.

**Comment by swisspol** [comment]
You need to have the tool installed:
https://github.com/git-up/GitUp/blob/a4ae7a0e6b2c801724444b2c72c0dbd1e473aca1/GitUpKit/Utilities/GIViewController%2BUtilities.m#L377

**Comment by mikecrittenden** [comment]
Do you mean the command line tools? If so, then I do, and I've restarted GitUp. It also fails for Kaleidoscope app.

**Comment by swisspol** [comment]
Yes, CLTs, which are expected to be at these paths:
https://github.com/git-up/GitUp/blob/a4ae7a0e6b2c801724444b2c72c0dbd1e473aca1/GitUpKit/Utilities/GIViewController%2BUtilities.m#L29

**Comment by mikecrittenden** [comment]
Ah, I'm with you now, thanks! It might be nice to update the popup to make that clearer.

**Comment by HunterDG** [comment]
came here for this! - seems both GitUp AND BC command line tools need to be installed.  Error could definitely be more descriptive!
