### ISSUE TITLE
Add a dark theme to style settings, it currently contrast too sharp to some of the text editors.

### ISSUE THREAD

**Issue by congwenma** [git-up/GitUp#198]

**Comment by lapfelix** [comment]
I have a [really rough (but working) dark theme fork implementation I did for myself](https://github.com/lapfelix/GitUp/tree/dark_mode). It's not complete, but here's how it looks right now:

![screen shot 2016-09-27 at 9 48 00 pm](https://cloud.githubusercontent.com/assets/4634735/18897967/8e712756-84fc-11e6-9548-1338059a58a5.png)
![screen shot 2016-09-27 at 9 48 41 pm](https://cloud.githubusercontent.com/assets/4634735/18897968/8f6977a8-84fc-11e6-923f-a6ae860c5ba9.png)
![screen shot 2016-09-27 at 9 51 23 pm](https://cloud.githubusercontent.com/assets/4634735/18897972/92b454dc-84fc-11e6-831f-72a4eaab353a.png)

I really did this for myself only and the `dark_mode` branch is currently on top of another one of my branches that has markdown enabled, so it's not ready for a pull request at all.

Actually if I were to submit a PR I would probably rewrite it from scratch (and differently).

@swisspol, if you had to implement a dark theme in Gitup, how would you do it ?

**Comment by congwenm** [comment]
@lapfelix awesome, so eager to use this. Is there a contrast setting?

**Comment by lapfelix** [comment]
Hmmm yeah as I said this was really built for myself and I like to have a black background (I'm probably a minority), but I could pretty easily let you customize the colors, yes.

( Though I'm trying to not put too much time into this dead-end branch haha )

**Comment by congwenm** [comment]
@lapfelix where can I find the executable that's been built, so I dont have to rebuild this every time i need to use it?

**Comment by lapfelix** [comment]
Here's the latest build I have for this branch: https://cl.ly/harx/download/GitUp.app.zip

**Comment by lapfelix** [comment]
I wouldn't want to add a _Github release_ for this branch because it would feel like openly distributing a forked version of Gitup and I wouldn't be comfortable with that.

**Comment by aristidesfl** [comment]
Suggestion for color scheme:
![screen shot 2017-01-05 at 18 01 51](https://cloud.githubusercontent.com/assets/208149/21689583/179b1934-d371-11e6-86c7-3c45e423164e.png)

**Comment by TableMountain** [comment]
any chance of this sort of feature ever landing in git-up/master?

**Comment by LunaticoCR** [comment]
I'm all for dark themes too, find it easier on the eyes. I'm sure once this is put in place a lot of people would start contributing theme files in.

**Comment by lucasderraugh** [comment]
With support for Mojave Dark Mode #463, I'm going to close this issue. The feature is only available from source at the moment, but we'll be working it into the continuous release channel, and eventually stable.
