### ISSUE TITLE
[Feature request] Ability t rewrite the first commit

### ISSUE THREAD

**Issue by chenglou** [git-up/GitUp#202]
It's greyed out.

**Comment by swisspol** [comment]
I don't remember the details but there are technical reasons while the first commit has to be treated specially, so that limitation is not going to change.

**Comment by chenglou** [comment]
It's possible on the command line right? http://stackoverflow.com/questions/2246208/change-first-commit-of-project-with-git
Or maybe gitup makes some other assumption about it?

**Comment by swisspol** [comment]
GitUp doesn't use the Git CLI at all, but libgit2.
