### ISSUE TITLE
[Feature request] Reset changes of file(s)  

### ISSUE THREAD

**Issue by AlexIzh** [git-up/GitUp#203]
Currently, gitUp can discard all changes only. Sometimes needed reset only one or few files, but not all. (it would not so necessary if partial stashing exists. We just could move files to stash, discard rest files and get files from stash. But unfortunately, this feature doesn't exist too)

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View.

**Comment by AlexIzh** [comment]
Thanks, but would cool if contextual menu was here too (right click on file(s), selection files with `cmd` and so on). It is more intuitively for new users and help memorize shortcuts

**Comment by AlexIzh** [comment]
@swisspol will be ok if I create new issue for contextual menu in commit view?

**Comment by swisspol** [comment]
There's a contextual menu in the diff area already (gear icon) which should do that IIRC.
