### ISSUE TITLE
Swap with Child (Move Up) Shortcut doesn't work right after exiting Quick View

### ISSUE THREAD

**Issue by shadowwalkersb** [git-up/GitUp#209]
To make it work again, I bring next commit down first, then I can use (U) again. It is not always, but it is most of the times. It has happened enough to motivate me to report it.

**Comment by swisspol** [comment]
Nobody has ever reported such an issue and without a reproducible case, there's nothing that can be done unfortunately. If you have one I'll reopen this issue.

I'm suspecting you are maybe pressing a modifier key at the same time you are pressing u, but without realizing it.

**Comment by shadowwalkersb** [comment]
<img width="520" alt="screen shot 2016-09-19 at 12 09 09 am" src="https://cloud.githubusercontent.com/assets/7955353/18623031/a74399ae-7dfd-11e6-9fe8-94719288f8e0.png">

---

**After the workaround mentioned above, it is not greyed out anymore.**

<img width="532" alt="screen shot 2016-09-19 at 12 13 16 am" src="https://cloud.githubusercontent.com/assets/7955353/18623041/ea259150-7dfd-11e6-9798-baaa838de3a6.png">

**Comment by swisspol** [comment]
Which workaround?

**Comment by shadowwalkersb** [comment]
https://github.com/git-up/GitUp/issues/209#issue-174399874

**Comment by swisspol** [comment]
So for some reason GitUp would think this commit has more than 1 child (i.e. it's a branch point) when exiting Quick View?
https://github.com/git-up/GitUp/blob/727673b7454aab82023d4807a1b53d1ecd7a9295/GitUpKit/Views/GIMapViewController.m#L707

Can you make sure everything is visible in the Map view and this commit is not a branch point?

**Comment by shadowwalkersb** [comment]
Actually, the screenshots were not taken after exiting Quick View, I think, as stated in the title. So, the problem may not be Quick View specific.
The commit is not a "branch" point, but the blue trace in the screenshots is a tag. So, maybe GitUp doesn't differentiate between real branches and tags? They are all blobs, after all.

**Comment by shadowwalkersb** [comment]
Why would a commit in a "tag" be considered a child? Can you write to that tagged branch? What's the point?

**Comment by shadowwalkersb** [comment]
Yeah, expected but non-intuitive. I get it!  Why do I even bother?
