### ISSUE TITLE
OpenSSL is no longer in the 10.12 SDK

### ISSUE THREAD

**Issue by AndrewHoos** [git-up/GitUp#210]
See this note from another [project](https://bugreports.qt.io/browse/QTCREATORBUG-16718). openSSL is no longer in the 10.12 SDK so projects linking against libcrpyto/libssl in the SDK will no longer work. The build needs to be adjusted to either link against the libcrypto/libssl on the host(which may be incompatible) or needs to build openSSL and statically link it.

**Comment by swisspol** [comment]
GitUp nor GitUpKit depend on OpenSSL, and neither does libgit2, which is configured to use the built-in OS X crypto. However, libgit2 uses libssh2 which does use OpenSSL.

**Comment by swisspol** [comment]
This was actually already fixed for iOS, but not OSX: 7d65b8445089b11a799e0d71b0078e84b8cfdbe2.

**Comment by AndrewHoos** [comment]
Awesome :)
