### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by montogeek** [git-up/GitUp#211]
Hi!

I have been using the app since months now, just 2 minutes ago I updated to v 1.0.6, after read previous release notes I found out that the app will start sending anonymous tracking data to Google Analytics, although I have no problem at all with the tracking some people will no find it particular trustworthy.

It would be nice to add an option to activate the tracking or not, or at least show a note saying that are being tracking

Cheers from Colombia!

**Comment by swisspol** [comment]
Thanks for the feedback. Just to be clear, people are not "being tracked": as anyone can see in the source code, a single anonymous GA event is sent without any data whatsoever from the user, host computer, repositories or anything else. The intent is simply to get an idea of the user base, and there's no other reliable way to know that (short of distributing GitUp only through the Mac App Store).
