### ISSUE TITLE
Feature request: "Open pull request"

### ISSUE THREAD

**Issue by mrh-is** [git-up/GitUp#212]
SourceTree has a quite useful menu item called "Create pull request..." which opens a browser tab which has prefilled PR details from the current branch onto `master`. It's helpful for a branch-driven development style.

**Comment by hawkrives** [comment]
IIRC, Gitup already has this: 
![image](https://cloud.githubusercontent.com/assets/464441/18299245/2859e6ea-74fa-11e6-8533-cfa5e084f3b0.png)

You can access it by right-clicking a branch, and going to the "Edit Remote Branch" submenu at the bottom.

I think it only shows up if the branch is on the remote, and the remote's URL ends in `.git`.

**Comment by swisspol** [comment]
Thanks @hawkrives!
