### ISSUE TITLE
Window toolbar layout sometimes broken on macOS Sierra 

### ISSUE THREAD

**Issue by antons** [git-up/GitUp#214]
Occasionally windows are loaded (or restored?) with a broken toolbar layout on macOS Sierra. 

<img width="884" alt="screen shot 2016-09-11 at 8 13 08" src="https://cloud.githubusercontent.com/assets/129705/18417047/7e006916-782e-11e6-8bc5-beac8dc0c76b.png">

The issue can be fixed by reopening the repository. 

I do not yet have clear steps to reproduce. I suspect the issue may be related to tabs.

**Comment by donut** [comment]
I'm getting this all the time now. I can't even see the buttons unless I make the window full width of my screen.

Normal width:  
![Normal width](https://www.dropbox.com/s/cjm00ivld355ogy/Screenshot%202016-12-01%2009.29.13.png?dl=1)

Full width:  
![Full width](https://www.dropbox.com/s/u5unyx9ii02eg5c/Screenshot%202016-12-01%2009.30.14.png?dl=1)

**Comment by swisspol** [comment]
I’ve been using GitUp on Sierra for a long time and never saw this issue. One way or the other must have been fixed by now.

**Comment by antons** [comment]
I stopped seeing it a while ago too. Nice!
