### ISSUE TITLE
Swap commit changes unrelated branch-off point

### ISSUE THREAD

**Issue by shadowwalkersb** [git-up/GitUp#218]
After, doing a swap-commit (D or U), a branching-off point that appears later in history is brought down before the moved commit. The first three screenshots are a vertical panoramic illustration of the repo before the operation, the last two are for after the operation.

---
<img width="1548" alt="screen shot 2016-09-17 at 1 05 02 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610169/bddc7146-7cda-11e6-8d64-41b4bc743bf3.png">
<img width="1548" alt="screen shot 2016-09-17 at 1 04 55 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610177/dc4ecc78-7cda-11e6-945a-8f5858a82070.png">
<img width="1548" alt="screen shot 2016-09-17 at 1 04 45 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610178/dee07ff4-7cda-11e6-9dbf-ba0f0d2febda.png">

**Before swap-commits**

---

<img width="1548" alt="screen shot 2016-09-17 at 1 05 38 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610181/ef37cc18-7cda-11e6-9597-d33241d20c35.png">
<img width="1548" alt="screen shot 2016-09-17 at 1 05 24 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610184/f1de1198-7cda-11e6-80b8-b0907d1b79ea.png">

**After swap-commits**

---

**Comment by swisspol** [comment]
That's expected behavior: that green branch is likely a remote one, so it can't be updated like the local branches as part of the rewrite.

**Comment by swisspol** [comment]
Whenever you rewrite a commit with GitUp, all its descendants must be rewritten accordingly, and dependent on what the branch tips are (local or remote) you will get such behavior. There's no other choice.

**Comment by shadowwalkersb** [comment]
Any chance we can confirm within GitUp that it is really a remote branch? And, is it possible to have GitUp not to show remote branches. that will help with such confusions.

**Comment by swisspol** [comment]
Remote branches are clearly indicated in the Map View - See the wiki for help on GitUp.

**Comment by shadowwalkersb** [comment]
Yeah, well, that branch is not a remote. The repo looks the same even after I remove the remote.
<img width="1548" alt="screen shot 2016-09-17 at 1 45 32 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610253/0b25bf96-7cdd-11e6-9381-cb9e4bb762c7.png">

**Comment by shadowwalkersb** [comment]
Yeah, well, that branch is not a remote. The repo looks the same even after I remove the remote.

**Comment by swisspol** [comment]
You need to look at the top of map view to see if there's still a remote branch associated with this tip.

**Comment by shadowwalkersb** [comment]
No, there is not a remote branch whatsoever.

**Comment by swisspol** [comment]
If you swap 2 commits, they both get rewritten as well as any of their descendant commits on any branch. Not all branch tips will change though: if you have a branch that is local and remote, the local part will be rewritten and the remote not, so in the Map view, you end up with 2 branch tips instead of 1, and further down you observe a new branch point appear where the swap occurred. I don't recall exactly but there might be other exceptions in the rewrite logic, where some local branch tips would be left alone because it's safer / better, and therefore you have a new branch point appear below the commit swap.

Without seeing the entire repo map, it's not possible to say if there's actually a bug. I'm quite skeptical there's one though: I'm suspecting an expected but not intuitive behavior.

**Comment by shadowwalkersb** [comment]
<img width="1548" alt="screen shot 2016-09-17 at 3 37 11 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610845/cd0e2fda-7cec-11e6-8bc0-c30542b9f192.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 37 05 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610847/d5fc99e2-7cec-11e6-916f-05da7d9090dc.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 58 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610848/d9dc4026-7cec-11e6-8031-e0d0e3eb7e22.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 50 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610851/dd3bc674-7cec-11e6-82ca-6a05e8e76892.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 43 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610853/e04fe656-7cec-11e6-96db-cc6c43f77cbe.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 33 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610854/e358fcfc-7cec-11e6-8ab6-b533b4bc7ea9.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 21 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610855/e88e2922-7cec-11e6-97da-38512aff8a55.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 16 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610856/eb3f3dd2-7cec-11e6-950c-9d85c257b022.png">
<img width="1548" alt="screen shot 2016-09-17 at 3 36 05 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610857/eed0a1ca-7cec-11e6-95a9-0bcc3049c2bc.png">

**Comment by shadowwalkersb** [comment]
And this is a copy of the original repo, https://github.com/GorgonCryoEM/Gorgon-refactor-gitup.git. I didn't want to mess with my work. I can see the same behavior with this repo, too.

**Comment by swisspol** [comment]
Which exact operations need to be done with this repo to reproduce this behavior that concerns you?

**Comment by shadowwalkersb** [comment]
I have tried U, D and E on 185b7440bfebdc17c298857c654a8ed65f07a6b7 and f5386f64dc29aca7334eeff3ad2919327e57bd99. But, it seems like it happens on any commit around those two. Is it the merges that cause problems?

**Comment by shadowwalkersb** [comment]
It seems like the green branch is rewritten after the operation, but the blue one is not affected. Just as you described it for a remote branch. But, this one is not a remote branch, just one of the merged branches.

<img width="1548" alt="screen shot 2016-09-17 at 9 19 24 pm" src="https://cloud.githubusercontent.com/assets/7955353/18612318/9bd33fac-7d1c-11e6-96d9-f463327f618c.png">
<img width="1548" alt="screen shot 2016-09-17 at 9 19 31 pm" src="https://cloud.githubusercontent.com/assets/7955353/18612319/9bd34dc6-7d1c-11e6-96cf-496eb77ed0a0.png">
<img width="1548" alt="screen shot 2016-09-17 at 9 20 06 pm" src="https://cloud.githubusercontent.com/assets/7955353/18612320/9bdc310c-7d1c-11e6-8cba-281b51547bdf.png">

**Comment by shadowwalkersb** [comment]
Any chance this will be fixed? It is a blocker. And, if there is no intention to change the behavior, it would be good to know.
