### ISSUE TITLE
How do I disable showing remote bracnhes?

### ISSUE THREAD

**Issue by shadowwalkersb** [git-up/GitUp#219]
I have disabled remote branch tips from the show menu and I can still see the remote branch. Is this intended? What is the option in the menu for?

<img width="1440" alt="screen shot 2016-09-17 at 3 56 49 pm" src="https://cloud.githubusercontent.com/assets/7955353/18610940/dbbd0666-7cef-11e6-9c14-8c0010b84f65.png">

**Comment by swisspol** [comment]
You did it right. The remaining remote branch is still visible because it's the upstream of the current local branch.

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/blob/727673b7454aab82023d4807a1b53d1ecd7a9295/GitUpKit/Interface/GIGraph.m#L200

**Comment by shadowwalkersb** [comment]
Can we make that invisible as well? In other words, can we hide remote branches altogether? I suspect, that may be what is happening in issue #208. When doing Command+Up in Quick View, GitUp follows the straight path up if there is branching. That straight up path is the remote branch. If we can disable remote branches, that problem would be solved.

**Comment by swisspol** [comment]
I have no intention to change this behavior: the current branch is a special case IMO and people seem to be fine with that as well.

QuickView ignores what's visible and invisible in the map view: it always navigates the real topology of the repo.

**Comment by shadowwalkersb** [comment]
Real topology of the remote or local?

**Comment by shadowwalkersb** [comment]
I bet no one complained about that either.

**Comment by swisspol** [comment]
The topology of the repo meaning all branches and tags and HEAD.

**Comment by shadowwalkersb** [comment]
So, when a branch deviates from its remote, would it follow the remote or the local in Quick View if I go up with Command+Up?

**Comment by swisspol** [comment]
It will follow one then backtrack and follow the other IIRC. If you have more questions like that, check the wiki docs first, and if it's not there just look at the code. I wrote most of it a couple years ago so I don't remember all the edge cases.

**Comment by shadowwalkersb** [comment]
These are not edge cases. They are my regular day-to-day operations. And, as opposed to the claims in the README, they cause me waste of time and breaking my repo! I would be happy to read the Wiki if you point me to the part that answers my last question. As for reading the code, it's a pity that Objective-C is not my language. Otherwise, I would have forked and changed it by now. Sorry for bothering! GitUp's concept is a good step, but most of the remaining parts make it almost useless ATM, at least for me. Thanks, anyways!

**Comment by shadowwalkersb** [comment]
How about providing an option in Preferences which has the current behavior as default?
