### ISSUE TITLE
Improve "Discard All" UX by doing "Discard" changes of selected file(s) only

### ISSUE THREAD

**Issue by aleemb** [git-up/GitUp#220]
I find it much more desirable to discard individual files which is tucked away in the per-file settings icon. How about changing "Discard All" to just "Discard" the selected file(s). Discarding all would be also quite easy (select all first) and improve the UX by reducing clicks.

**Comment by swisspol** [comment]
Just use the keyboard shortcuts 😄 
https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View

**Comment by aleemb** [comment]
Am aware of the shortcut but this is a UX bug. To illustrate what it's easy to confuse the issue in the following screenshot where discard all where discard everything, not just selected items:

![image](https://cloud.githubusercontent.com/assets/46616/18675522/0c3dd896-7f6c-11e6-889f-f4123abde41e.png)

**Comment by aleemb** [comment]
Related https://github.com/git-up/GitUp/pull/28
