### ISSUE TITLE
merge tool doesn't work

### ISSUE THREAD

**Issue by lyqeyes** [git-up/GitUp#221]
![image](https://cloud.githubusercontent.com/assets/9962597/18656632/6f5c1b46-7f25-11e6-8a28-87389b02d3f4.png)

code merge conflicts,  but when I click the ‘Resolve in Merge Tool’ button, noting happened!

I do want this function,  help please.

**Comment by hawkrives** [comment]
<img width="612" alt="screen shot 2016-09-20 at 12 31 29 pm" src="https://cloud.githubusercontent.com/assets/464441/18656683/34ebe816-7f2e-11e6-92c1-21b4d5045bfc.png">

Do you have a tool selected in Preferences?

**Comment by lyqeyes** [comment]
![image](https://cloud.githubusercontent.com/assets/9962597/18656854/6ab280b0-7f27-11e6-9149-871a7180c6b5.png)


what my GitUp chosen is 'FileMerge' ,the default choice.  
In fact, I tried all of these choices,  with others, when I click 'Resolve in Merge Tool’,  error reported( like 'uninstall' ).
 
Dose any other tool need?

**Comment by hawkrives** [comment]
I think that FileMerge is part of the Xcode tools? (Wikipedia [says so](https://en.m.wikipedia.org/wiki/Apple_Developer_Tools#FileMerge)]).

Do you have Xcode installed?

**Comment by lyqeyes** [comment]
@hawkrives    oh, I think what u say is the point.  I didn't install Xcode.  Do it now.  Feedback soon.  thx  :-)

**Comment by lyqeyes** [comment]
@hawkrives  u r right. FileMerge belongs to Xcode, I installed Xcode minutes ago and then it worked. (tortoise-like-network-speed... lol)   thank u so much.

**Comment by hawkrives** [comment]
excellent! glad to hear it's working.
