### ISSUE TITLE
401 response from HTTP remote with osxkeychain credential

### ISSUE THREAD

**Issue by stephenvisser** [git-up/GitUp#222]
From `XLFacilityMinLogLevel=1 /Applications/GitUp.app/Contents/MacOS/GitUp`

> libgit2 error (-1): Unexpected HTTP status code: 401

- Git is using `credential.helper=osxkeychain`; everything works as expected on command line.
- origin is VSTS (`http://tfs-01p:8080/tfs/DefaultCollection/...`), and I'm on VPN to connect.

VSTS doesn't support SSH AFAIK. Workaround for now is to use `git fetch` from command-line

**Comment by swisspol** [comment]
Is there anything else in the log before this message?

Seems like this might be entirely in [libgit2](https://libgit2.github.com/), not GitUp.

**Comment by stephenvisser** [comment]
Some more content, (but doesn't seem related)

> 2016-09-21 12:37:34.839 GitUp[3867:257403] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9303, name = 'co.gitup.mac'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 00:00:00.172 [ERROR    ]> Failed creating message port for tool
> 00:00:00.181 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/.../.git"
> 00:00:00.215 [VERBOSE  ]> History loaded for "/Users/.../.git" (872 commits scanned in 0.036 seconds)
> 00:00:00.299 [VERBOSE  ]> Graph regenerated for "/Users/.../.git" in 0.012 seconds
> 00:00:00.713 [VERBOSE  ]> Commit database for "/Users/.../.git" updated in 0.002 seconds (0 added, 0 removed)
> 00:00:00.774 [ERROR    ]> libgit2 error (-1): Unexpected HTTP status code: 401
> 00:00:00.774 [VERBOSE  ]> Repository is up-to-date with its remotes
> 00:00:01.014 [VERBOSE  ]> App is up-to-date at version 1020 on channel 'stable'

**Comment by swisspol** [comment]
Looks like this issue is not at the GitUp level :/
