### ISSUE TITLE
Search box placeholder text misaligned on Sierra

### ISSUE THREAD

**Issue by tbodt** [git-up/GitUp#225]
<img width="244" alt="screen shot 2016-09-30 at 12 04 45 am" src="https://cloud.githubusercontent.com/assets/5678977/18983433/905387de-86a1-11e6-952a-cf12ea9e460f.png">

When you click on the text box and then click elsewhere, it goes back to normal.

**Comment by hawkrives** [comment]
See #213. 

No idea when it'll be merged, though.
