### ISSUE TITLE
GitUp uses 198% CPU even when idle 

### ISSUE THREAD

**Issue by ole108** [git-up/GitUp#229]
I run the latest GitUp version (1.0.6 build 1020) and it uses 10 times the energy of the next energy consuming application (Chromium with 5 windows and about 50 tabs).

The CPU usage seems to constantly at least at 198% (even while running unused in the background).
I wouldn't like to close and reopen GitUp all the time.
So please fix this.

**Comment by swisspol** [comment]
Can you sample the app?

Did you enable indexing of commit diffs (https://github.com/git-up/GitUp/wiki/Using-GitUp-Search)?

How many commits and branches / tags in your repo?

Does it happen with every repo or only a specific one?

**Comment by ole108** [comment]
> Can you sample the app and copy paste the result here?

I used the MacOS "Activity Monitor" to sample GitUp and pasted the result here:
[Sample of GitUp.txt](https://github.com/git-up/GitUp/files/523748/Sample.of.GitUp.txt)

> Did you enable indexing of commit diffs (https://github.com/git-up/GitUp/wiki/Using-GitUp-Search)?

No.

> How many commits and branches / tags in your repo?

We have around 10 branches (origin; 3 local) and currently 293 commits.

> Does it happen with every repo or only a specific one?

This seems to happen with every repo. I only found out since I am mainly using the described one.

**Comment by swisspol** [comment]
Looks like GitUp is checking with the server for changes in the repo in background. Try disabling this behavior in the preferences then relaunch GitUp and see if the problem still happens.

Are these repos hosted on GitHub or a private server? If not GitHub, can you try with a GitHub repo (make sure no other repo is open and CPU usage is zero before opening new repo)?

What is the remote using: SSH or HTTPS protocol? Does the problem go away if you use the other protocol?

**Comment by swisspol** [comment]
Any update on this?

**Comment by ole108** [comment]
I was never able to find out wether SSH or HTTPS is used.
But the problem went away when I disabled the background repo checks.
So we can close this now. Especially since I am not even using a Mac anymore!
