### ISSUE TITLE
Open items from "Open Recent" in tabs

### ISSUE THREAD

**Issue by salutis** [git-up/GitUp#230]
When using Open Recent to open a repository, it would be nice to open it in a new tab instead of a new window.

**Comment by salutis** [comment]
Just discovered: Command + Click opens it in a tab. It would be nice to be able to make this default though. Leaving this open.

**Comment by salutis** [comment]
@swisspol Actually, this is more of a bug. When I open a repository using Open Recent, it opens in a new window. However, when I close that window and open the same repository using Open Recent again, it opens in a tab. So, one needs to do it twice to get a tab.

**Comment by SenHeng** [comment]
This may be a separate issue, but some of my repos will open in a tab while others won't.

On a separate computer where I have multiple repos in one `project` folder, all those repos will open in a single window in separate tabs.  On that same computer, on *another* `project2` folder that has multiple repos, those repos will open in separate windows.

Is there some kind of settings that I have to trigger?

**Comment by swisspol** [comment]
Tabs are not "officially" supported in GitUp. It's OS X making it magically work under the hood. I guess it might not work in all cases?

**Comment by salutis** [comment]
@swisspol 

> I guess it might not work in all cases?

It is totally random. Drives me bananas! I would rather see no tabs than this..

**Comment by lapfelix** [comment]
In my experience, it always opens in a new tab when GitUp is fullscreen. Otherwise it's always in a new window.

**Comment by salutis** [comment]
@lapfelix 

> In my experience, it always opens in a new tab when GitUp is fullscreen. Otherwise it's always in a new window.

Just tried it (using Open Recent, no full screen) and it opened a new tab.

**Comment by swisspol** [comment]
There's likely some new APIs added for 10.12 that allow to fine-tune this behavior. Feel free to send in a PR 😄

**Comment by salutis** [comment]
@swisspol 

> Feel free to send in a PR 😄

I would totally do if the project used Swift. Forgot all Objective-C already...

**Comment by swisspol** [comment]
See Release Notes for App Kit in 10.12 for a starting point:
https://developer.apple.com/library/content/releasenotes/AppKit/RN-AppKit/#10_12Window Tabbing

(I'm still myself using El Capitan so I can't develop or test this feature)

**Comment by salutis** [comment]
I have no idea what happened but randomness is gone and tabs always work now.

macOS 10.12.2 (16C67)

**Comment by swisspol** [comment]
Did you update to very latest beta of GitUp? Maybe recompiling against 10.12 SDK did the trick?

**Comment by salutis** [comment]
@swisspol 

> Did you update to very latest beta of GitUp?

Oops, sorry for missing GitUp version number. Running 1.0.6 (1020) here.

**Comment by SenHeng** [comment]
Also on OS X 10.12.2 and GitUp 1.0.6, everything opens in windows now. Haven't got any to open in tabs in a while.

**Comment by salutis** [comment]
FYI: I disabled the Welcome window and use Open Recent exclusively. GitUp always opens the repository in a new tab.

**Comment by themyth92** [comment]
For me, I have to go to `View/Show Tab Bar` to make GitUp Open Recent show in tabs instead of new window.
