### ISSUE TITLE
Failed to start SSH session: Unable to exchange encryption keys

### ISSUE THREAD

**Issue by egracer** [git-up/GitUp#241]
Despite being able to successfully fetch and push via SSH from the Terminal, I am unable to do either from GitUp. I'm unable to identify the source of the error, however a quick google search of the error message yielded [this issue in the gitfs project](https://github.com/PressLabs/gitfs/issues/193). Maybe GitUp requires a libssh2 dependency update?

<img width="532" alt="screen shot 2016-11-23 at 4 24 32 pm" src="https://cloud.githubusercontent.com/assets/4086884/20579426/785f2e2a-b19a-11e6-8303-9f13e0885619.png">

**Comment by swisspol** [comment]
There's some info about SSH logic here: https://github.com/git-up/GitUp/wiki

**Comment by egracer** [comment]
Thanks. I added my private key using `ssh-add ~/.ssh/id_rsa`. Still no luck. And I confirmed that the private key there is correct.

**Comment by evergist** [comment]
+ 1

**Comment by phatmann** [comment]
I am running into this error now, too, both on current HEAD build and last released build. I am not sure what changed, since I have not installed an OS update recently. Other Git clients are working fine. There is nothing in my .ssh/config file. I cannot find a workaround so I am stuck.

**Comment by lapfelix** [comment]
Same thing just started happening to me too. The repo is hosted on Github. Might be on their side, but it's still weird that I can push using the command line...

**Comment by simonyangme** [comment]
I'm also running into this issue. Using git via command line still works but GitUp does not.

**Comment by egracer** [comment]
This has continued to happen for me -- I first noticed it pushing to git hosted on TFS, so it doesn't appear to be a GitHub specific thing. Best guess is it has something to do with how SSH is configured server-side, but I'm not familiar enough with objective-C and the mac sdks to determine if the client might be contributing as well.

**Comment by phatmann** [comment]
@swisspol Seems like the GitUp client is broken for many of us until this gets resolved. if you need help debugging or fixing it, let me know.

**Comment by simonyangme** [comment]
For whatever reason, the issue seems to have resolved itself and GitUp is able to work with GitHub again.

**Comment by phatmann** [comment]
Same here!

**Comment by gabehoffman** [comment]
This just started up for me today. Doesn't look like there is any resolution. Maybe later today it will work?

**Comment by mcschroeder** [comment]
Pretty sure this is due to GitHub dropping support for some outdated crypto standards: https://githubengineering.com/crypto-removal-notice/. The timeline fits exactly.

**Comment by gabehoffman** [comment]
Yeah, that's probably it. So we're just out of luck? That won't be fixing itself later today like it did before.

**Comment by g-Off** [comment]
Dug into this a bit and I now have a working version on my machine. Not sure how to submit a patch though. Issue as I understand it is that the version of libssh2 that is used is too old for GitHub and doesn't support any of the necessary key exchange algorithms. GitUp is using 1.6.0, latest release is 1.8.0 (released October 25th 2016).

I made a small change to the Libraries submodule, specifically in the [libssh2 rebuild.sh script](https://github.com/swisspol/Libraries/blob/master/libssh2/rebuild.sh) changing:

```
-VERSION="1.6.0"
+VERSION="1.8.0"
```
and
```
-  curl -O "http://www.libssh2.org/download/libssh2-$VERSION.tar.gz"
+  curl -O "https://www.libssh2.org/download/libssh2-$VERSION.tar.gz"
```

**Comment by lapfelix** [comment]
@g-Off It's in the Libraries submodule so to submit a patch you would probably need to send a pull request to https://github.com/swisspol/Libraries

And then another pull request here where you would update the reference to "Libraries" to the pull request merge commit

**Comment by g-Off** [comment]
@lapfelix I'm unsure how @swisspol manages or wants to manage his repo of precompiled libraries since it might be used in other projects or impact things in other ways and this is why I didn't submit a PR against there

**Comment by swisspol** [comment]
Thanks @g-Off . Closing this issue as a dup of #421

**Comment by csjones** [comment]
Started getting this error yesterday but was able to resolve the issue by changing `remote.origin.url` in the git config from `git@github.com:csjones/gg.git` to `https://github.com/csjones/gg`.

**Comment by logicminds** [comment]
Changing to http url doesn't fix this issue and only uses a non ssh based protocol which skirts around the issue.
