### ISSUE TITLE
Run GitUp with inverted colors / black theme?

### ISSUE THREAD

**Issue by pitaatip** [git-up/GitUp#243]
Hi,

I want to use GitUp on presentation about git, to have live preview of running git commands. 
I have one problem - displays on which I will be presenting are very bright and have poor contrast. 
The result is that you practically can't see anything on Map view.

Is there some way to invert colors or turn on some black/presenter theme? I know I can do this on Mac, but it looks awkward that way.

Due to this problem: https://github.com/git-up/GitUp/issues/234 I have to compile gitup on my own, so if you had some developer/temporal solution in mind, please share it with me.

Thanks!

**Comment by swisspol** [comment]
Hi,

See #198 otherwise you would need to change the code in GIGraphView class.

**Comment by pitaatip** [comment]
One more question in the same topic:
is there a way to enlarge Map view (simply zoom in)?

**Comment by pitaatip** [comment]
And thanks  for linking #198 , it worked perfectly

**Comment by swisspol** [comment]
No, there's no zoom feature in the app at this time.
