### ISSUE TITLE
Fetch/Push fails when git remote config uses ~/.ssh/config Hosts

### ISSUE THREAD

**Issue by torarvid** [git-up/GitUp#244]
Hi there. In my `~/.ssh/config` I have for instance:

    Host github
        Hostname github.com
        User git

And in the console I'm used to doing `git clone github:someuser/somerepo`. Regular git will handle this clone just fine, and look up the actual hostname github.com from my ssh config. It also works for subsequent fetch/push commands, and my `.git/config` has:

    [remote "origin"]
        url = github:someuser/somerepo

.. in it. However, when attempting to fetch/push from GitUp, I get `Failed connecting to "origin" remote: Failed to resolve address for github: nodename nor servname provided, or not known`.

I don't know GitUp well enough to know if I'm doing something wrong, if this is an issue with libgit-and-not-gitup, or something else - so apologies if this issue is misplaced. Anyways, I'm curious if it can be solved.

Thanks for an otherwise excellent app!

**Comment by swisspol** [comment]
Hi,

See https://github.com/git-up/GitUp/wiki for more info about ssh.

**Comment by elsonwu** [comment]
I got into the same issue and unfortunately, I found this in git-up wiki:

> SSH config files (typically located at ~/.ssh/config) are ignored by GitUp since it uses libssh2 and not the ssh tool for SSH remote operations.

@swisspol  but the question is, how can I fix this issue? I meant how to make it work?

**Comment by torarvid** [comment]
@elsonwu replace `github:someuser/somerepo` with `git@github.com/someuser/somerepo` in your .git/config file

**Comment by elsonwu** [comment]
@torarvid the problem is that I need ~/.ssh/config because I am now using enterprise Github with ssh key, but GitUp ignores this file, then it won't able to access my repo.

**Comment by torarvid** [comment]
@elsonwu Ok; `git@github.myenterprise.com:someuser/somerepo` works fine for me at least. So somehow it ends up finding/using the right pub key (which for me is the default `~/.ssh/id_rsa.pub` key) when trying to access GHE.

(extra note: There was a typo in my previous post, where I said `git@github.com/some...` instead of `git@github.com:some...` <-- note that it should be `:` and not `/` between host and owner)
