### ISSUE TITLE
Enable file Drag&Drop from Working Directory/Index on Mac

### ISSUE THREAD

**Issue by tobias-r** [git-up/GitUp#249]
A great feature would be, if Drag&Drag would work for files listed in the Working Directory/Index listing.

There, all the files are listed, that changed. This would e.g. make an upload into a FTP program easier and faster.

**Comment by swisspol** [comment]
You can already drag & drop files between the working director and index lists. If you mean drag & drop from the Finder into the working directory or index list, this is not a feature that would make sense for GitUp. Drag and drop into the Git repository directory in the Finder instead.

**Comment by tobias-r** [comment]
I am leaving this closed, however:

It would make a lot of sense.

I am always uploading my changed files onto a server (in case I dont want to do a full deploy).

With this feature, I could use GitUp as base. Without this feature, I need to navigate into every single folder manually. This takes a lot of time.

For me this is crucial!
