### ISSUE TITLE
"Submodule not in index" after adding and removing a submodule

### ISSUE THREAD

**Issue by sergej-koscejev** [git-up/GitUp#250]
I have added a project as a submodule of my main project but in a later commit I decided to just copy it over instead of using submodules. However now GitUp refuses to do anything with the repository (such as move a totally unrelated commit up/down), telling me "Submodule not in index".

**Comment by swisspol** [comment]
Sounds like a [libgit2](https://libgit2.github.com/) bug. What happens if you quit GitUp and relaunch it?

**Comment by sergej-koscejev** [comment]
Well, what I described is what happens - I don't get any error on startup, I can browse commits, I just can't change anything via GitUp. Restarts don't affect this in any way. I didn't add/remove the submodule via GitUp, I did it via the command line.

**Comment by swisspol** [comment]
It sounds like there is some inconstances in your repo with regarding to the submodules settings. Git can handle that but libgit2 is more sensitive.

**Comment by swisspol** [comment]
You would need to compleletely remove any trace of the former submodule from your repo. From the .gitmodule file, the .git/module directory, the .git/config file... and delete the .git/index file. Make sure GitUp is not running while you do that.

**Comment by sergej-koscejev** [comment]
This helped, thanks!
