### ISSUE TITLE
100% CPU when in background

### ISSUE THREAD

**Issue by danielchasehooper** [git-up/GitUp#252]
I've noticed an occasional issue in which gitup Cpu usage will go to 100%, even though I'll be using another application. This just happened to me after waking my computer from sleep and using Safari, I didn't interact with gitup at all. 

I was able to take a CPU sampling and it appears that it's checking for remote changes (checkForChangesInRemote:withOptions:addedReferences:modifiedReferences:deletedReferences:error:) and then all of it's time get spent in http_stream_read. 

The instruments sampling:
[gitup cpu pinned.trace.zip](https://github.com/git-up/GitUp/files/658918/gitup.cpu.pinned.trace.zip)

**Comment by swisspol** [comment]
Sounds like a dup of #229.

**Comment by danielchasehooper** [comment]
@swisspol the issue you duped this to is closed, but this behavior is still occurring. Seems like either this issue or #229 should be reopened until the problem is addressed.

**Comment by swisspol** [comment]
The workaround is to disable background remote checks, seems like an issue in libgit2.

**Comment by danielchasehooper** [comment]
Should I file a bug against libgit2 or is this a "wont fix"?

**Comment by swisspol** [comment]
I really wish it could be fixed but I can't look into this right now, and libgit2 is unlikely to look at it unless they have a fully self contained test case, so it's a "won't fix" at least for now.

**Comment by danielchasehooper** [comment]
How do you disable background remote checks? I just turned "Remotes: automatically check" to "never" and this issue still happened.

**Comment by swisspol** [comment]
Did you try restarting the app afterwards? If it still happens, then it's a different bug.
