### ISSUE TITLE
"Object not found" error while pushing

### ISSUE THREAD

**Issue by nikolaykasyanov** [git-up/GitUp#255]
The exact message is:
>Object not found - no match for id (&lt;some stale commit sha1&gt;)

I suspect it is caused somehow by heavy use of rebase in our team. Git CLI doesn't have such issue, though.

Local repo is not shallow.

**Comment by swisspol** [comment]
Does it still happen if you relaunch GitUp? Does it still happen if you start from a clean checkout of your repo?

**Comment by nikolaykasyanov** [comment]
@swisspol relaunch doesn't help. I'll try clean checkout.

**Comment by nikolaykasyanov** [comment]
Doesn't seem to happen with 1.0.7. Apparently libgit update helped.
