### ISSUE TITLE
GitUp CLI command options

### ISSUE THREAD

**Issue by dudeofawesome** [git-up/GitUp#256]
The GitUp CLI mentions that there are options you can pass it, but I can't find a reference to the options anywhere else. Are these implemented yet, and if so, what are some of them?

I'm specifically looking for a way to launch GitUp with a specific set of view options applied. (Remote branch tips enabled, show tag labels, show branch labels)

```
$ gitup help
Usage: gitup [command [options]]
…
```

**Comment by swisspol** [comment]
There are no options defined at this time. It's just a placeholder.
