### ISSUE TITLE
Map sometimes has drawing artifacts where commit tooltip used to be

### ISSUE THREAD

**Issue by salutis** [git-up/GitUp#259]
This happens quite often:

<img width="88" alt="screen shot 2017-01-04 at 11 29 05" src="https://cloud.githubusercontent.com/assets/1158274/21639633/5788da96-d271-11e6-9532-7c3fd7d20a7b.png">

The lines match the border of "commit popover":

<img width="284" alt="screen shot 2017-01-04 at 11 32 52" src="https://cloud.githubusercontent.com/assets/1158274/21639686/96019c4a-d271-11e6-8630-c8deeb6f5d9e.png">

Configuration:
 
* MacBook Pro (Retina, 15-inch, Early 2013)
* macOS 10.12.2 (16C67)

**Comment by lucasderraugh** [comment]
I believe this should be resolved with #654
