### ISSUE TITLE
Simple commit view is slow

### ISSUE THREAD

**Issue by aristidesfl** [git-up/GitUp#260]
When using the simple mode, the commit view takes quite a while to load. 
Is there is some optimisation which can be done here?

**Comment by swisspol** [comment]
It's already very optimized but there are cases where computing / rendering the diff is just going to be slow and there's nothing that you could do, short of not displaying it at all.

See #45 and #83 for instance.

**Comment by aristidesfl** [comment]
Here the emphasis is the difference between advanced and simple view. Advanced view is quite fast.

**Comment by swisspol** [comment]
The diff is computed differently for Simple View it's "workdir to head" vs just "workdir to index" or "index to head".
