### ISSUE TITLE
Command ⌘ + Return ↵ to commit the message

### ISSUE THREAD

**Issue by aristidesfl** [git-up/GitUp#262]
While writing the commit message, is there any shortcut to submit?
I've seen other apps using ⌘↵ for this purpose.

**Comment by lapfelix** [comment]
`alt + return` does it for me

**Comment by aristidesfl** [comment]
Thanks @lapfelix. 
When ↵ submits the message, I've seen some apps use ⌥↵ to enter a newline.
Any reason to use ⌥ instead of ⌘?

**Comment by swisspol** [comment]
See docs at https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View for keyboard shortcuts.

⌥ is used because ⌘ would not work everywhere (in some type of dialogs IIRC) leading in inconsistencies in the UI.
