### ISSUE TITLE
Warn when config user.email is missing

### ISSUE THREAD

**Issue by mull** [git-up/GitUp#266]
I noticed this after a fresh OSX install. If git config user.email is missing it seems like

1. Enter to stage file does not work (I get a error beep sound)
2. Committing does not work and hints that the config entry is missing

Let me know if I can/need to provide you with more information!

**Comment by swisspol** [comment]
This is expected behavior: you need `user.email` and `user.name` to commit.

**Comment by mull** [comment]
While I agree that it needs to happen, I would say the app could warn a bit earlier. While trying to press return to stage files for commit I only got an error beep. Only when I tried to actually commit did it hint at this problem.
