### ISSUE TITLE
Feature Request: diff/compare branches

### ISSUE THREAD

**Issue by aviflax** [git-up/GitUp#267]
Would be fantastic!

Thank you!

**Comment by aviflax** [comment]
@swisspol Thanks! I reviewed the page and doing so helped me realize that I had become lazy in my thinking — I allowed myself to forget that in Git, branches are barely even a thing. They’re just labels that point to commits — so comparing branches _really_ just means comparing the HEAD commits of those branches. This was a helpful reminder.

So, correct me if I’m wrong, but I just tried the _Diff with HEAD…_ feature on a few different commits (including some that are the HEAD of some branches) and it seems that GitUp is in fact currently fully capable of quickly and easily displaying high-quality diffs of branches, via that feature.

So, unless I’m missing something, I think maybe the only potential change worth considering might be to “surface” this capability in the GUI in such a way as to make it a bit more likely for folks using an inaccurate but common mental model of Git to _find_ the capability. To have it “register” with them.

If you agree, and you think such an enhancement would be worth considering, I’d be happy to try to rephrase the title of this issue to reflect that understanding. And/or if you’d like I could try to add some new content to the wiki to help guide other users. I could also try making a few suggestions on how specifically to approach the enhancement, but I’ll hold off until I hear whether you’re interested ;)

Thanks again for GitUp! I use it every day and it’s fantastic!

**Comment by salutis** [comment]
BTW, the help entry for Diff View says:

> The Diff view shows you the diff between the current HEAD of the repository and any other commit. Press [i] or [Spacebar] to exit.

Spacebar does nothing. Only `i` works.

**Comment by swisspol** [comment]
I'm glad you figured it out and like it! I don't plan on changing the UI at this point. GitUp is not intended as a way to learn Git with tips and guidance and stuff.

Feel free to send PRs to the wiki although I'm not sure how this actually works.

**Comment by aviflax** [comment]
I don’t think the GitHub wiki supports PRs; you can open up changes to the public if you want, or I could submit a patch via a regular issue.

**Comment by swisspol** [comment]
I'm not sure I want to open the wiki to public editing. So please make a new issue with change to make.
