### ISSUE TITLE
`post-checkout ` hook not executed?

### ISSUE THREAD

**Issue by PixelPirate** [git-up/GitUp#270]
I have a `post-checkout` hook which should run whenever I change between branches. It is invoked by SourceTree and the command line, but not by GitUp.

**Comment by hawkrives** [comment]
According to the wiki,

> - Only a subset of Git hooks are supported: `pre-commit`, `commit-msg`, `post-commit`, and `pre-push`.

So, it's currently expected behavior to not run `post-checkout` hooks, but I don't know if there's a reason that _only_ those four are run.

**Comment by swisspol** [comment]
`post-checkout` is much harder to integrate with libgit2. Unfortunately there are no plans to support it.
