### ISSUE TITLE
Set tip / Move tip

### ISSUE THREAD

**Issue by wmertens** [git-up/GitUp#271]
One feature I thought I was missing in GitUp was the ability to move the tip of the branch so I could re-do a bunch of commits. Then I reasoned that that is so useful, it should be in there, and I started trying modifiers and only then I discovered the <kbd>^</kbd>+<kbd>T</kbd> Move Tip command.

I am wondering if this command should not always be visible in the menus, given that it is currently hard to discover while being very useful. So, just to show both `Set Tip` and `Move Tip` where they can apply?

**Comment by salutis** [comment]
@wmertens 

_I am wondering if this command should not always be visible in the menus, given that it is currently hard to discover while being very useful._

It's in the context menu:

<img width="495" alt="screen shot 2017-01-30 at 11 48 26" src="https://cloud.githubusercontent.com/assets/1158274/22420300/20601982-e6e2-11e6-81d0-62705ef69bd7.png">

**Comment by wmertens** [comment]
No, that is the Set Tip Option+T command, not the Move Tip Control+T
command. Set Tip changes the working directory to the state at the new tip,
and Move Tip simply moves the tip and leaves the working directory as-is
from the previous tip state, allowing you to re-commit all your changes.

**Comment by swisspol** [comment]
It says in https://github.com/git-up/GitUp/wiki/Using-GitUp-Map-View you have to press option or control to see more commands in menu. Probably good enough for this very advanced operation.
