### ISSUE TITLE
Are there plans to upload application to AppStore?

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#276]
My issue:

If I don't use GitUp app too long, it starts beachballing at next focus on app.
It could be connected ( not sure ) with signing issues. ( mac security system try check it )

Maybe this issue could disappear if application reallocated to AppStore?

MacBookPro, Late 2011, HDD 512, 16GB RAM

**Comment by salutis** [comment]
I'd like to see GitUp in the App Store too. Easier to upgrade, etc. Maybe it could even include IAP to support ongoing development?

**Comment by swisspol** [comment]
I have no plans to put GitUp on the App Store. There's no real benefit.

> If I don't use GitUp app too long, it starts beachballing at next focus on app.

That sounds like a dup of the unfortunate #229.
