### ISSUE TITLE
Failed to parse signature

### ISSUE THREAD

**Issue by keatonswob** [git-up/GitUp#278]
When trying to squash two commits I get an error message "Failed to parse signature, Signature cannot have an empty name or email". Has anyone run across this and know of a fix?

**Comment by invariant** [comment]
I'm currently having this problem. Did you resolve it?

**Comment by invariant** [comment]
Resolved it myself by setting name and email in .gitconfig

**Comment by dqj1998** [comment]
Or run commands:
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
