### ISSUE TITLE
Question: how to exit git config?

### ISSUE THREAD

**Issue by SenHeng** [git-up/GitUp#284]
Try as I might, I couldn't find a way to return to the usual view other than closing and re-opening.

**Comment by swisspol** [comment]
[Esc] key I think or use close button in upper right of window.

**Comment by swisspol** [comment]
https://github.com/git-up/GitUp/wiki/Using-GitUp-Configuration-Editor

**Comment by vermapushpendra** [comment]
1. Press Esc key
2. Write :wq
3. done

**Comment by ricky-kiva** [comment]
I'm using Git Bash, on a loop by `git config --list`. What I do to exit the loop:

1. Press `q`

Done!
