### ISSUE TITLE
project does not build on a case sensitive filesystem

### ISSUE THREAD

**Issue by mdaniel** [git-up/GitUp#289]
Either `$(PLATFORM_NAME)` changed case with some recent version of Xcode, or the build has only worked coincidentally before.

One will observe the folder is [Libraries/libssh2/MacOSX](https://github.com/git-up/Libraries/tree/04686418418ca90581233690f8edc320c5975aa1/libssh2/MacOSX) but the `$(PLATFORM_NAME)` is `macosx`. The practical implication of this is it causes `libgit2.xcodeproj` and `GitUp.xcodeproj` both to not find `libssh2.h`, since they use `$(PLATFORM_NAME)` in the header search path.

The work-around I used was to symlink `MacOSX` to `macosx` and then the build found `libssh2.h` again, but I believe the _correct_ fix is to make all those platform directories fully lowercase, since `xcodebuild -showBuildSettings | grep PLAT` shows `AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator` and thus those with case-insensitive filesystems won't notice anything, and those with case-sensitive ones will enjoy builds succeeding.

**Comment by swisspol** [comment]
Case-sensitive file systems are the exception by very far on the Mac platform, it's not a compatibility it would make sense to maintain, sorry.

**Comment by vovkasm** [comment]
@swisspol Just hit this issue. Have to say two things.
1. With new Apple File System it is now much easy to create volumes and setup case sensitive file systems. So now it's not exceptional to have case sensitive fs for development.
2. It's not about maintain some sort of compatibility, it's about to have source code in consistent state. It's about well structured project and general accuracy.

So my question about this is the position of developers "it's not a compatibility it would make sense to maintain" or more like "can't maintain it, but PRs welcomed"?
