### ISSUE TITLE
Recently Opened list always says "No Repositories"

### ISSUE THREAD

**Issue by danngreen** [git-up/GitUp#293]
The dropdown menu on the Welcome screen always shows No Repositories. The "Open Recent" menu item in the File menu always shows a disabled item reading "Clear Menu", but no other sub-menu items. 
This is in Mac OS 10.12.3 (16D32)
GitUp 1.0.7 (1021)

If I open a repository with the File Menu, it shows up fine. But if I close it, it does not appear in the "Open Recent" or "Recently Opened..." menus. Whether I close the repo by quitting or by selecting "Close", it doesn't matter, the menu is always empty.

Where can I look to see where this list of recent repos should be stored?

<img width="284" alt="screen shot 2017-03-17 at 3 31 34 pm" src="https://cloud.githubusercontent.com/assets/25355384/24065239/d2c58202-0b26-11e7-8280-4b400620371b.png">

**Comment by swisspol** [comment]
This list is managed by OS X / Cocoa, not the app. Not sure why it would be empty?

**Comment by danngreen** [comment]
Ah, that explains why I couldn't find it in the source code! I'll check into OSX... 

I really love being able to visualize our repo, great program!

**Comment by deyton** [comment]
The list in your screenshot is populated using `-[NSDocumentController recentDocumentURLs]` [in the app delegate](https://github.com/git-up/GitUp/blob/master/GitUp/Application/AppDelegate.m#L243), if you want to set a breakpoint or poke around some more.
