### ISSUE TITLE
Can't find discard line changes

### ISSUE THREAD

**Issue by SimonLi5601** [git-up/GitUp#297]
In older version, user can discard selected lines before stage. But I can't find it now anymore. It changes to discard file changes which will discard everything in one file. Not sure if this feature moves to somewhere else.

**Comment by swisspol** [comment]
This hasn't changed. Just hit the backspace key.

More info at https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View.

**Comment by SimonLi5601** [comment]
Thanks for the reply. The delete button doesn't work for me. It seems to be readonly if I open the file in this view. Did I miss anything? I am using Mac 10.11.6.

**Comment by deyton** [comment]
Are you sure you're selecting the lines and not just the text? I sometimes make that mistake and get confused about why things aren't working.

### Here:
![screen shot 2017-04-05 at 9 08 10 pm](https://cloud.githubusercontent.com/assets/495258/24737595/b9571704-1a44-11e7-8058-fb5447f8c920.png)

### Not Here:
![screen shot 2017-04-05 at 9 08 18 pm](https://cloud.githubusercontent.com/assets/495258/24737603/c90a87bc-1a44-11e7-98f9-584b997b6b64.png)

**Comment by SimonLi5601** [comment]
Thanks Deyton! I did make the mistake exactly you mentioned. I am not very familiar with this tool and I just tried it last year or two. When I came back again, I forgot this tip. Or I didn't even realize the difference at that time. I still didn't get what's the point to distinguish those two different selecting mode.

**Comment by swisspol** [comment]
You select text to copy-paste only some text, you select entire lines to act on lines.
