### ISSUE TITLE
Can't navigate to merged branches easily via keyboard. 

### ISSUE THREAD

**Issue by macrael** [git-up/GitUp#298]
If I have a branch that has been merged into, it's difficult to navigate down both the main and the merged branch easily with the keyboard. Perhaps allowing a combination press of down and right to navigate diagonally from the main to the merged branch would help. 

Example: 

a
|
b
| \\
| c
| |
| d
| /
e

Starting with the cursor at a, there is no way to get to c using only the keyboard. But if when b was selected I could differentiate between going for e and going for c by using [down] or [down+right] respectively, then I could navigate with the keyboard completely.

**Comment by lucasderraugh** [comment]
We have recently added a basic implementation using up and down with the option ⌥ key to split to the alternative branch. This works well in simple one branch cases, might evolve it if anyone has better ideas to improve it. Closing with the merge of #581.
