### ISSUE TITLE
Fix hover functionality

### ISSUE THREAD

**Issue by valcalde** [git-up/GitUp#300]
Hover state is active, also when the mouse moves out of the hover area. 
Please fix this and show the hover effect, only when the mouse is over the specific area. See screenshot:

<img width="1400" alt="screen shot 2017-04-05 at 14 18 41" src="https://cloud.githubusercontent.com/assets/25527816/24705131/d140d9ac-1a0a-11e7-81eb-fec32ba78ff2.png">

**Comment by swisspol** [comment]
That's not a "hover" card, that's a "selection" card that is on screen when a node is selected.
