### ISSUE TITLE
Bad performance on https://github.com/jetbrains/intellij-community/

### ISSUE THREAD

**Issue by ignatov** [git-up/GitUp#303]
Hi, thank you very much for your program, it's great!
But when I'm trying to use it for https://github.com/jetbrains/intellij-community/ the performance leaves mush to be desired on my Macbook Pro 2013.
Could you help with it?

**Comment by swisspol** [comment]
This repo is 200K commits and almost 49K references (branches and tags): this is above with GitUp is designed to handle: see https://github.com/git-up/GitUp/wiki.
