### ISSUE TITLE
Connection timeout when using repository on different SSH port

### ISSUE THREAD

**Issue by DanielHeckrath** [git-up/GitUp#306]
We're running a GitLab installation non-standard SSH port. When I try to interact with the repository in GitUp all operations end with an error dialog stating

> Failed to connect to "origin" remote: Failed to connect to `<host>`: Operation timed out

The remote origin url has the pattern `[git@<host>:16122]:<group>/<repository>.git`

**Comment by swisspol** [comment]
Maybe the port is not parsed properly and there's an alternate syntax you can try?

It's all in https://libgit2.github.com/ unfortunately.

**Comment by DanielHeckrath** [comment]
I was able to solve this in the end by using a url in the form of `ssh://git@<host>:<port>/<group>/<repository>.git` instead of the format I get when I copy the repository url from GitLab
