### ISSUE TITLE
Native notifications

### ISSUE THREAD

**Issue by wardoost** [git-up/GitUp#311]
On the commit screen you sometimes can't click on the first file under working directory because of the notifications bar. Maybe using native notifications could work better?

**Comment by salutis** [comment]
This drives me crazy!

**Comment by sesam** [comment]
Likely a #good-first-issue to either make notifications go somewhere they don't hinder the user, like in a status bar that slides in from below, or just switch over to native notifications with some default very low urgency to ensure they don't overflow into other connected devices that may share notifications with the OSX desktop.

**Comment by lucasderraugh** [comment]
Let’s collapse this into #281 and focus on a single form of where the notifications can go. I think moving them to the bottom would be a happy medium.
