### ISSUE TITLE
Add support for the new includeIf directive

### ISSUE THREAD

**Issue by lilyball** [git-up/GitUp#315]
Git 2.13 added a new feature where your config can have an `includeIf.<condition>.path` directive that acts like `include.path` as long as the condition holds. It looks like GitUp doesn't understand this.

**Comment by swisspol** [comment]
GitUp relies on https://libgit2.github.com/, is it supported there?

**Comment by kballard** [comment]
Probably not. A quick skim doesn't suggest anything like this has been added since Git 2.13 came out. I'll file a ticket on them.

**Comment by kballard** [comment]
Filed as libgit2/libgit2#4246.

**Comment by swisspol** [comment]
Thanks!

**Comment by kballard** [comment]
libgit2 just implemented this. I'd love to see a GitUp update that includes this change.

**Comment by svdo** [comment]
I'm considering fixing this. Would somebody be able to point me in the right direction? I have never seen this code base before, and neither that of libgit2, so few pointers / suggestions would be very welcome.

**Comment by svdo** [comment]
Oops, the git-up/libgit2 fork: "This branch is 73 commits ahead, 2334 commits behind libgit2:master". I don't think I'm going to be able to fix that. I quickly tried to rebase / merge but that gives too many conflicts for me to solve.

**Comment by ches** [comment]
I would be happy to see this too. A practical use case:

My default `user.email` is my personal email address for open source contribution, but I use

```
[includeIf "gitdir:~/src/mycompany/"]
    path = ~/src/mycompany/.gitconfig
```

to override it with work address on work projects below that path. Currently if I make commits with GitUp on work projects, they will use with my personal address.

**Comment by khoan** [comment]
> Oops, the git-up/libgit2 fork: "This branch is 73 commits ahead, 2334 commits behind libgit2:master". I don't think I'm going to be able to fix that. I quickly tried to rebase / merge but that gives too many conflicts for me to solve.

Are we able to straight up use https://github.com/libgit2/libgit2, if it already supports the customizations made by [the git-up/libgit2 fork](https://github.com/git-up/libgit2)? Thanks.

**Comment by lucasderraugh** [comment]
@khoan Once #772 is in then we should be set to implement things like this. Unfortunately we haven't resolved all the issues yet.

**Comment by lucasderraugh** [comment]
I believe the includeIf directive now should be understood in 1.3.3 (because of the libgit2 bump) which is now on the continuous channel.

I'm going to close out this issue, but if this isn't resolved, please feel free to reopen.

**Comment by svdo** [comment]
That's great news @lucasderraugh, thanks!! Does that (libgit2 bump) mean that gitup now also performs code signing, or is that unrelated?

**Comment by lucasderraugh** [comment]
@svdo I think code signing is different, and is sort of being worked on here #691. I don't think libgit2 has any plans to implement it on their end.

**Comment by svdo** [comment]
I understand, thanks for clarifying!
