### ISSUE TITLE
Pressing Alt + Enter in "New branch" modal inserts new line in branch name

### ISSUE THREAD

**Issue by mcdado** [git-up/GitUp#321]
In the modal for creating new branches, out of habit with the rest of the UI, I hit <kbd>⌥</kbd> + <kbd>↵</kbd> to submit the name for the new branch, but this creates a new line, if then I hit <kbd>↵</kbd> again or click `Create`, an error pops up.

![jun-08-2017 13-18-41](https://user-images.githubusercontent.com/898057/26926219-19f812fe-4c4d-11e7-8529-5ad24fa4a4ad.gif)

**Comment by salutis** [comment]
Fixed in #288.
