### ISSUE TITLE
"Failed writing snapshots" message when opening repo on macOS 10.13 with APFS

### ISSUE THREAD

**Issue by mark-anders** [git-up/GitUp#322]
I'm seeing this since upgrading to 10.13.  It happens on every repo I open.

**Comment by salutis** [comment]
Duplicate of #144.

**Comment by aleksandergrzyb** [comment]
I'm having this issue too.

**Comment by wmertens** [comment]
Confirm fixed in 1.0.9

**Comment by salutis** [comment]
@swisspol This one can be closed.
