### ISSUE TITLE
Modernize Clang-Format rules

### ISSUE THREAD

**Issue by zwaldowski** [git-up/GitUp#326]
Homebrew has moved forward to Clang-Format 5.0.0 — they only serve up 3.8.0 as a version variant. The only major incompatibility I can see is ObjC being an actual language, so we might need to simply duplicate the rules? I don't quite understand the rules layering.

**Comment by swisspol** [comment]
Yes, should be trivial.

**Comment by swisspol** [comment]
This has been resolved some time ago.
