### ISSUE TITLE
How is one supposed to work with submodules?

### ISSUE THREAD

**Issue by cicuz** [git-up/GitUp#330]
How can I create a new submodule? How can I import and/or update existing ones? Must I use the commandline for that?
For example, I tried cloning a repository with submodules, to test things, and I purposely deselected the "initialize submodules" checkbox, but now I don't know how to perform that action; furthermore, I want to add a submodule to my existing repository, but I can't figure out the expected way of doing that.

Thank you very much for any input, and for all the past work.

**Comment by swisspol** [comment]
You can't "manage" submodules from GitUp. GitUp is just aware of them and handles them properly when they exist. You would need to use the command line or another GUI tool to add / remove them.
