### ISSUE TITLE
Improve logic of diff context extra lines

### ISSUE THREAD

**Issue by mcdado** [git-up/GitUp#332]
<img width="516" alt="screen shot 2017-06-20 at 14 44 46" src="https://user-images.githubusercontent.com/898057/27333769-4db9ca14-55c7-11e7-8dd5-835d6ebb251a.png">

You can see in the screenshot that line 263 in the original file has been trimmed, because it's outside the two contexts for the previous and next hunk. Since the distance between hunks + context (three lines, correct?) is one line, it would be better to collapse the hunks in one. What do you think?

**Comment by swisspol** [comment]
Seems like an edge case. This is not something that can easily be fixed: the diff engine is the one from libgit2, which itself comes from Git.
