### ISSUE TITLE
GPL licensed code

### ISSUE THREAD

**Issue by davlhd** [git-up/GitUp#334]
The license of GitUpKit makes it impossible to use it in any macOS or iOS project, that is not open source. Is that going to stay that way? 

We are thinking to support some git features in our macOS app and are looking for an easy solution. GitUpKit seems exactly right for that. It would be a shame if we could not use it.

**Comment by swisspol** [comment]
Yes, that's intentional. If you want to use the code in a closed source app and you're willing to pay for a license, we can certainly discuss this - email me `pol@mac.com`. Note that the code would be provided as-is.
