### ISSUE TITLE
Error when pushing: Authentication required but no callback set.

### ISSUE THREAD

**Issue by whmountains** [git-up/GitUp#337]
I get this error when trying to push or pull from my repository.  It's not a new error, but it only seems to happen on repositories that use SSH authentication:

![screen shot 2017-06-29 at 13 37 24](https://user-images.githubusercontent.com/8680147/27701863-3eee3ab4-5cd0-11e7-80a7-c055558746be.jpg)

I do have a valid key in `~/.ssh/`.  Pushing from terminal `git push` works just fine.  I'm using Mac OS 10.12.6.

Anything I can do to help you debug this please let me know.  It's  annoying but until it gets fixed I can just push from terminal.

**Comment by swisspol** [comment]
Check out the info about SSH in https://github.com/git-up/GitUp/wiki and also other related issues where people solved this problem.

**Comment by whmountains** [comment]
I read the Wiki but says that GitLab will try all the keys in `~/.ssh/`, which apparently is not the case.

The solution is in #35.  You have to run `ssh-add -K path/to/key` before GitLab will start using it.
