### ISSUE TITLE
GitUp hangs when a repository has too many branches

### ISSUE THREAD

**Issue by luolong** [git-up/GitUp#344]
I happen to work on a project that has massive amount of open remote branches (1723 branches to be precise). When switching to veiws like reflog or enabling to show all remote branches, the GitUp basically hangs there. For a _Veery Looong Time..._, supposedly trying to find a way to visualise the whole tree.

While this is going on, I can do nothing to GitUp except wait or force-kill it's process. I can't even cancel the requested operation...

**Comment by swisspol** [comment]
Yes, with 1700+ branches all visible at the same time (did you try hiding old branches in the graph view settings)? You will be past the limit of what GitUp was designed to handle.

Also try `git fetch --prune`.

**Comment by luolong** [comment]
No, I can't do that. Can't go around deleting branches. `git fetch --prune` would not help either, as all those branches are coming from remote origin. 

Bad shit, I know and someone should probably take a deep look at all those branches and delete ones that are long overdue for deletion, but we need to get there somehow. Meanwhile, GitUp is kind of useless for browsing remote branches.
