### ISSUE TITLE
Linux version please

### ISSUE THREAD

**Issue by COLABORATI** [git-up/GitUp#348]
Please release this software for Linux. Thank you.

**Comment by hawkrives** [comment]
Duplicate of https://github.com/git-up/GitUp/issues/160

**Comment by wmertens** [comment]
@COLABORATI it is very difficult to port this project to Linux. You will have to create a new UI in some framework, and bridge to GitUpKit (which is written in ObjectiveC). I am certain @swisspol won't be doing that, but you are welcome to start a project that does this…

**Comment by swisspol** [comment]
Duo of #160
