### ISSUE TITLE
Removed remote still present in graph

### ISSUE THREAD

**Issue by mdtusz** [git-up/GitUp#359]
I've removed a remote from my repo, but the dashed line for that remote still is displayed. 

I'm unsure if this is a bug, or if I just need to do something to updated GitUp's state for the repo.

<img width="289" alt="screen shot 2017-09-27 at 10 54 12 am" src="https://user-images.githubusercontent.com/6494463/30920562-499ca962-a372-11e7-9769-a8249231c3e4.png">

and from the command line:

```
myrepo|master⚡ ⇒ git remote -v
origin	git@github.com:mdtusz/myrepo.git (fetch)
origin	git@github.com:mdtusz/myrepo.git (push)
```

**Comment by swisspol** [comment]
It means this Git ref might still be in your repo. What happens if you relaunch GitUp?

**Comment by mdtusz** [comment]
It still appears. Is there an ApplicationSupport cache or something I can manually remove? It's not a huge issue but just bothers my need for a clean slate. Once I've cleaned up my stashes I'll re-clone the repo and see if it's still present.

**Comment by swisspol** [comment]
Can you run `git branch -a`?

**Comment by mdtusz** [comment]
Hmm yep still showing the remote `resin/master` branch. Strange it doesn't show up when listing the remotes, but I suppose that must be expected git behaviour on a level I don't fully grok. 

Output of `git branch -a`:

```
  master
  production
  feature-temperature-panel
* stage
  remotes/development/master
  remotes/origin/master
  remotes/origin/production
  remotes/origin/feature-temperature-panel
  remotes/origin/stage
  remotes/resin/master
```

The fix: `git branch -rd resin/master`
