### ISSUE TITLE
"Object not found" when using a shallow cloned repository

### ISSUE THREAD

**Issue by AlicanC** [git-up/GitUp#364]
```bash
git clone --depth=1 git@github.com:git-up/GitUp.git
cd GitUp
gitup # Object not found - no match for id (........)
git fetch origin --unshallow
gitup # All dandy
```

**Comment by swisspol** [comment]
Shallow clones are not supported by GitUp:
https://github.com/git-up/GitUp/wiki

**Comment by swisspol** [comment]
I’m not aware of any off the top of my head.

**Comment by AlicanC** [comment]
```bash
cd complete_repo
git fetch origin --unshallow --dry-run
# fatal: --unshallow on a complete repository does not make sense
```

Looks like Git has a way of doing it.

**Comment by sesam** [comment]
@swisspol How about making the error message link to a wiki-page here on github? Then users and others can help each other with worarounds.

Doing this in general for all error messages could relieve you of a lot of work.
