### ISSUE TITLE
Cannot disable yellow tips at the top of the window

### ISSUE THREAD

**Issue by vahotm** [git-up/GitUp#367]
Every time I install GitUp on new machine, it thinks I'm a newbie and shows yellow tips at the top of the window. Those tips either hover essential controls or moves them to an unexpected  position (50 px down, see screenshot). 

Is it possible to disable them?

![screen_shot](https://user-images.githubusercontent.com/6671245/31936358-05a7cd56-b8ba-11e7-92fb-42170711a7f5.png)

**Comment by tflo** [comment]
Yep, similar problem with the red (warning) banners.

**Comment by swisspol** [comment]
There's but here: these help banners are here on new installs and do not cover anything, just shift the UI down. There's no way to disable them preemptively: you have to dismiss them.

**Comment by vahotm** [comment]
Isn't there a common UX pattern, that you ask user if he wants to see them or not? Is there a big deal to add an option to at least disable them from settings?
