### ISSUE TITLE
Feature request: remember window size and position

### ISSUE THREAD

**Issue by ryexley** [git-up/GitUp#368]
I love gitup...it's easily my favorite tool for working with git repositories. Please keep up the great work. Thank you so much for making such a fantastic tool freely available.

There is one small thing that I would love it if it would do better. My workflow is typically to _not_ keep gitup open all of the time. I typically do my work, and then when I'm ready to commit and push some code, I'll open it up in gitup, via the command line, review the code, commit and push.

It would be _SUPER_ nice if gitup could **remember the size and position of the window from the last time I had it open whenever I open it up again**.

Forgive me if this is a duplicate issue...I searched through the issues for some of the above keywords (size, position, etc) and didn't see anything related to this. Happy to close it if this is a known issue or has already been discussed.

Thanks again.

**Comment by swisspol** [comment]
Make sure you have this setting off in System Preferences > General:

![image](https://user-images.githubusercontent.com/627915/32034441-77e95822-b9c7-11e7-8aab-e678924a21d6.png)
