### ISSUE TITLE
Lately fetch is never completing

### ISSUE THREAD

**Issue by jasongregori** [git-up/GitUp#375]
In the console I see the following:

default	11:21:05.452389 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:06.495031 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:07.552479 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:08.660245 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:09.751052 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:10.812208 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:11.825383 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:12.866281 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change
default	11:21:13.879335 -0800	GitUp	com.apple.foundation.filecoordination	Foundation	Making presenter FEB2C799-271B-4191-9C07-A51A8989476F observe change

Is there any way I can debug this?

**Comment by swisspol** [comment]
I would just build and run the app from Xcode and watch the console output as well as put breakpoints.
