### ISSUE TITLE
Option to load credentials from file instead of from keychain

### ISSUE THREAD

**Issue by CrazyPython** [git-up/GitUp#377]
This is the only major roadblock preventing a port to Linux. http://mediawiki.gnustep.org/index.php/Writing_portable_code#Porting_from_Cocoa_or_OPENSTEP_.28NS.2A.29_to_GNUstep
https://github.com/gnustep/libs-quartzcore

**Comment by swisspol** [comment]
I am highly skeptical of this statement. Even if theoretically correct, one would first need to actually port the entire app and then reach a point where it is indeed the very last thing to do.

In any case, there's no plan to support such a feature, sorry.
