### ISSUE TITLE
Alignment issues in Remotes menu

### ISSUE THREAD

**Issue by infotexture** [git-up/GitUp#378]
In Version 1.0.9 (1024), several of the keyboard shortcuts that appear in the **Remotes** menu have alignment issues: the shift ⇧ and command ⌘ symbols are not aligned with the same baseline as the command name, and the ⌘ symbols partially overlap the following letters:

![gitup-remotes-menu-glitch](https://user-images.githubusercontent.com/129995/32702940-a2865d2a-c7ee-11e7-83a0-f66ff7820714.png)

**Comment by swisspol** [comment]
What OS is this on? This would be some OS issue, not an app bug.

**Comment by infotexture** [comment]
Seen on macOS Sierra 10.12.6, but after restarting the app, the issue is gone, so I'll close this.
