### ISSUE TITLE
Follow and import gitconfig IncludeIf

### ISSUE THREAD

**Issue by lukaswelte** [git-up/GitUp#380]
GitUp makes a great job of reading the local gitconfig. 
But there is `IncludeIf` which allows to e.g. include a specific config for certain directories.

```
[includeIf "gitdir:~/Development/my_company/"]
  path = .gitconfig_my_company
```

This includeIf is read from the config but the contents of the config file are not imported and thereby not used.

**Comment by swisspol** [comment]
For this to happen, libgit2 would need to support this feature. I don’t know if the latest version does.

**Comment by lukaswelte** [comment]
Cause it was implemented in libgit2 as @deild mentioned, it could now be integrated into GitUp @swisspol? Or is there still something external missing?

**Comment by svdo** [comment]
I would love to have this feature as well. 

Gitup is awesome, thanks!!!!

**Comment by svdo** [comment]
Oh I think this issue is a duplicate of #315 by the way.

**Comment by lucasderraugh** [comment]
Thanks! I’ll close this to make for one place to track this issue.
