### ISSUE TITLE
Operations on large files are super slow on macOS High Sierra

### ISSUE THREAD

**Issue by aleksandergrzyb** [git-up/GitUp#385]
Since upgrading to macOS High Sierra, GitUp application is not responding for a very long time (approx. 1 minute, sometimes even more) when staging/opening/stashing large files (couple of thousands of lines). 

Using regular command line interface behaves as expected. The wait time is maximum one second.

I will be happy to help to investigate this issue further. I am really enjoying the program and I am using it for a very long time, but since upgrading to macOS High Sierra the client became unusable (also other Git clients, such as Tower, work properly).

**Comment by swisspol** [comment]
Can you sample the app or build it locally and see in XCode where the time is spent?

**Comment by aleksandergrzyb** [comment]
Great idea! I will do that.

**Comment by aleksandergrzyb** [comment]
I tried to open a commit view using quick view (by pressing space key) that had changes to this large file (almost 36k lines, it's actually `project.pbxproj` from Pods project). I run Time Profiler to check which methods are blocking main thread, I waited almost 8 min 30 second, but the commit still didn't open. 😞

Below you can find the report:

[report.trace.zip](https://github.com/git-up/GitUp/files/1543200/report.trace.zip)

**Comment by swisspol** [comment]
I'm not observing any regression on 10.13.3 vs 10.12 on my MacBook Pro with 1.0.9 or latest `master`. Let me know if you can find a repro case with a sample repo on GitHub and we can revisit.

**Comment by aleksandergrzyb** [comment]
I will try to create sample project that reproduces the problem and upload it to Github. Thanks!

**Comment by wmertens** [comment]
I have it every time when I'm looking at `package-lock.json`, whether it's a new file or a small diff of the file.

Repro repo at https://github.com/wmertens/gitup-slow-repro

@swisspol reopen?

**Comment by wmertens** [comment]
@Fab1n https://github.com/btford/participating-in-open-source#assume-everyone-is-doing-their-best

**Comment by Fab1n** [comment]
@wmertens @swisspol I am sorry, didn't want to sound harsh and blame others, just wanted to inform that this issue is still existing. Sorry for the wrong words, I'll try to do better next time.
