### ISSUE TITLE
Feature request: Command line tool default behavior should be open with specified path

### ISSUE THREAD

**Issue by oliverhr** [git-up/GitUp#386]
It would be nice to open current path like we do with other tools:

```bash
gitup .
```

i now currently we can achieve this by running:

```
gitup open .
```

**Comment by ppo** [comment]
… and more importantly, it could allow to open another path without having to `cd` there first.

**Comment by chmac** [comment]
@ppo I found this issue with the same goal as you, thanks for the script, that's super useful.

I think this issue can now be closed, running `gitup` in a directory does open that directory, which I believe is what this feature request is about.
