### ISSUE TITLE
Elevate "Quick View" to a "History View" with tabbar icon, ⌘-1 menu command, etc

### ISSUE THREAD

**Issue by snoblenet** [git-up/GitUp#392]
Great tool, but Map view is a gimmick and needs to be demoted and Quick View is really handy and needs to be promoted.

I did not realise that it was even possible to scroll the history of commits on a branch until I discovered 'quick view' buried in a contextual menu in those tiny tiny UI targets in the generally useless Map view.

Quick View should get a more meaningful name, like History View, and it should have an icon in the tabbar, and a short cut in the View menu. It should be view ⌘-1, followed by Commit, then Stashes, then Map (which is called Network in most other Git websites and Git clients).

But great job! I look forward to this tool growing in stature.

**Comment by PixelPirate** [comment]
You can use the `space`-key. It's the default QuickLook key and works in many Apps e.g.: Finder to quick preview files, Mail to quick preview attachments and GitUp to preview changes of a commit.
Using `space` is really fast and natural on macOS.

But adding a QuickLook item to the toolbar might help to communicate to people that QuickView works just as QuickLook does. (Maybe it should be renamed too?)

**Comment by swisspol** [comment]
Thanks for the feedback. The UX of GitUp, with the map front and center, is by design and there are no plans to revisit it.
