### ISSUE TITLE
Timeline tree view

### ISSUE THREAD

**Issue by brotherbain** [git-up/GitUp#394]
When using gitup after leaving sourcetree the first thing I missed was the timeline version of the tree.  Instead of all trees' nodes competing for the same lateral space, often with branch names overlapping, you have one node per 'line' sorted in order by date with a few exceptions.  This makes it possible to neatly show the data currently in the node tags across each node's line, which in turn makes for easier scanning/navigation.

I imagine this is a heavy lift, so I'll leave it as a wish-list item.  Keep up the good work!  You've all done an admirable job so far.

**Comment by swisspol** [comment]
Thanks for the encouragement and suggestion. There are no plans to create such a view though, that's the intent of GitUp. The closest functionality is "HEAD ancestors": Cmd-D.
