### ISSUE TITLE
Generic application icon

### ISSUE THREAD

**Issue by davidfmiller** [git-up/GitUp#396]
Probably not high on the priority list, but a slightly less generic application icon would be  greatly appreciated. The low-contrast grey-on-white lines/treatment is basically invisible at smaller sizes:

![gitup-dock](https://user-images.githubusercontent.com/12614/34222018-eeca306a-e56e-11e7-86e2-5b83aa1fa227.png)

(Shameless plug: I'd love to have a go at creating an icon)

**Comment by tflo** [comment]
Great idea, yes. The icon is extremely ugly and looks almost like a placeholder graphic. As if I write an app and still haven’t designed the icon, or decided for an icon.

**Comment by davidfmiller** [comment]
I wasn't gonna say anything! 🙊 I can only imagine the amount of work required for finishing the _difficult_ things in the app.

I'm thinking something along the lines of an icon based on the usual commit/pull-request/merge/branch graphics used on Github & Bitbucket & other source-code-related things:

![screen shot 2017-12-20 at 12 59 17 pm](https://user-images.githubusercontent.com/12614/34228514-c9a6f824-e585-11e7-9542-ea59b9007c64.png)

... combined with some sort of "up" motif.

Crazy, right?

**Comment by swisspol** [comment]
Sounds like a dup of #216.
