### ISSUE TITLE
When using QuickLook, GitUp sometimes opens tens of FileMerge instances

### ISSUE THREAD

**Issue by tomnazarenko** [git-up/GitUp#401]
This does not happen every time, but here is the way I am able to reproduce the bug:

Make a branch with several commits. Checkout commit that was a couple of commits back. Use QuickLook to view commits that are further ahead. Bang, GitUp might go haywire with FileMerge tool.

**Comment by swisspol** [comment]
Can't repro on latest `master` on 10.13.3.
