### ISSUE TITLE
Preview of commit showed too earlier.

### ISSUE THREAD

**Issue by akoppela** [git-up/GitUp#404]
Hello. I've just upgraded to High Sierra 10.13.2. And can see strange behaviour of previewing the commit. Now if I hit `space` to preview the commit it will expand from commit place to full window size. However it's now possible to see already previewed commit on the background which is already fully scaled. Before upgrade I've not experienced same issue.

![image](https://user-images.githubusercontent.com/56569/34660871-9cc77b12-f480-11e7-904c-0984b3df9201.png)

**Comment by Briahas** [comment]
Yep, same here. But it doesnt bother me cose it happens to quickly.

**Comment by swisspol** [comment]
This a bug with the Quick View animation, which I don't have time to maintain, so I'll just remove it.
