### ISSUE TITLE
How to wipe GitUp's data?

### ISSUE THREAD

**Issue by r00ger** [git-up/GitUp#407]
That's more a question, but it would be nice to have it answered and maybe somewhere documented. I accidentally checked "Show Remove Branch Tips" on a huge repo and GitUp hanged. Since then I can't open the repository in GitUp it hands with 8Gb allocated memory forever. Is there a way to wipe the setting so that GitUp will open the repo in default view, which do not have "Show Remove Branch Tips" checked?

**Comment by rm-code** [comment]
Not sure, but I'd try removing the `co.gitup.mac` folder inside of the repository's `.git` folder.

**Comment by r00ger** [comment]
I've noticed and already removed. Didn't help.

**Comment by rm-code** [comment]
Again, just an idea. Another place GitUp stores cached data is in:

`~/Library/Caches/co.gitup.mac`

**Comment by r00ger** [comment]
I did try that as well. No success

**Comment by swisspol** [comment]
These display settings are indeed stored in `.git/co.gitup.mac`.
