### ISSUE TITLE
ESC closes Ancestors view instead of modal dialog

### ISSUE THREAD

**Issue by ole** [git-up/GitUp#408]
Steps to reproduce:

1. Open Map View (⌘1).
2. Make sure the Browse Head Ancestors… view is visible (⌘D)
3. Select a commit and type E to edit the commit message. A modal dialog opens.
4. Hit ESC.

Expected results:
The modal dialog is closed.

Actual results:
The modal dialog stays visible. Instead, the Ancestors view is closed. This action also causes the modal dialog to lose keyboard focus, which means it won't close even if you hit ESC once more.

Version: GitUp 1.0.9 (1024), macOS 10.13.2.

**Comment by lolgear** [comment]
@ole 
Can you reproduce it on latest release? I suppose it has been fixed.

**Comment by ole** [comment]
@lolgear Thanks for the heads-up. I can confirm that I can't reproduce this in 1.1 (1031). Closing.
