### ISSUE TITLE
git status mismatch

### ISSUE THREAD

**Issue by iljaiwas** [git-up/GitUp#412]
GitUp is not allowing me to merge branches, because it reports modified files. However, git on the command line and SourceTree think my repo is clean.

If I use the Discard command in GitUp, I end up with a broken local repo. All subsequent git invocations fail with the error message: "fatal: multiple stage entries for merged file". 

However, cloning the repository anew from origin doesn't solve the issue. The same modified file are reported again.

Any ideas why this could be and how to fix it.

<img width="1326" alt="screen shot 2018-01-26 at 11 59 55" src="https://user-images.githubusercontent.com/2284114/35437111-52d9f51a-0291-11e8-8f66-a20b55a018b7.png">

**Comment by swisspol** [comment]
Most likely your these files are checked-in twice in your repo but with different cases: see #117 and #93.
