### ISSUE TITLE
Commit button keyboard shortcut in Advanced Commit View not working

### ISSUE THREAD

**Issue by simonkeys** [git-up/GitUp#418]
Pressing Opt-Return in Advanced Commit View has no effect. Is there a different keyboard shortcut that works for this?

GitUp Version 1.0.9 (1024)
OS X 10.12.6

**Comment by swisspol** [comment]
It’s the right shortcut. Make sure the caps lock key is not active.

**Comment by simonkeys** [comment]
Figured out what the problem was: I had Input Source set to Unicode Hex Input (System Preferences>Keyboard>Input Sources>Unicode Hex Input). In that case the commit shortcut is nonfunctional.

Maybe a note in the wiki? In my experience setting input to Unicode Hex doesn't typically affect Opt+_ shortcuts.
