### ISSUE TITLE
How to recover untracked files which has been discarded when saving stash?

### ISSUE THREAD

**Issue by LeelaRamala** [git-up/GitUp#422]
Is there any way to get untracked files(new files) added that has been removed while stashing changes?

I've added new files and when I stash them(I've not included them for stashing and i've discarded those files). Now I can't see those physical files in my mac memory. Is there any way that i can recover it?

**Comment by swisspol** [comment]
If you remove files from the commit area, GitUp simply moves them to the Trash.

**Comment by mohamadsheam** [comment]
Hi, Did you find any solution for this issue? I also need to know
