### ISSUE TITLE
SSH session: Unable to exchange encryption keys

### ISSUE THREAD

**Issue by mime29** [git-up/GitUp#432]
I get the following error on gitup
`Failed connecting to "origin" remote: Failed to start SSH session: Unable to exchange encryption keys`
Even after executing `ssh-add -A`

It happens with I try to SHIFT CMD P and CMD P for example (interaction with the remote which makes sense)

**Comment by SenHeng** [comment]
refer to this thread #421

**Comment by mime29** [comment]
Thanks, closing this Issue
