### ISSUE TITLE
Branch 'line' sometimes disappears

### ISSUE THREAD

**Issue by SenHeng** [git-up/GitUp#437]
<img width="591" alt="gitup" src="https://user-images.githubusercontent.com/11208360/37129760-d9816dbc-22c3-11e8-9118-3882be71796e.png">

## Situation

Branches: `master`, `a`, `b`.
`a` was built on top of master. `b` branched off of `a` and is one commit ahead.

- `master` had new changes merged into it
- rebased `b` off of master
- deleted `a`
- create a new `a` branch from master

I think what happens here is that GitUp thinks `a` ahead of `b`?
This happens quite often when rebasing and splitting branches but isn't that predictable.

**Comment by swisspol** [comment]
See #44
