### ISSUE TITLE
Get 'Working directory contains modified files' message when it's not true

### ISSUE THREAD

**Issue by joachim-n** [git-up/GitUp#438]
I tried to do 'Split' a commit and got the error message 'Working directory contains modified files'.

But I had just done a 'git stash' and 'git diff' shows nothing.

**Comment by swisspol** [comment]
What if you relaunch GitUp?

**Comment by joachim-n** [comment]
No change.
Getting this again with the 'Swap with parent' command.

**Comment by swisspol** [comment]
What if you git status?

What does the commit window show in GitUp? It would tell you what has changed.

**Comment by joachim-n** [comment]
Git status said there are no modified files (but lots of untracked ones).

I'll check the commit window next time this happens.

**Comment by swisspol** [comment]
There you have it: untracked files count as modified files for GitUp. Bottom line your repo is not clean.

**Comment by joachim-n** [comment]
> untracked files count as modified files for GitUp

Why? They don't count for git -- I can rebase with untracked files present.

At the very least, you need to change the 'Working directory contains modified files', as it's incorrect. You're trying to say that the working directory contains modified *or untracked* files.

**Comment by AlejandorLazaro** [comment]
I am also still seeing this even without any untracked files, but with submodules in the git repo that may be out-of-date.
