### ISSUE TITLE
cli symlink conflict with git-repo-updater binary

### ISSUE THREAD

**Issue by craftey** [git-up/GitUp#440]
GitUp command line tool has same name as https://github.com/earwig/git-repo-updater.
Reverse discussion here: https://github.com/earwig/git-repo-updater/issues/19

Can GitUp rename its cli tool (name of the symlink) to something else?
E.g. `git-up` or `gitup-app` or `gitupp` or something else.

Reproduce issue via:
```
brew install gitup // installs git-repo-updater
ls -l /usr/local/bin/gitup
brew cask install gitup // installs GitUp.app
ls -l /usr/local/bin/gitup
```
Regards, Craftey

**Comment by swisspol** [comment]
Thanks for the report, but won’t fix this, sorry.
