### ISSUE TITLE
Error while working with Heroku remote

### ISSUE THREAD

**Issue by nicoespeon** [git-up/GitUp#441]
Hi there 👋 

First of all, thanks for GitUp. This has been my Git-GUI reference for months 🙏 

---

I started working on a project using Heroku remote git to do deployments.

Thus, I added the remote like so (from `.git/config`):

```
[remote "production"]
        url = https://git.heroku.com/our-super-repo.git
        fetch = +refs/heads/*:refs/remotes/production/*
```

Using git CLI, everything is fine.

But, whenever I try to fetch the remote on GitUp I get the following error:

<img width="659" alt="capture d ecran 2018-03-13 a 18 36 48" src="https://user-images.githubusercontent.com/1094774/37373709-222bd3bc-26ee-11e8-98b2-fcad85eccf21.png">

I tried to switch to [SSH Git transport](https://devcenter.heroku.com/articles/git#ssh-git-transport). It worked from the CLI, but the result is the same with GitUp 🤷‍♂️ 

Do you have any clue for me? Did I miss something?
Thanks!

**Comment by swisspol** [comment]
Something must be strange in your configuration: if GitUp uses SSH then your remote is SSH based not HTTPS based.

Make sure your SSH key is added to SSH agent or is in ~/.ssh without a password and you should be fine.

**Comment by swisspol** [comment]
There’s more info in https://github.com/git-up/GitUp/wiki.

**Comment by nicoespeon** [comment]
@swisspol sorry, I was uncleared by reporting all the details in chronological order.

HTTPS is the default for Heroku remote. But, as I said, I switched to [Heroku SSH Git transport](https://devcenter.heroku.com/articles/git#ssh-git-transport) − basically configuring git to replace Heroku HTTPS with Heroku SSH globally. 

Thus, the call is done with SSH:

![image](https://user-images.githubusercontent.com/1094774/37673542-d8936e1e-2c46-11e8-9a3f-7bed4f720a1b.png)

Using the CLI, there is no problem. My key is in ~/.ssh with no password.
Still, when I fetch remotes on GitUp I get this error.

May be related:
- I've got 2 remotes: **origin** (which is the GitHub repo) and **production** (which is Heroku)
- I only use 1 SSH key for both GitHub and Heroku, which is `id_rsa`

Could there be a conflict with both remotes using the same key?

I'll keep digging 🔍

**Comment by nicoespeon** [comment]
As a feedback: I'd have appreciated you ask me if my question was solved before closing the issue right away. 

Not a big deal 👐 but I took care of giving details and context and I feel disappointed that it was just closed while I'm still in trouble 😉

Thanks!
