### ISSUE TITLE
changing a commit message makes the solid line of the current branch go dotted

### ISSUE THREAD

**Issue by joachim-n** [git-up/GitUp#442]
I was on a particular branch, and used the 'Edit message' comment on the commit 1 back from HEAD.

After that was done, the current branch changed from a thick line to a dotted line, with the commits still showing as white circles.

![screen shot 2018-03-14 at 15 21 07](https://user-images.githubusercontent.com/105262/37411685-4c06b226-279b-11e8-8af3-0f11d9283700.png)

**Comment by joachim-n** [comment]
Closing the repo window and reopening it doens't fix this, nor does quitting gitup outright and relaunching.

**Comment by swisspol** [comment]
See #44

**Comment by AlexMouton** [comment]
Hi Guys
I think I am seeing the same thing persist across multiple branches.
No other insight just wanted to catalog symptoms.

Thanks!
A
<img width="357" alt="screen shot 2018-06-15 at 2 12 47 pm" src="https://user-images.githubusercontent.com/1989298/41489867-507f3450-70a6-11e8-8c6e-797ae3eee473.png">
