### ISSUE TITLE
Question: Why are the commit dots sometimes different sizes?

### ISSUE THREAD

**Issue by TedDriggs** [git-up/GitUp#443]
This image was taken on the latest version:

![gitup commit dots](https://user-images.githubusercontent.com/4805575/37656032-1ee4264e-2c04-11e8-87cd-a80e5f49dd6b.png)

I'm curious what makes some dots fit within the solid line while others slightly breach it. Is this a bug? An undocumented feature?

**Comment by swisspol** [comment]
These are merge commits. Change the view options to show more branches and see what is being merged,

**Comment by TedDriggs** [comment]
@swisspol they're not merge commits, though turning on remote branch tips did reveal what they are. Each large dot appears to be the launching point for another solid line.

Thanks for the quick response!
