### ISSUE TITLE
hooks and lfs folders are created on project root instead of inside .git folder when using git-lfs

### ISSUE THREAD

**Issue by halileohalilei** [git-up/GitUp#445]
I have just migrated my Mac to another one. There were some problems with symlinks and permissions but I've resolved them all. The one problem that's remaining is that now when I add a .pdf file to my repo and switch to Commit screen, git-lfs creates new hooks and lfs folders on my project root, instead of using the existing ones under the .git folder. 

I tried reinstalling both git and git-lfs but that didn't work. Then I tried adding the file to the repo and committing via Terminal, and there were no problems. However, if I then open up GitUp and switch from Map screen to Commit screen, the folders are created again. So I'm guessing something wrong is happening with GitUp, but I have no idea what it is. 

Anyone have any ideas?

**Comment by swisspol** [comment]
Never heard of such a problem before it seems like it comes from git lfs not GitUp.

**Comment by daGrevis** [comment]
We are also experiencing the same problem with GitUp.
