### ISSUE TITLE
Very slow performance when doing large number of diffs

### ISSUE THREAD

**Issue by raulriera** [git-up/GitUp#446]
Super edge case, but when dealing with a large number of files. Gitup will hang when switching to the commit view. In my setup I am trying to diff removing 2600 files and adding a new set of 2600 filled (all small pdfs) into an Xcode project (which will also generate a large diff XML)

<img width="804" alt="screen shot 2018-03-25 at 5 57 23 pm" src="https://user-images.githubusercontent.com/24159/37880410-03107cdc-3056-11e8-91cd-8595875b8f9f.png">

This is running on a brand new latest generation MacBook Pr

**Comment by swisspol** [comment]
Edge case indded. This is not something that is going to be fixed I’m afraid: rendering the diff of 2600 files at once will never be fast.

**Comment by aleksandergrzyb** [comment]
It's not only huge number of file, but also singular larger file. Could you please look at #385?

**Comment by raulriera** [comment]
That makes sense, since my Xcode project will grow very large and I would assume that is the one causing the choking up instead of the "list of items"
