### ISSUE TITLE
Download page is not using https

### ISSUE THREAD

**Issue by green-coder** [git-up/GitUp#448]
I suggest to use the release page on Github to provide the built sofware -OR- to setup httpS on your webpage.

**Comment by mcdado** [comment]
Seems solved?

![screen shot 2018-06-25 at 10 33 18](https://user-images.githubusercontent.com/898057/41839534-c56f13c4-7863-11e8-8fec-2ea623f51899.png)

**Comment by green-coder** [comment]
It is fixed: https://github.com/git-up/GitUp/releases
