### ISSUE TITLE
Better support for vibrancy

### ISSUE THREAD

**Issue by saagarjha** [git-up/GitUp#449]
Hi! I was using GitUp and noticed that some parts of it looked slightly out-of-place, and I think this might be partially due to a lack of vibrancy throughout the app. For example, here's the map view as it is currently:

![screen shot 2018-04-10 at 21 22 21](https://user-images.githubusercontent.com/13786931/38596269-6e51daf2-3d05-11e8-9e34-4bdeba8155a7.png)

Here's an IMO nicer way and more native looking map view I whipped up:

![screen shot 2018-04-10 at 21 20 41](https://user-images.githubusercontent.com/13786931/38596281-8192e35e-3d05-11e8-8b81-527eb71e36e7.png)

Notice the use of `NSVisualEffectView` for the bottom panel. I was thinking of adding a bit more vibrancy throughout the app, but I've hit a wall because of the way it's designed. In particular, vibrancy depends heavily on content insets that aren't made available to `Document`, as well as unrestricted content that abuts the title bar. For example, notice how vibrancy in the toolbar appears here:

![screen shot 2018-04-10 at 21 27 43](https://user-images.githubusercontent.com/13786931/38596399-2b4c2e46-3d06-11e8-8e7b-60691c647b05.png)

but not here:

![screen shot 2018-04-10 at 21 28 42](https://user-images.githubusercontent.com/13786931/38596406-33accc4e-3d06-11e8-89c0-bb82ab6a6350.png)

That's because the table view can't scroll under the titlebar due to the header views in the way. I'm trying to get this to work, but the way GitUp is laid out currently just doesn't really seem to be conducive to adding this behavior. Do you have any suggestions on how I should structure this?

**Comment by swisspol** [comment]
GitUp UI was designed with modularity in mind and fully reusable components. And that was all pre vibrancy. I don’t think it would be easy work to retrofit this. Unfortunately this is not my area of expertise anymore, so can’t suggest a path forward.

**Comment by saagarjha** [comment]
@swisspol I thought about this a bit and I think I've got a reasonably clean solution. I've opened #450 for you to take a look at it.

**Comment by swisspol** [comment]
Nice for sending this in. I'm pretty busy these days so I won't be able to review the PR soon. Looks impressive though, nice work!

**Comment by saagarjha** [comment]
Thanks! I'm in no rush, I'm using it currently to test how it's working out. I think there's actually a bug in the current implementation, so I'll try to track it down and fix it sometime soon.
