### ISSUE TITLE
GitUp generating trees with duplicate entries

### ISSUE THREAD

**Issue by mpavey0** [git-up/GitUp#454]
**Symptoms**:
1) Attempting `git push remotename branchname` produces:

```
remote: error: object 954a5107353081565e8ce093e26e9d8913280a1d: duplicateEntries: contains duplicate file entries
remote: fatal: Error in object
error: remote unpack failed: index-pack abnormal exit
To github.com:userid/reponame.git
 ! [remote rejected] branchname -> branchname (failed)
error: failed to push some refs to 'git@github.com:userid/reponame.git'
```

2) Running `git fsck --no-dangling` produces:

```
error in tree 954a5107353081565e8ce093e26e9d8913280a1d: duplicateEntries: contains duplicate file entries
error in tree baea7bc3e75bd1e6caf8c9ca322fe5130ba25f0a: duplicateEntries: contains duplicate file entries
```

**Investigation:**

`git ls-tree 954a5107353081565e8ce093e26e9d8913280a1d --full-tree -rt -l` produces:

```
100644 blob 89cd1bfb64f9288b7a97a1d39d94c4d5a0ac36e4   15812	Mygvip.php
100644 blob 89cd1bfb64f9288b7a97a1d39d94c4d5a0ac36e4   15812	Mygvip.php
```
(followed by an innocuous-looking list of non-duplicate entries).

This is not entirely surprising. I remember when working on this file that GitUp was behaving strangely. I can't remember the exact details, but I made some changes to the contents of this file, as well as renaming it such that the first letter of the filename was capitalized. In GitUp, I got into a confusing situation where the file was listed twice in the staging area (I think), and I either couldn't commit (nothing happened when I clicked Commit), or when I did commit, instead of the staging area and working directory both being cleared of any references to the changed file, it stuck around for some reason. I think I ended up removing the file from Git, committing, then readding it and committing again in order to proceed. And I may have ended up falling back to the command line to do so.

I've spent half a day struggling to figure out how to fix this (with no luck as yet). Hopefully GitUp can be fixed to avoid anyone else suffering the same fate 😄

**Comment by swisspol** [comment]
Thanks for the report. GitUp uses https://github.com/libgit2/libgit2 under the hood, not Git CLI so it would be a bug on their side. That said, I've never heard of such an issue before and libgit2 itself is quite reliable. A bug that would result in such trees is not impossible but something else could have equally likely happen e.g. disk corruption or the `.git` directory or index file being partially overwritten, who knows...

**Comment by mpavey0** [comment]
Thanks for the info! I'll log the bug over there then. 

I do hope some of the reliability issues I've faced with GitUp can be fixed, I love GitUp but am very hesitant to use it now. In addition to this issue it usually crashes around a couple of times a day :(

**Comment by dbnex14** [comment]
@mpavey0 Having exact same issue but I am using Mac, git v.2.19.1 and SourceTree
I am working in crossplatform team so some of us have Windows, others have Mac
One Mac (the one using SourceTree) is seeing this issue over and over
