### ISSUE TITLE
Is there a way to read console logs?

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#455]
For example when using git with console, there are error messages, that describe the situation. Gitup, when it's an error, just say that can't do something without the description.
Test case - go to atlassian and create a repo. Upload more than 2 Gb. If it would be over 2Gb, than the uploading will not success. But in GitUp it would be an error without the description, that there is not enough space.

**Comment by swisspol** [comment]
GitUp uses https://github.com/libgit2/libgit2 under the hood, not Git CLI so the errors are not captured the same way. IIRC GitUp doesn't capture any error message returned by the Git server.
