### ISSUE TITLE
[10.14] 3 buttons view switcher doesn't work

### ISSUE THREAD

**Issue by FadeFei** [git-up/GitUp#459]
No response of clicking three select view button.
![image](https://user-images.githubusercontent.com/20281026/41074150-379b4eec-6a39-11e8-877b-fdb78f25b53d.png)

**Comment by saagarjha** [comment]
I have this fixed locally, along with other WIP fixes like dark mode support. Stay tuned!

**Comment by swisspol** [comment]
You can use the "View" menu instead or the keyboard shortcuts Cmd-1/2/3 right?

**Comment by swisspol** [comment]
Should be fixed by #460.

**Comment by toastrr** [comment]
I too have the same issue!
