### ISSUE TITLE
Stash: Don't reset the index doesn't work

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#461]
![image](https://user-images.githubusercontent.com/8013017/41229669-882bdc2e-6d85-11e8-944d-0a774f61c258.png)
When using "stash" feature, the _Don't reset the index_ toggle doesn't have any effect on the app's behavior: the index is being reset always.

**Comment by swisspol** [comment]
This is expected behavior but the wording is confusing. It means create a stash in way that the index is preserved (not reset) when it's restored. See `--keep-index` in https://git-scm.com/docs/git-stash.
