### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by yonaskolb** [git-up/GitUp#465]
Is there a way to get GitUp to play nicely with Github's 2 factor authentication?

**Comment by swisspol** [comment]
Yes, simply use a personal access token like with any other tool:
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

Or use SSH instead of https.

**Comment by yonaskolb** [comment]
Yes, I'm using a personal access token but Gitup isn't remembering it and asks me with every access to github

**Comment by splodingsocks** [comment]
I'm seeing the same behavior using a personal access token.
