### ISSUE TITLE
Unable to switch views in macOS Mojave

### ISSUE THREAD

**Issue by toastrr** [git-up/GitUp#466]
I am stuck on the screen where it shows the visulaization of all my commits.
![gitup issue](https://user-images.githubusercontent.com/27452990/41869597-83a732cc-7887-11e8-96f3-80364ff3b9d9.gif)

**Comment by hawkrives** [comment]
See also: https://github.com/git-up/GitUp/issues/459

**Comment by swisspol** [comment]
Seems like a dup.
