### ISSUE TITLE
Authentication Required, but `git fetch` on command-line works without credentials

### ISSUE THREAD

**Issue by Sh4pe** [git-up/GitUp#471]
When I'm trying to interact with a remote repository (e.g. fetch, push, pull), a window titled "Authentication Required" pops up asking for my user name and password. However, when I'm using the same repository with `git` from the command line, I don't need to enter any username or password.

However, the issue does not occur when I start the GitUp executable from the shell (`/Applications/GitUp.app/Contents/MacOS/GitUp`) or when I use the shell command `gitup`.

So the problem only occurs when I start GitUp from the Dock or with Spotlight. Is there a way to make this work even from Dock or Spotlight?

**Comment by Sh4pe** [comment]
Today it did not work event when I invoked `gitup` from the terminal. I had to `ssh-add -K` and then invoke `gitup`. After that, it works.

**Comment by swisspol** [comment]
If you have an http remote the GitUp will prompt for username / password and remember it. For an shh remote, it needs to have the ssh key - see SSH related info in https://github.com/git-up/GitUp/wiki.

**Comment by Sh4pe** [comment]
Okay, thank you!
