### ISSUE TITLE
Improve website TLS

### ISSUE THREAD

**Issue by kalafut** [git-up/GitUp#474]
Just a couple of comments re: gitup.co

- With Chrome 68 out, the site is now prominently marked as "Not Secure". A redirect to https would be good.
- The cert setup for https://gitup.co has problems and is triggering browser warnings.

Thanks,
Jim

**Comment by swisspol** [comment]
Fixed now!

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
https://help.github.com/articles/setting-up-an-apex-domain/
