### ISSUE TITLE
GitUp shows ghost edit?

### ISSUE THREAD

**Issue by SenHeng** [git-up/GitUp#480]
There's a file that's always displayed as deleted in GitUp's working directory, but the file isn't actually deleted or modified. There is no way to delete the changes made. If change is staged, it can't be unstaged from within GitUp but can be removed with a simple `git reset` in the terminal.

It is possible to actually commit the ghost edit. Doing so makes the actual file disappear. Deleting the commit or doing a hard git reset makes the ghost edit reappear again.

<img width="862" alt="2018-10-05 12 02 45" src="https://user-images.githubusercontent.com/11208360/46514061-9f6a6600-c896-11e8-91ff-ba3a241f4ad0.png">

If a change is made to the actual file, 2 files with the same name shows up.

<img width="506" alt="2018-10-05 12 04 30" src="https://user-images.githubusercontent.com/11208360/46514116-de98b700-c896-11e8-81af-dc8d1f04ac89.png">

This problem doesn't occur in the terminal, vscode or sourcetree.

Please let me know if you need anymore info.

**Comment by swisspol** [comment]
See #117
