### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by krabbypattified** [git-up/GitUp#495]
Is this repository abandoned?

<img width="752" alt="screenshot 2019-01-21 at 17 26 14" src="https://user-images.githubusercontent.com/13423815/51486692-abc0f300-1da1-11e9-9468-5842c0eea4ae.png">

**Comment by swisspol** [comment]
The app works and I'm maintaining it if something breaks - I'm just not actively developing it.

**Comment by krabbypattified** [comment]
@swisspol Understandable. You are only one person. If the repository is not being actively developed, maybe is it worth mentioning in the README and/or on the front page of the website. For me personally it would have been nice to know up-front. Lots of people are asking for enhancements that no one will ever implement.

**Comment by redbonzai** [comment]
I know how it is to maintain a large app alone.  I know that there are plenty of developers would love to assist in developing new features ( myself included).  People like me would love to see how we can help to develop more featured or to fox any existing issues.  maybe put that in Readme ? 

hope you hace a great day.
