### ISSUE TITLE
Allow for interface scaling

### ISSUE THREAD

**Issue by comatory** [git-up/GitUp#499]
Enable CMD + / - for scaling the views. Basically change text size.

**Comment by douglashill** [comment]
You can get this to some extent in my fork: https://github.com/douglashill/GitUp/releases

I only added changing the text size in the diff view and commit message entry box so far.

**Comment by douglashill** [comment]
@lourenci the PR was https://github.com/git-up/GitUp/pull/283

**Comment by gotjoshua** [comment]
is it confirmed that GitUp is abandoned ? @git-up ? @swisspol ?

**Comment by swisspol** [comment]
This is a duo of #240

**Comment by lourenci** [comment]
@swisspol please, take a look at #283 PR. I've been using @douglashill version and everything is ok.
