### ISSUE TITLE
Tag and branch names truncated in map view if too many of them

### ISSUE THREAD

**Issue by Baawa** [git-up/GitUp#502]
We found an issue where all tag and branch names are not being rendered when there is too many of them on the same commit.

In the image below we have:
- 13 tags
- 3 remote branches
- 1 local branch
all pointing to the same commit.

Might not be the most common use-case though ;)

![skarmavbild 2019-02-21 kl 11 00 31](https://user-images.githubusercontent.com/14069252/53160494-5e19ef00-35c8-11e9-8188-3cfd89865f01.png)

**Comment by swisspol** [comment]
Yes that’s a known issue

**Comment by lucasderraugh** [comment]
Going to close this out to consolidate the issue to #94. It's effectively the same issue where we don't give proper spacing to names along the top.
