### ISSUE TITLE
Is GitUp officially abandoned ?

### ISSUE THREAD

**Issue by gotjoshua** [git-up/GitUp#503]
is it confirmed that GitUp is abandoned ? @git-up ? @swisspol ?

**Comment by swisspol** [comment]
Why would it be abandoned? Just because a software, that is fully functional, is not continuously updated doesn’t mean it has been “abandoned”. I use GitUp everyday myself and every major bug that impacts a lot of users has been fixed since a long time.

**Comment by gotjoshua** [comment]
Just didn't know if you were still around, and saw a comment in another thread indicating that the project must be abandoned...
Wanted to know if you are considering the pull requests, and still around fielding the issues.

I love the app! I use it even in the face of Webstorm's integrated git... i think that says a lot.

**Comment by hftf** [comment]
Yes, it is clearly abandoned just by looking at the number of people asking whether it is abandoned as well as the number of ignored pull requests and issues.

**Comment by swisspol** [comment]
Only very low-risk, small and worth it PRs are being merged. Otherwise you end up adding a lot of code that could introduce regressions.
