### ISSUE TITLE
Add support for socks proxy

### ISSUE THREAD

**Issue by ruffapuffa** [git-up/GitUp#504]
I work against a private password protected gitlab repro.
To access it I setup a socks proxy (pointing to localhost and some unused port number: localhost 53080)
After this I run the following command line:
ssh -D 53080 myUser@external.location.com

By using a socks proxy git have no problem handling both upstream/downstream.
This works for me from the terminal/CLion safari/mail. (as if I were logged in at work)
GitUp doesn't seem to honor the socks settings. Am I missing something?
If not implemented I might give it a go. If someone could point me in the right direction in the source code that would be awesome.

**Comment by swisspol** [comment]
GitUp uses libgit2 under the hood, not the Git CLT so this is setup is not supported.

**Comment by ruffapuffa** [comment]
Ok I guess it is up to libgit to add support for socks proxy. Ill go and see if there is an existing ticket there for this issue already..

**Comment by lucasderraugh** [comment]
Going to close out this issue, unless we know that libgit2 is supporting this feature. We're unlikely to support something that isn't supported by them. That said, you're more than welcome to open this up if libgit2 supports this. Cheers!
