### ISSUE TITLE
can not displayed commit log

### ISSUE THREAD

**Issue by keisukeYamagishi** [git-up/GitUp#510]
I can not see the commit log on the screen below, so I want to improve that part.

<img width="1241" alt="スクリーンショット 2019-03-24 12 55 01" src="https://user-images.githubusercontent.com/5553852/54874709-1212d200-4e34-11e9-872d-c5d3749fe8c2.png">

I think that it is the best if you can easily view the commit log on this screen,

**Comment by NixDeveloper** [comment]
MENU -> Repository -> Browse HEAD Ancestors (cmnd+D)
