### ISSUE TITLE
Is there a way to stage a line?

### ISSUE THREAD

**Issue by MihaelIsaev** [git-up/GitUp#514]
Is there a way to stage just a line?

**Comment by hawkrives** [comment]
Yes; see https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View

> To select lines to stage or unstage, click in the line numbers margin of the diff area (you can also extend the line selection by pressing Shift and Cmd as in standard Mac apps)

**Comment by MihaelIsaev** [comment]
Thanks but please take a look at old good GitX app, there's really natural, convenient and friendly UX for staging lines. Would be great to have the same in GitUp app as well.

**Comment by douglashill** [comment]
What specifically don't you like with how this works in GitUp?
