### ISSUE TITLE
3-button view switcher has unhelpful tooltip

### ISSUE THREAD

**Issue by hftf** [git-up/GitUp#516]
The switcher widget has a single tooltip that says "Select view" regardless of hover position, instead of helpful individual tooltips for each button.

<img width="131" alt="Screen Shot 2019-04-30 at 16 42 59" src="https://user-images.githubusercontent.com/312957/56991994-0cad5380-6b67-11e9-80b4-36490b0eddde.png">

**Comment by lucasderraugh** [comment]
If you have a PR you're willing to contribute, would be a nice fix.

**Comment by hftf** [comment]
I don't plan to make a PR as I wasn't aware the project was interested in PRs.

**Comment by lucasderraugh** [comment]
Well, we’re now open to accepting :)

**Comment by hftf** [comment]
Thanks!
