### ISSUE TITLE
Workspace does not automatically reopen on next launch

### ISSUE THREAD

**Issue by MrSkwiggs** [git-up/GitUp#520]
When disabling the "Appearance: Show the welcome window" option, quitting GitUp and reopening it does not automatically reopen the previously opened workspace.

This was confusing to me at first as I thought GitUp was crashing on start, until I realised what was going on. It's not ideal as I really don't need that initial welcome window

**Comment by swisspol** [comment]
This behavior is actually controlled by this system setting:
![image](https://user-images.githubusercontent.com/627915/58824586-43a4d800-85f1-11e9-9888-45fd8ccdb5bd.png)

Can you double-check this is set properly?

**Comment by MrSkwiggs** [comment]
@swisspol Hmmm I do have it off, but for most apps that only have 1 window open it always reopens the last active one, which is why I was expecting GitUp to behave in the same way

**Comment by MrSkwiggs** [comment]
Sorry I meant I have it on

**Comment by MrSkwiggs** [comment]
Hey @swisspol I think there was a misunderstanding... Do you mean to tell me that if you chose not to show the welcome window, and have that system setting on, launching GitUp just starts the process without opening any window ? 

To me this doesn't feel like standard behaviour.

**Comment by swisspol** [comment]
If this setting is ON then windows are not restored on relaunch. IIRC none of that is defined by GitUp, it’s all built in NSDocumentController.

**Comment by MrSkwiggs** [comment]
Alright I understand that part. Then I guess this is not specifically a bug but more a feature request ? As in, if I choose not to show the welcome window, opening GitUp should automatically reopen the last previous open project ?
