### ISSUE TITLE
How to use if heroku remote is configured ...?

### ISSUE THREAD

**Issue by breathe** [git-up/GitUp#525]
heroku implements some kind of fake git-like endpoint -- can't seem to authenticate to it from gitup and so 'fetch-all-branches' functionality doesn't work ...

Is there a way to workaround?  I have no need to address the heroku remotes in gitup -- but ideally wouldn't have to remove them from my repo config so that the heroku cli stuff works in expected sways ...

**Comment by lucasderraugh** [comment]
I don't use Heroku enough to know what this specific issue would be. If you could elaborate on a sample setup I could try and create myself, perhaps I could try to reproduce what you're hitting and resolve it from the application side.

**Comment by breathe** [comment]
You’ll have to create a heroku account, create a heroku app, and then add the git url that heroku provides for your app as a remote in your git repo.  I believe a trial version of above is available for free ...

I’m not sure what the app can do with the git remote tho — I think it’s basically some kind of fake git server endpoint that only supports pushes ...

**Comment by lucasderraugh** [comment]
Does it work in Terminal to do real git commands, like calling git fetch?

**Comment by breathe** [comment]
@lucasderraugh Yes -- i can run `git fetch` but trying to fetch all branches in gitup gets me stuck in this authentication loop ... (... my credentials are correct tho I believe ...)

<img width="457" alt="image" src="https://user-images.githubusercontent.com/434034/60565978-c6b96b00-9d22-11e9-9d72-1e27edbeb7bc.png">

**Comment by breathe** [comment]
Actually ... I found documentation which helps me resolve this ... https://devcenter.heroku.com/articles/git#creating-a-heroku-remote

Apologies!!
