### ISSUE TITLE
Error when opening repository

### ISSUE THREAD

**Issue by ivanmah** [git-up/GitUp#529]
Earlier on today, the GitUp app crashed on me, and when I re-launched it, opening a particular repository displays an error message:
<img width="532" alt="Screenshot 2019-06-13 at 11 06 53" src="https://user-images.githubusercontent.com/39365246/59400895-858d0580-8dcb-11e9-86bb-bc46665cdb74.png">

Interestingly, opening other repositories do not cause this error message to appear.

Does anyone know how I can resolve this?

**Comment by lucasderraugh** [comment]
I'm not exactly sure what error dialog that would be, but my guess is that the database embedded in .git/co.gitup.mac is broke. You could easily try deleting that folder in your repository and that should resolve any GitUp specific issue (obviously will lose snapshot data, but this will get it running again).

**Comment by ivanmah** [comment]
@lucasderraugh That fixed it! Thanks a lot for your advice!
