### ISSUE TITLE
Unable to copy text (CMD+C) from the diff editor

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#531]
Unable to copy text (CMD+C) from the diff editor

It would be a very handy feature to being able to copy text from the diff editor to the buffer, e.g. to search in the text editor to get more context.

**Comment by lucasderraugh** [comment]
What is the "diff editor", is this the "Commit" tab? That seems to work fine for me. Maybe a screenshot of what view you're referring to would help me :D. Thanks.

**Comment by lucasderraugh** [comment]
I'm just going to close this issue. I can't figure out from where copy doesn't work for you in the diff view. If I'm misunderstanding the area you're talking about, please reopen with a screenshot of the area that you can't copy text from.

**Comment by richardtop** [comment]
Hi, yes, it seems it was an issue of my system. Or, most likely, I was not able to copy a `localizable.strings` file contents (they're treated as the binary file)

**Comment by lucasderraugh** [comment]
If it's a particular file type that you feel should be visible, we can make a feature around that. A screenshot would be helpful too. Thanks.

**Comment by richardtop** [comment]
Just checked, it's the `localizable.strings` file, copying doesn't work there at all.

**Comment by lucasderraugh** [comment]
Is it possible to attach the specific file you're having this issue with? If I change GitUp's Localizable.strings file (it is English) it would appear I can still copy changes in the diff viewer without issue.
<img width="627" alt="Screen Shot 2019-07-05 at 10 19 55 AM" src="https://user-images.githubusercontent.com/714282/60734840-7141b180-9f0e-11e9-9157-5841efde6910.png">

**Comment by richardtop** [comment]
Copy menu works, but the action doesn't actually copy the file.
What kind of settings are you using for your localizable.strings to appear in the GitUp?

Also, did you edit something in your git settings to get changes visible in the GitUp app?

**Comment by lucasderraugh** [comment]
I've done nothing special. I've simply cloned this GitUp repo, opened the project in Xcode, and edited `Localizable.strings` using Xcode. Then if I look in the running GitUp app (open with the GitUp repository), it seems to work as expected.

If you have a repo I could clone and test out on my machine, I'd be happy to try it out. I've done nothing special on my end as far as I know.
