### ISSUE TITLE
A hug for gugs

### ISSUE THREAD

**Issue by peter-leonov** [git-up/GitUp#542]
Thank you a lot for Gitup!

I showed it to my colleague and he gave me a hug! Then I showed how to split commits and he gave me a second one. And this guy is not easy to surprise.

Thank you again!

**Comment by lucasderraugh** [comment]
Glad your colleague loves the application! Let us know if there is anything in particular we can do to improve the experience :). I'm going to go ahead and close out this "issue" just for my sanity in combing through the others.

Cheers!

**Comment by peter-leonov** [comment]
@lucasderraugh, I'm back with a question about Patreon or something alike.

**Comment by lucasderraugh** [comment]
I have my personal [Patreon](https://patreon.com/AppleProgramming) account, but I don't think that necessarily supports this project directly (it's mainly to support my YouTube channel). I think the best ways to get support are bug bounties where you fund an issue you want resolved. That way other contributors can get paid if they resolve issues as I'm usually not the sole person resolving
