### ISSUE TITLE
Python module installation problem

### ISSUE THREAD

**Issue by Jacobgokul** [git-up/GitUp#547]
I already installed all modules of py like numpy, pandas etc., when i try to import in a PYCHARM IDE  it throws a #importerror. And i installed again using interrupter in pycharm.
we need to install those modules again in pycharm although it already installed in a pc ?

**Comment by lucasderraugh** [comment]
@Jacobgokul Are you in the correct project? This is a git GUI client, I'm not sure how python IDEs are relevant here?
