### ISSUE TITLE
Dark theme is brown

### ISSUE THREAD

**Issue by hipstersmoothie** [git-up/GitUp#555]
![Screen Shot 2019-08-22 at 2 00 53 PM](https://user-images.githubusercontent.com/1192452/63549443-5094e180-c4e5-11e9-9ad3-b8569c1352b9.png)

**Comment by lucasderraugh** [comment]
Wo, that's really brown 😅. Do you have some kind of accessibility changes or display color profile that might make it manifest this way? What macOS version do you have? Trying to think of reasons this could occur. This is what it looks like on my end :)
![Screen Shot 2019-08-22 at 2 29 51 PM](https://user-images.githubusercontent.com/714282/63551187-4e348680-c4e9-11e9-8a90-7238b4721e14.png)

**Comment by zwaldowski** [comment]
More to the point, what is your wallpaper? (If you’re comfortable with sharing.) The system is doing sampling for that. In theory, a Finder window or Safari on the New tab page at that same size and position would be the same color.

**Comment by hipstersmoothie** [comment]
I've never set accessibility or any color stuff. I think it is related to the background stuff. I can't get the specific background cause it changes every hour on my system.

Just set it to this and get a similar effect

![Screen Shot 2019-08-22 at 4 15 10 PM](https://user-images.githubusercontent.com/1192452/63556036-18e36500-c4f8-11e9-92c5-1c0b48d8cb1b.png)

<img width="1323" alt="Screen Shot 2019-08-22 at 4 17 27 PM" src="https://user-images.githubusercontent.com/1192452/63556101-5c3dd380-c4f8-11e9-9045-d938cecf2a60.png">

**Comment by hipstersmoothie** [comment]
For future users: 

<img width="671" alt="Screen Shot 2019-08-22 at 4 19 14 PM" src="https://user-images.githubusercontent.com/1192452/63556160-a030d880-c4f8-11e9-8951-d1d136d4bb67.png">

**Comment by hipstersmoothie** [comment]
BTW, thank you so much for helping maintain GItup! I was worried that it would die since i saw somewhere it wasn't being maintained anymore. 

I really appreciate all the work you guys are doing. Dark mode has been awesome otherwise!

**Comment by lucasderraugh** [comment]
@hipstersmoothie I'm glad we can continue to maintain it. I use it every day and really can't go back to anything else.

I'm going to close this out as it would appear that everything becomes this brown color when your background wallpaper is set to what you gave us. If you don't agree feel free to reopen, but it would appear to me this is system behavior.
