### ISSUE TITLE
Take up full screen on double click of header

### ISSUE THREAD

**Issue by hipstersmoothie** [git-up/GitUp#556]
On most mac apps you can double click the header and it will expand to take up the full screen (not full screen mode). Double clicking again will return the app to it's pre-expanded size

Gitup should do the same.

**Comment by lucasderraugh** [comment]
It would appear that it does have this behavior, but my guess is that the text field in the center is larger than the text and so it's blocking the double click action. If you try double clicking close to the items on the left, you'll see the behavior works as you'd expect.

This would likely be a relatively easy fix. Either the text field should fit to the content or the text field should allow the double click action to pass through. My preference would be the former.

**Comment by johankool** [comment]
It seems to me it already works this way.
