### ISSUE TITLE
Dismiss Quick View when Space key is released.

### ISSUE THREAD

**Issue by vosatom** [git-up/GitUp#557]
Quick View is very similar to native QuickLook found in Finder app. It would be nice to consider feature, that dismisses Quick View after when you stop holding `Space` key in same way as in Finder.

**Comment by johankool** [comment]
Important to note that Finder doesn't dismiss QuickLook for short space presses. This works the same as it does for GitUp now.

**Comment by lucasderraugh** [comment]
I think I'm going to close this out as I don't see how we could implement this unless we somehow had an animation which I think we'd like to avoid. For my reasons stated above I think I'll close this out.
