### ISSUE TITLE
Maybe... Just maybe... rewrite GitUp in Swift?

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#570]
Maybe...
Rewrite GitUp ( only app ) in Swift?
It seems that it will not be so hard, only `Document.m` is big enough ( 3k LoC )...

**Comment by lucasderraugh** [comment]
Why? Seems like an unnecessary change to me. If we were to ever do that I’d want @swisspol approval and I’m going to guess the answer would be no.

**Comment by lolgear** [comment]
@lucasderraugh Because swift has better readability in architectural patterns like nested classes and domains.
Reading boilerplate or throw away error handling ( passing NULLs everywhere is a generic pattern in ObjC, cause "system functions can't fail" ) - typical ObjC evil.
Yes, `nil` and dynamic dispatching with beautiful macOS architecture save time and bring you to finish without hassle, but...

**Comment by lucasderraugh** [comment]
If there’s one thing I hate more than either language, it’s having to interop with the 2. If it’s a leaf node then perhaps we could consider interoping, but we’ll need to talk to libgit2 which C/Swift is kind of a pain.

**Comment by lolgear** [comment]
@lucasderraugh 
One super-feature of ObjC - it barely changes over time ( look at Swift 3 support in latest Xcode ).

**Comment by swisspol** [comment]
There's no reason to rewrite GitUp, or part of it, in another language (unless wanting to introduce new bugs). Current solution has been battle tested for years and works.
