### ISSUE TITLE
diff with HEAD keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by zachvalenta** [git-up/GitUp#606]
So far all other keyboard shortcuts from map view working fine (e.g. `space` to open quick view, `e` to edit message) but `|` to diff with HEAD isn't working.

**Comment by lucasderraugh** [comment]
It’s not a vertical bar, it is a capital i “I”.

**Comment by zachvalenta** [comment]
Aha, gotcha, thought it was the UNIX pipe :)

**Comment by lucasderraugh** [comment]
It’s all good. I’m not sure why “I” makes any sense tbh.
