### ISSUE TITLE
[Bug] Trying to open a repository

### ISSUE THREAD

**Issue by uhlhosting** [git-up/GitUp#609]
I got:

object not found - no match for id (1ae7d3b0d86ae6b53eeea5b93eb94449cbf2e8b7)

Thats is all info seen.

**Comment by lolgear** [comment]
@uhlhosting 
Do you have some stashes?

**Comment by uhlhosting** [comment]
@lolgear yes there are stashes inside.

**Comment by lucasderraugh** [comment]
You don't happen to have shallow cloned your repo? #541 #364

**Comment by uhlhosting** [comment]
@lucasderraugh oww I did...

**Comment by lucasderraugh** [comment]
Going to close this as it is a known issue.
