### ISSUE TITLE
Not staged lines are committed alongside staged lines in the same file

### ISSUE THREAD

**Issue by kominak** [git-up/GitUp#612]
Steps to reproduce:
1. Edit a file, e.g. modify 10 lines
2. Stage just some changes - 5 lines
3. Make a commit

Expected result:
* Staged lines are committed
* Not staged lines are not commited (nor reverted)

Actual result:
* The whole file is committed, including not staged lines

This used to work few releases ago. The bug is present both in the 1.1 release and in commit 78569b8f87f4fb5974c0cedb78449c00b7d69798.

**Comment by lucasderraugh** [comment]
I think you'll need to attach a video of what you're doing. This doesn't occur on any repos I've been using.

**Comment by kominak** [comment]
You are right - with a clean repo it works as expected. The cause for this misbehavior is my pre-commit hook: we process every staged file (regardless of unstaged lines) and in case of any change we just stage the whole file again - including unstaged lines, obviously. My bad. Closing the issue. Thanks :)

**Comment by lucasderraugh** [comment]
Thank you for verifying for me!
