### ISSUE TITLE
Zoom - increase size of everything, or at least make font size configurable

### ISSUE THREAD

**Issue by astubbs** [git-up/GitUp#615]
I'm getting old, have to squint to see the commit details on the map view.

**Comment by douglashill** [comment]
Which parts of the map view you‘d like to see larger? The branch and tag labels, or the little floating view with details of the selected commit, or the lines themselves?

**Comment by natestemen** [comment]
I would love to be able to increase all font size. That said, I didn't try and zoom until I was on the quickview page. So that would be the first vote for me.

**Comment by astubbs** [comment]
Sorry for the slow reply - I'm referring also to the commit message, Sha, author etc on the left hand column. Not just the patch details.
And yes this:
> branch and tag labels, or the little floating view with details of the selected commit
