### ISSUE TITLE
2-3 second pause before showing map view in very large repositories

### ISSUE THREAD

**Issue by tbodt** [git-up/GitUp#62]
I work with a repository with over 100,000 commits. When I switch to some view other than the map view, such as quick view, then switch back, there's a 2-3 second pause before map view reappears. Could be fixed by leaving the map view around when you switch to another view, instead of recreating it.

**Comment by swisspol** [comment]
It's not so much the number of commits but also the complexity of the topology and number of branches and tags, that takes time to compute the graph. And of course it depends on how fast your Mac is.

The Map view is always kept around as part of the document, however it needs to be redrawn when it gets visible again. This is just drawing, not graph computation, which is cached, and only invalidated if the repo has been "touched" in the mean time.

There's no bug here, it's all behaving as expected. You can see where the time is spent by running GitUp from Terminal:

    $ XLFacilityMinLogLevel=1 /Applications/GitUp.app/Contents/MacOS/GitUp
