### ISSUE TITLE
500 error with GitLab Community Edition 12.5.5

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#622]
When i try to do any git manipulation (fetch, pull, push...) it returns the error: `Failed connecting to "origin" remote: unexpected HTTP status code: 500`. If i use SourceTree or Terminal everything goes well. Only with GitUp happens that bug.
Version 1.1.1(1033).

**Comment by lucasderraugh** [comment]
If you issue a pull from the command line on that repo and then try it in GitUp, does that resolve the issue? I’ve seen this before and don’t believe this is anything new.

**Comment by NikKovIos** [comment]
In command line i can do any git command and it exects well. Also in GitUp these changes shows. But it doesn't fix and 500 error still exists.

**Comment by lucasderraugh** [comment]
Can you reclone the repo and see if that works. I can’t think of any changes between 1.1.0 - .1 that would have influenced this. Would love to get to the root of the problem though.

**Comment by NikKovIos** [comment]
I did reclone multiple times. =(

**Comment by lucasderraugh** [comment]
Hmm, well if you want to try checking out the 1.1 code and build and run to see if it works correctly there vs the 1.1.1 tag. Happy to debug if I can get access to something that reproduces the issue.

**Comment by NikKovIos** [comment]
Sorry, its a private repo with NDA.

**Comment by NikKovIos** [comment]
In commit 3973ee4fed2f6acdc87e240fcbc82936447c281c.
GCLiveRepository line 857 in method `performOperationInBackgroundWithReason`. `Error Domain=GCErrorDomain Code=-1 "Failed connecting to "origin" remote: unexpected HTTP status code: 500" UserInfo={NSLocalizedDescription=Failed connecting to "origin" remote: unexpected HTTP status code: 500}`. In log it writes `libgit2 error (-1): unexpected HTTP status code: 500`.

**Comment by NikKovIos** [comment]
@lucasderraugh any news? If you don't have time, please tell how to update libgit2 and i'll try with myself)

**Comment by lucasderraugh** [comment]
@NikKovIos We should update the version of libgit that we have as it is rather old at this point. There are many additions that @swisspol made originally and I'm unfortunately not well versed in all the changes there. I'm not sure that the issue you're facing is necessarily a libgit issue though. I can certainly try my hand at rebasing his changes onto a branch though if you'd like to try it out.

**Comment by NikKovIos** [comment]
@lucasderraugh thnks for the response. Please tell me what to do (if it's not hard ;)). I'll try to help as i can.

**Comment by lucasderraugh** [comment]
I think the easiest way would be seeing if you can create a public repository that reproduces this issue and then I can debug it myself to see if I have the same issues (or anyone else that comes across the issue). Merging the latest release worth of changes into https://github.com/git-up/libgit2 is likely a ton of work. I imagine there are many conflicts (though I haven't tried) that may be difficult to resolve correctly. I think the best step is to try and get a public repo that reproduces the issue so that I and others could try and help you debug on.

**Comment by NikKovIos** [comment]
@lucasderraugh unfortunately i can't create a repo to reproduce it. I think it depends on gitlab version `GitLab Community Edition 12.5.5`. I don't have any own repos with this version.

**Comment by NikKovIos** [comment]
Closed to https://github.com/git-up/GitUp/issues/628
