### ISSUE TITLE
How to install Kaleidoscope as a merge tool? [Question]

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#624]
Please, who know, describe how to set it up. I can't find any manual for this.

**Comment by intiocean** [comment]
I think it's in the preferences?

![image](https://user-images.githubusercontent.com/725843/74847303-32902880-5332-11ea-8f55-6727ec9a022b.png)

**Comment by NikKovIos** [comment]
@intiocean now try to use it and you would find a problem.

**Comment by lucasderraugh** [comment]
I’ll have to install Kaleidoscope to test it out.

**Comment by NikKovIos** [comment]
@lucasderraugh that is the question!

**Comment by intiocean** [comment]
It works for me no problem.

In the diff view click the little gear icon on the top right
![image](https://user-images.githubusercontent.com/725843/74921637-57d27480-53ce-11ea-8ad8-fdf46240f3d5.png)

-> View in Diff tool.

✨🤷🏽‍♂️

**Comment by NikKovIos** [comment]
@intiocean how did you install kaleidoscope?

**Comment by intiocean** [comment]
From the their website just as normal? Not from the mac app store...

Just seen this on their website: 
![image](https://user-images.githubusercontent.com/725843/74928328-928dda00-53d9-11ea-9e1a-423b1bed66fb.png)

My integrations settings
![image](https://user-images.githubusercontent.com/725843/74928185-4e023e80-53d9-11ea-84fe-b1d60e5a6eb5.png)

**Comment by eric-norcross** [comment]
I was finally able to figure this out by running `ksdiff` in terminal and received the message:

    Error locating Kaleidoscope: This version of ksdiff (version 123) is too old to launch the version of Kaleidoscope installed at 
    /Applications/Kaleidoscope.app (version 125)

Apparently the `ksdiff` tool wasn't updated along with Kaleidoscope itself. After removing the `ksdiff` tool (`Kaleidoscope > Integration... > Kaleidoscope Command-line tool > Remove`) and reinstalling it, I was able to use it the GitUp integration again after restarting.

**Comment by lucasderraugh** [comment]
Closing this out as it sounds like there are solutions.
