### ISSUE TITLE
Need improvement: libgit2 update

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#628]
I LOVE this app. In order to use the latest functions and fix some issues we need to update the gitlib2 library.

**Comment by lolgear** [comment]
@NikKovIos 
They still not released 0.99.
In this release annoying [bug](https://github.com/libgit2/libgit2/pull/5275) with stashes fixed.

**Comment by lucasderraugh** [comment]
Good to know that it would fix certain issues. I'll look into what it would take to merge in the latest changes into our fork.

**Comment by lourenci** [comment]
Will this update allow us to sign commits with gpg?

**Comment by lolgear** [comment]
@lucasderraugh 
I suppose that #340 and #191 also could be solved after libgit2 update.

**Comment by lolgear** [comment]
@lucasderraugh 
[Finally released!](https://github.com/libgit2/libgit2/releases/tag/v0.99.0)

**Comment by lolgear** [comment]
@lucasderraugh 
This issue also is really necessary for next release and it requires some attention.

**Comment by lolgear** [comment]
@lucasderraugh 
It seems that some changes in fork are outdated.
Some commits are merged into libgit2, some functions are deprecated, some fixes are unnecessary now.

Could you tell how people could help GitUp with libgit2 update?
I start rebasing existing commits onto latest libgit2, but I can't figure out how to add this rebased branch to GitUp's libgit2 fork.

**Comment by lucasderraugh** [comment]
We have updated to libgit2 1.4.4. All with a whole host of new problems 😅
