### ISSUE TITLE
Cherry-pick does not preserve author

### ISSUE THREAD

**Issue by indeyets** [git-up/GitUp#63]
Whenever I cherry-pick commit authored by someone else GitUp puts my name both in "Committer" and "Author" properties.

Expected result: "Author" field is preserved

**Comment by berkus** [comment]
Vote up :+1:

**Comment by swisspol** [comment]
Git CLI preserves the author indeed.

**Comment by swisspol** [comment]
Should be fixed in 92836493c6d854257099f4b747e2320c09010e5a
