### ISSUE TITLE
Commit View - Cannot Push

### ISSUE THREAD

**Issue by gwsounddsg** [git-up/GitUp#632]
This is more of a feature request. When I'm in the Commit View, after committing I have to go back to the Map View to push. I'd love for the keyboard shortcut to be active in this view. Also, if there was a Commit & Push command, that would be amazing.

Thanks,
GW

**Comment by MrSkwiggs** [comment]
Duplicate of #521

**Comment by lucasderraugh** [comment]
Going to close as a duplicate, we have so many issues to track as it is. I'll make a note of Commit & Push option.
