### ISSUE TITLE
Feature Request: adjust diff and text editor font size

### ISSUE THREAD

**Issue by rodrigoelp** [git-up/GitUp#636]
This feature request is quite specific, I would like to be able to increase the font size (and possibly the font family) used in the diffs panel of the commit view so it is a bit more pleasant to look at my code. Everything else seems pretty good.

**Comment by lucasderraugh** [comment]
Lucky for you this was addressed with #620. I have to wrap up a few things before putting it into the continuous channel for testing, but that will probably happen sometime this weekend. You can try it now by building from source, or if you change GitUp to the continuous release channel in GitUp Preferences, you should see the change by Monday.

Going to close this out as I believe this mostly addresses your issue. If not, feel free to reopen.

**Comment by rodrigoelp** [comment]
Sweet! I will check it out tomorrow :)

**Comment by lucasderraugh** [comment]
@rodrigoelp The changes are in the continuous channel now if you'd like to try them out.
