### ISSUE TITLE
Support other 3rd party diff tools by allowing user to specify a command line?

### ISSUE THREAD

**Issue by r-owen** [git-up/GitUp#64]
I'd like to be able to use BBEdit for 2-way diffs. But there are many other good tools and I doubt you want to add explicit support for all of them. Any chance of support for an arbitrary command string? That should satisfy most tools (though it means the user has to figure some things). SourceTree does this, and copying them might help with documentation (meaning that any info a user finds for how to configure for SourceTree would also work for gitup).

Ideally one could specify a command and arguments separately for 2-way diff and 3-way merge

If there is already a way to hack this in by editing a config file, I'd love to know it.

**Comment by swisspol** [comment]
GitUp can already use the standard Git diff / merge tools (see Preferences), which should work in most cases:
- http://git-scm.com/docs/git-difftool
- http://git-scm.com/docs/git-mergetool
