### ISSUE TITLE
error popup for a repo: database disk image is malformed

### ISSUE THREAD

**Issue by gschueler** [git-up/GitUp#649]
I receive this message every time I open a certain repo: "database disk image is malformed" in a popup alert window.

what is the problem, and what can I do to fix it?

**Comment by gschueler** [comment]
btw, i can dismiss it, and then use the repo normally afaict

**Comment by lucasderraugh** [comment]
Well a way to fix it would be to go into the .git directory and delete the GitUp db. I'm not sure how to determine the exact cause of this error though. It would be good to know though if it goes away after trashing the gitup directory inside your repo though.

**Comment by gschueler** [comment]
thanks, i deleted the .git/co.github.mac/ dir and the problem went away ¯\_(ツ)_/¯

**Comment by lucasderraugh** [comment]
Ya, that’s not a great answer. If I ever get time I’ll have to look into better logging resolution around these types of issues.
