### ISSUE TITLE
FileMerge does not open

### ISSUE THREAD

**Issue by carlbennettnz** [git-up/GitUp#655]
I have FileMerge installed and working. I have FileMerge selected as my external merge tool in GitUp's preferences. When I click the "Resolve in Merge Tool" button, nothing happens.

If I select any other merge tool in preferences, I get an error saying that the tool isn't installed, so GitUp seems to be correctly detecting that FileMerge is available. It's just not opening it.

I'm running Catalina (10.15.3), so I'm suspecting a permissions issue. There's nothing of note in Console though, and it still doesn't work with Full Disk Access enabled.

I'm running GitUp version 1.1.2. Any ideas?

**Comment by lucasderraugh** [comment]
Does the "View in Diff Tool..." option work if you click the gear in the diff view?
I don't think there are any permissions necessary for operating it. The code run is pretty simple for file merge tool, could you try the following in terminal (it's what the app calls into):
`/usr/bin/opendiff filename1 filename2`
If that doesn't work then that would be the issue.

**Comment by carlbennettnz** [comment]
The "View in Diff Tool…" option also did nothing, but running that command pointed me in the right direction.

```
xcode-select: error: tool 'opendiff' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Turns out I had my "active developer directory" set to `/Library/Developer/CommandLineTools` but `opendiff` requires a full Xcode instance. This fixed it for me:

```
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by lucasderraugh** [comment]
Perfect, glad we could resolve the issue.
