### ISSUE TITLE
Trying to open a git repository does nothing and freezes the app

### ISSUE THREAD

**Issue by renanferrari** [git-up/GitUp#656]
Clicking **Open a Git repository...** or **File > Open...** does nothing. Trying again freezes the app for a few seconds.

I'm using **GitUp Version 1.1.2 (1035)** on **macOS Catalina Version 10.15.2**.

![gitup-issue-1](https://user-images.githubusercontent.com/830056/74937908-cb26b700-53cb-11ea-88ed-b75cd2800274.gif)
![gitup-issue-2](https://user-images.githubusercontent.com/830056/74937918-d1b52e80-53cb-11ea-95bb-7481257021f1.gif)

**Comment by lucasderraugh** [comment]
Hmm, can you try building from source? I'm curious if there are any logs you see if you build from source. I'm running 10.15.3 and it doesn't have an issue. You could try clearing user defaults as well to see if that helps.

**Comment by renanferrari** [comment]
I just reinstalled the app and it's working again. Sorry I won't be able to get you some logs.

**Comment by lucasderraugh** [comment]
No worries. Going to close out the issue then.
