### ISSUE TITLE
get commands executed by gitUp

### ISSUE THREAD

**Issue by bmailhe** [git-up/GitUp#659]
Is there a way to get all commands lines executed by gitUp ?

**Comment by lucasderraugh** [comment]
Do you mean commands that GitUp is able to handle?

**Comment by bmailhe** [comment]
no I mean git commands performed by gitup when we do an action in the UI.

**Comment by lucasderraugh** [comment]
There isn’t necessarily a mapping. We use libgit under the hood and a few slightly custom implementations, so if you’re looking for “here’s what to type in the CLI to do the same thing”, we don’t offer that and likely won’t.

**Comment by bmailhe** [comment]
ok I understand, thx

**Comment by lucasderraugh** [comment]
You’re welcome to look at the code we have for each call and how we call into libgit, but I mostly don’t know of a way we could go from libgit to CLI without extending that project.

**Comment by ppo** [comment]
Too bad… then, could displaying the libgit calls be useful to understand what going on under the hood?
