### ISSUE TITLE
Condition failed: "!(byte & (1 << 7))?

### ISSUE THREAD

**Issue by RayTao** [git-up/GitUp#66]
When I use differ, GIComputeHighlightRanges() cause crash
byte is '\xb0' and _logMessage is "Condition failed: "!(byte & (1 << 7))"
can any one help?

**Comment by swisspol** [comment]
Looks like you have a file that contains invalid UTF8:
https://github.com/git-up/GitUp/blob/9e447327c8601e1b086f9b154957b8063585e5a1/GitUpKit/Interface/GIFunctions.m#L49

**Comment by RayTao** [comment]
Fix this bug use unicode:
NSString *unicodeStr = [NSString stringWithCString:deletedBytes encoding:NSUnicodeStringEncoding];
const char* deletedMin = [unicodeStr UTF8String];

Can you support for diffing unicode characters?

**Comment by swisspol** [comment]
This will not work if the text is ASCII or UTF8.

GitUp currently assumes all text is UTF8 and non-UTF8 text is not supported at this time, sorry.

**Comment by RayTao** [comment]
Thanks for you answer
How do you know this not work, you have a test sample?

**Comment by swisspol** [comment]
It cannot work, these are different string encodings: UTF8 text cannot be read using UTF16 encoding.
