### ISSUE TITLE
Add information about total amount of changed lines/files ( deleted, modified, added ) in Diff view.

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#661]
It would be nice to add information about total changes between two commits/branches.
I would like to know total amount of changed files and lines by pressing [i] on commit.

#416

**Comment by lucasderraugh** [comment]
Let’s leave this in the issue already open. Your title is almost identical to what’s asked for in that issue. I can see us doing what GitHub essentially does saying lines added/removed in the diff views, not much else.
