### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by talregev** [git-up/GitUp#662]
Please make Gitup available for windows.
Thank you.

**Comment by lucasderraugh** [comment]
I think there is probably zero chance of this happening. Somebody would pretty much have to rewrite everything for that environment and nobody from the original incarnation wrote Windows stuff.

I’ll leave it open though for the lucky soul that wants to write an entire git client for Windows 😅

**Comment by talregev** [comment]
Thank you for leaving it open!
I hope we find this soul very quickly 😀

**Comment by lolgear** [comment]
@lucasderraugh Actually, Catalyst expands UIKit on macOS... Guess, what Apple could introduce in this year...

**Comment by lucasderraugh** [comment]
There is 0 chance Catalyst will come to Windows.

**Comment by talregev** [comment]
The lucky soul (me) that want to rewrite gitup for windows, I consulted with my colleagues how to do it.
We choose (for meantime) to do it with c# and wpf.
And we thought which best control will fit for the main window visualization.
We thinking about for simple start to take tree view control and change it template.

Any Idea how I can re write the gitup for easy way (any other languages and libraries are welcome).

Thank you again for leaving it open 🙂

**Comment by lucasderraugh** [comment]
Honestly, the only code that can really be shared is from libgit2 (the underlying C library). The rest is in Obj-C which doesn't really have great Windows support. I don't have any Windows programming experience so my suggestions beyond the fact that you could use libgit2 is about as far as I can send you. The graph visualization is all done using CoreGraphics calls (custom drawing) and that's an Apple platform thing.

**Comment by matthewhively** [comment]
It would really be fantastic if this were possible.

**Comment by ehrenmann1977** [comment]
I need it also under windows, i don't suggest you write every thing from scratch but compile it under windows, please try using cocotron.

**Comment by lucasderraugh** [comment]
Cocotron is not actively maintained and has no chance of compiling the current project.

I'm going to close out this ticket as it is not going to share the same codebase until Apple APIs work on Windows.

When that day comes feel free to reopen.

**Comment by talregev** [comment]
That ok, thanks for leaving this issue open for long time.
