### ISSUE TITLE
Branches aren't drawn after update the repo

### ISSUE THREAD

**Issue by jcmoraisjr** [git-up/GitUp#663]
HI, using GitUp 1.1.2 (1035) here. Every now and then the Map has some empty area. The lines stop one "page" (`fn+down`) from the top:

<img width="670" alt="above" src="https://user-images.githubusercontent.com/1457820/77489952-4d195e00-6e18-11ea-84ac-94c47e83b6c8.png">

... and continue two "pages" (`fn+down`) below:

<img width="661" alt="below" src="https://user-images.githubusercontent.com/1457820/77490007-70440d80-6e18-11ea-9aef-ecede8ff931d.png">

I can reproduce this a couple of times per day but I cannot describe a way it will always happen, sorry. A go bottom (`cmd+down`) followed by a go top (`cmd+up`) redraw the missing lines.

**Comment by lucasderraugh** [comment]
Hmm, I have been unable to reproduce this in my day-to-day usage. If you have a repo that reproduces for you, feel free to share it and I can try to reproduce. Not sure of a great way to debug this otherwise.

**Comment by lapfelix** [comment]
This happens to me regularly but I wouldn't know how to reproduce it reliably

**Comment by MrSkwiggs** [comment]
Can attest, happens to me almost daily, but unsure about reproduction steps

**Comment by jcmoraisjr** [comment]
> Duplicate of #602

Great, closing this one.

**Comment by jcmoraisjr** [comment]
> free to share it and I can try to reproduce

Here is my repo: https://github.com/jcmoraisjr/haproxy-ingress
