### ISSUE TITLE
[FR] A reset-like option

### ISSUE THREAD

**Issue by jcmoraisjr** [git-up/GitUp#664]
Hi there, is there a way to do a `git reset [--hard] <commit>` from within GitUp? Delete the commit doesn't sound to be an option here - I need that same commit in the other branches and I sometimes need also the changes that was in that commit in the staging or working area.

**Comment by lucasderraugh** [comment]
I think what you're looking for is this:
<img width="401" alt="Screen Shot 2020-03-24 at 7 18 45 PM" src="https://user-images.githubusercontent.com/714282/77494900-53054400-6e04-11ea-8262-0ebe462c492e.png">
It will effectively move the branch you're currently on to target whatever commit you reset to.
Please let me know if this is not what you had in mind.

**Comment by jcmoraisjr** [comment]
Hi, thank you so much! Yes this is exactly what I was looking for when I need a `reset --hard`, which is about 80% of the time. Other 10% I think I can do using `Rewrite... W`.

One more question - perhaps you have something like `reset` without `--hard`, which will leave my working area with exactly the same files with the same content. This is how rewrite works but I think, when using rewrite, I cannot move back to Map `Cmd+1`, Commit `Cmd+2` or Stashes `Cmd+3` views, and I cannot also move two or more commits.

**Comment by lucasderraugh** [comment]
I don't think we have a way of doing `--soft` for example. If I had branch A and B and checked out on B, I can't do a `--soft` onto A. The closest would be stashing, set tip, then unstash, but that leaves reverting the commit and placing in the staging area. I'm not sure whether we have a way of doing this. I'm going to close out this particular issue as I think your original question has been addressed. If you have a specific request, please look in the backlog to see if there is anything matching exactly what you're looking for. If not, make a request with what exactly you want to accomplish. Thanks!
