### ISSUE TITLE
Command + Enter to commit

### ISSUE THREAD

**Issue by jpadilla** [git-up/GitUp#67]
It'd be great to be able to do `cmd + enter` after writing commit message to actually commit.

**Comment by jcowgar** [comment]
Opt+Enter does the trick. It's odd, yes, but there was discussion on this previously. I do not remember where, sorry.

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/wiki/Using-GitUp-Advanced-Commit-View#keyboard-shortcuts.

IIRC it's because cmd+enter would not work in modal dialogs due to a limitation in Cocoa. Opt+Enter works everywhere though.

**Comment by kud** [comment]
Related https://github.com/git-up/GitUp/issues/550

and thanks for the trick!

**Comment by dankimio** [comment]
It was very unclear to me that `Opt + Enter` is the shortcut for 'Commit' because there is no menu item for it. Perhaps it could be added for clarity.

**Comment by hftf** [comment]
See also #431

**Comment by lucasderraugh** [comment]
We're accepting PRs once again and although I don't have unlimited bandwidth, definitely trying to push changes through. If someone wants to work on adding a menu item for better visibility, a PR would be accepted assuming correctly implemented.
