### ISSUE TITLE
I can't open the application.

### ISSUE THREAD

**Issue by iwamoto65** [git-up/GitUp#670]
When I try to open an application, I get a warning to update the software.
Is there a way to update it?
Mac OS is the latest version 12.15.0

**Comment by lucasderraugh** [comment]
I assume you’re on 10.15.4 if you’re on latest. GitUp should update automatically to stable or continuous release channels.

**Comment by duhrich** [comment]
same issue here, it just doesn't open `10.15.4`
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1461692/79997664-0b132480-8477-11ea-85a7-1cbc1846b3c8.png">

**Comment by duhrich** [comment]
Probably not an option for all (most?) but I cloned and built myself, and I'm good to go.

**Comment by lucasderraugh** [comment]
#617 lists a workaround for this. It is a known issue that I'll try to address for the next release.
