### ISSUE TITLE
"You are now on branch ..." popup in way

### ISSUE THREAD

**Issue by dbr** [git-up/GitUp#677]
Whenever I open a repository (e.g via the `gitup` command or launching the .app normally and opening a repo via "File" menu), there is a overlay-banner-thing:

![](https://user-images.githubusercontent.com/509/81030661-b8028e00-8ec8-11ea-970c-769180013966.png)

1. This part is not too important, but: it's not clear if that's intended to always popup - the "now on" wording sounds like it was intended to appear when changing branch?
2. The popup stays for a few seconds, and gets in the way of quickly clicking the "stage file/line" button

**Comment by dbr** [comment]
Ah, sorry, this is essentially a duplicate of #554!

**Comment by lucasderraugh** [comment]
No worries. It’s something that is starting to annoy me as well so I’ll consider some fixes for next release. Thanks!
