### ISSUE TITLE
Cannot read diff highlight colors too close

### ISSUE THREAD

**Issue by Secoia800** [git-up/GitUp#681]

**Comment by Secoia800** [comment]
The colors of text in diff tool are too close making reading diffs in files very difficult. Try putting in a choice of nigh light diff colors

**Comment by lucasderraugh** [comment]
Any colors you propose?

**Comment by lucasderraugh** [comment]
If you have a proposed color that works for you, feel free to reopen. Closing for now to reduce issue count.
