### ISSUE TITLE
Shows files as deleted when they are not

### ISSUE THREAD

**Issue by max5it** [git-up/GitUp#682]
`git status` shows `nothing to commit, working tree clean`, git-cola shows nothing, but gitup 1.1.3 (1036) shows two deleted files. macOS 10.15.5

<img width="429" alt="Screen Shot 2020-06-04 at 4 59 10 PM" src="https://user-images.githubusercontent.com/5707198/83761327-3a789c00-a687-11ea-96d0-725f7151d7f7.png">

**Comment by lucasderraugh** [comment]
@max5it Is this reproducible in some way? Would be nice to be able to debug this on my end.

**Comment by max5it** [comment]
@lucasderraugh I can reproduce this - this is permanent. Unfortunately, it happens in a private repo. If I can check something by myself, please let me know.

**Comment by swisspol** [comment]
This is a case sensitivity issue: you have these 2 files with different casing on disk compared to what’s stored inside Git trees. Git CLI  and other tools silently ignore the problem but GitUp intentionally doesn’t not.

**Comment by swisspol** [comment]
Actually it’s more nuanced than that: these files are duplicated in your Git trees. See #117.
