### ISSUE TITLE
Apple Universal App support (arm64)

### ISSUE THREAD

**Issue by lucasderraugh** [git-up/GitUp#693]
This issue tracks progress with arm64. So far I've done a preliminary sweep and there are dependencies we have that need to be rebuilt. This will track which dependencies have been successfully rebuild using macOS arm64.

- [x] libmbedtls
- [x] libgit2
- [x] libsqlite3
- [x] libssh2
- [x] libssl (openssl support needs to merge in before we get this and ssh working: https://github.com/openssl/openssl/pull/12369)
- [x] Sparkle

There are other things that need to be built, but these are the dependencies that are mostly out of our immediate control. I'll update this issue as time goes on.

**Comment by MaddTheSane** [comment]
Sparkle should be updated to arm64. Or at least buildable.

**Comment by lucasderraugh** [comment]
Done in 1.2 release.
