### ISSUE TITLE
Update Sparkle to a less vulnerable version

### ISSUE THREAD

**Issue by pedrogalan** [git-up/GitUp#694]
Apparently, [the current version of Sparkle included in GitUp has a man-in-the-middle vulnerability](https://sparkle-project.org/documentation/security/). I think this should be fixed by upgrading to a most recent version of Sparkle.

**Comment by lucasderraugh** [comment]
Thanks for bringing this to my attention. We'll update for the next release.

**Comment by lucasderraugh** [comment]
I believe we were actually safe on this one, though we will be updating Sparkle regardless in a coming release. See #48
