### ISSUE TITLE
Should adding be green rather than blue?

### ISSUE THREAD

**Issue by jasonhan-vassar** [git-up/GitUp#703]
Hi, it seems that adding events are colored blue instead of green, and green is instead used for merges. Given that typically (both in GitHub/GitUp), inserts are green and removals are red, would it make more sense to make adds green and removals red? This would also mean making merges blue.

Sorry if it's a silly change, but I would like to hear your guys' feedback and/or rationale. Since this is more of a personal gripe rather than a feature request, please let me know which files in the source code I should look into to change the colors myself — I am willing to change it on my own GitUp builds. Thanks!

**Comment by lucasderraugh** [comment]
Can you attach a photo of what you mean by this? If you're referring to the changed files colors blue represents additions, red is removals, green is modifications, and orange is merge conflicts.

**Comment by jasonhan-vassar** [comment]
Sorry if I wasn’t being clear, I was essentially asking to switch the colors blue and green. I was wondering if adding would make more sense as green as it is usually that way in other Git-related programs.

**Comment by lucasderraugh** [comment]
I think GitHub uses green for additions on the diffs (which we use as well), but there isn't a color associated with adding a new file for the first time. Do you have another Git program that uses this styling for their list of file changes?

**Comment by jasonhan-vassar** [comment]
One program that uses green is Fork:
<img width="1373" alt="Screen Shot 2020-09-22 at 3 14 27 PM" src="https://user-images.githubusercontent.com/34594853/93927188-873fbb80-fce6-11ea-94d1-1a6de84b3998.png">

Another is the GitHub Desktop client:
<img width="971" alt="Screen Shot 2020-09-22 at 3 23 17 PM" src="https://user-images.githubusercontent.com/34594853/93927947-92471b80-fce7-11ea-803a-e1bd13e8063b.png">

Interestingly enough, both those clients also use yellow for modifications.

Could you please add a way to customize the colors in an Appearance preference tab maybe? If not, could you let me know where to look to modify these colors myself?

**Comment by lucasderraugh** [comment]
We really don't want to allow too much appearance customization but I think green for additions is probably the most logical.

**Comment by lucasderraugh** [comment]
Closing as this went into the 1.2 release. Thanks @jasonhan-vassar!
