### ISSUE TITLE
Dark mode icons are almost invisible

### ISSUE THREAD

**Issue by codymikol** [git-up/GitUp#708]
The current icon set for gitup is almost impossible to see in dark mode

![image](https://user-images.githubusercontent.com/13606342/97021972-8d150080-1521-11eb-857a-d0a84c697664.png)

**Comment by codymikol** [comment]
I'm sorry its monday, this is not even gitup. I need more coffee

**Comment by lucasderraugh** [comment]
Haha, saw the issue come through my inbox and was definitely confused 😅

**Comment by codymikol** [comment]
Only this afternoon did I realize that it is in fact Friday and not Monday. It's been quite a day, thanks for understanding 😅.
