### ISSUE TITLE
Any plans for a Windows version?

### ISSUE THREAD

**Issue by mrchief** [git-up/GitUp#71]
With Git being the _"the best SCM with the worst user interface (yes CLI counts as user interface)"_,  GitUp is like a prayer answered!!

However, for those who haven't taken a crunch out of the fruit of love, any plans to release a Windows version?

I'd love to contribute to make this a reality!

**Comment by swisspol** [comment]
No, this would require a full rewrite as GitUp was entirely built and designed for OS X.

**Comment by mikeboutch** [comment]
A Linux version at least?
