### ISSUE TITLE
Feature request: “universal” binary for better performance on Apple Silicon Macs

### ISSUE THREAD

**Issue by aviflax** [git-up/GitUp#712]
I guess I could build the project myself, but I’m not proficient with Xcode and then I wouldn’t get updates. So I’d prefer to use an official build if possible.

Thank you!

**Comment by lucasderraugh** [comment]
This is a dupe of #693. I openssl doesn't have a distribution that includes the correct configuration yet but perhaps I'll just make a fork that has the configuration.

**Comment by aviflax** [comment]
Ah, yes, that it is!

I'd searched for "ARM" and "M1" and "Apple Silicon" but not for "universal" 🤦

Thanks!
