### ISSUE TITLE
Right edge of 'stashes view' button is clipped on Big Sur

### ISSUE THREAD

**Issue by nealyoung** [git-up/GitUp#718]
It looks like the right side of this button's background is clipped when it's selected/highlighted:
<img width="209" alt="Screen Shot 2020-11-26 at 12 07 38 PM" src="https://user-images.githubusercontent.com/1132493/100388679-28e1d280-2fe0-11eb-9cd3-7ae2d4e47c80.png">

**Comment by lucasderraugh** [comment]
We'll have a Big Sur continuous update out next week. I'll make sure this is addressed in there.

**Comment by zwaldowski** [comment]
This was already sneakily in #689. 🤫

**Comment by lucasderraugh** [comment]
This should be resolved in 1.2 release available now through the continuous release channel.
