### ISSUE TITLE
Map/Commit/Stashes segmented control not showing up in toolbar in Big Sur

### ISSUE THREAD

**Issue by mdznr** [git-up/GitUp#722]
The toolbar is missing the segmented control it use to display.

Workaround: View > Map Commit Stashes menu items

<img width="1112" alt="Screen Shot 2020-12-03 at 11 48 53 AM" src="https://user-images.githubusercontent.com/963948/101060952-fa26a780-355d-11eb-8ffd-6e827ccc3a97.png">

**Comment by lucasderraugh** [comment]
That's weird, not an issue I've hit. We do have many Big Sur changes coming though on the continuous channel probably next week that should address a variety of Big Sur style changes.

**Comment by lucasderraugh** [comment]
This should be resolved in the 1.2 release that's now in the continuous release channel.

**Comment by mdznr** [comment]
Looks like it’s been fixed. Thank you!
