### ISSUE TITLE
Update app icon for Big Sur

### ISSUE THREAD

**Issue by mdznr** [git-up/GitUp#723]
The GitUp app icon is already a rounded rectangle. Making a version where it’s not angled will make it fit better in the dock.

<img width="175" alt="Screen Shot 2020-12-03 at 11 53 25 AM" src="https://user-images.githubusercontent.com/963948/101061137-28a48280-355e-11eb-9574-7ef93debf78e.png">

**Comment by lucasderraugh** [comment]
Totally open to anyone providing assets that do this. I can probably get around to it before the next release.

**Comment by mdznr** [comment]
@lucasderraugh Thanks for the quick reply!

**Comment by mdznr** [comment]
Put something together quickly. What do you think about this?

<img width="767" alt="GitUp in Dock Screen Shot" src="https://user-images.githubusercontent.com/963948/101070447-6064f780-3569-11eb-97ea-d4618bf0cca7.png">

[AppIcon.iconset.zip](https://github.com/git-up/GitUp/files/5638104/AppIcon.iconset.zip)
[GitUp Big Sur App Icon.sketch.zip](https://github.com/git-up/GitUp/files/5638105/GitUp.Big.Sur.App.Icon.sketch.zip)

**Comment by lucasderraugh** [comment]
Looks good to me for a Big Sur-ification. If you want to make a PR that replaces the icon assets I'd be happy to merge it in. If not, I'll get to it at some point 😄

**Comment by lucasderraugh** [comment]
Closing as we integrated this into our release for 1.2. Thanks for the icon @mdznr!
