### ISSUE TITLE
How to use self-signed SSL certificate?

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#730]
Our brave colleagues are on the guard of security and got an wonderful idea to use self-signed certificate. After this i get next error:

![image](https://user-images.githubusercontent.com/16647690/102786086-fe512280-43af-11eb-9b0e-e827da678a45.png)

In terminal it tells: `fatal: unable to access 'http://...': SSL certificate problem: self signed certificate in certificate chain`

Any suggestions?

**Comment by lucasderraugh** [comment]
I'm not familiar enough with how SSL works or self-signed certs in the app (or in general). Is there an easy way that you know of to debug this on my end?

**Comment by NikKovIos** [comment]
Write me in telegram please @nikekov

**Comment by NikKovIos** [comment]
I solved this! Thx https://github.com/libgit2/libgit2/issues/4878#issuecomment-436240600

Go to keychain and set `trust` to certificate 
![image](https://user-images.githubusercontent.com/16647690/103079936-e662e400-45e5-11eb-950f-0a3d54d67233.png)
