### ISSUE TITLE
Feature: Control how much space is given for branch names at Map view

### ISSUE THREAD

**Issue by oleksii-horishnii** [git-up/GitUp#737]
Having a project with long branch names, it doesn't help that branch names getting eclipsed or not eclipsed, I just want to see full names (because parts before eclipses are the same for many branches). 

To do that, the point at which git tree starts should be allowed to be dragged up or down.

**Comment by lucasderraugh** [comment]
Thanks for filing. It's really an existing bug that we have where we don't calculate the amount of offset needed along the top. #94
