### ISSUE TITLE
GitHub app URL scheme

### ISSUE THREAD

**Issue by jankeesvw** [git-up/GitUp#74]
On GitHub.com you find link with "Open this in GitHub Desktop" they use an URL-Scheme like: `github-mac://openRepo/https://github.com/project/reponame?branch=branch-name`

Would be great if GitUp would also support these.

**Comment by swisspol** [comment]
How would this work if both GitHub and GitUp are installed?

**Comment by JanX2** [comment]
SourceTree has a checkbox that sets it to be the designated app for that URL scheme. At least until the GitHub app claims it for itself once again. ;)

**Comment by swisspol** [comment]
Follow up in PR.
