### ISSUE TITLE
Bug: Pre-commit fails in latest update (v1.2)

### ISSUE THREAD

**Issue by alxsavard** [git-up/GitUp#740]
Hi!

Long time user here! Thanks for keeping this project alive! 

The latest update seems to have broken something and prevents my pre-commit hooks to run properly. I don't have a lot of information about this unfortunately. The message I receive is this one, but it's a npm generic message and doesn't have anything to do with GitUp specifically. 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/11441711/106186498-5da20f80-6172-11eb-9c1a-5b2ba16d2914.png">

The command line works fine for the same commit. I tried reverting to the previous version and all is working well, but then the app auto-updates to the new version and it keeps breaking again. 

I'm not a mac dev, but if I can do anything to help let me know!

(I'm on the latest Big Sur on an intel mbp if that's any help)

**Comment by lucasderraugh** [comment]
@alxsavard Thanks, and sorry for breaking it in the latest release. Are you able to compile this project, if so I have some changes I'd like to test. I have a different change I'll try for #736 and I'll give you the output of that once I make the build. I'll try to implement #738 for the next release. My work has been a bit hectic this week but I'll try to get you that build soon.

**Comment by alxsavard** [comment]
Yeah I can try to build it this weekend and hopefully get more logs or test whatever you'd need me to.

**Comment by lucasderraugh** [comment]
Ya, unfortunately my best for now is to say you can download the old app in the meantime and don't quit it.

**Comment by lucasderraugh** [comment]
Alright, I whipped up a new build that reverts the change I believe might break your scenario. You'll have to open it with System Preferences > Security > General Tab as it's not notarized. Let me know if that build works and if so I'll revert that change in 1.2.1.
[GitUp.zip](https://github.com/git-up/GitUp/files/5889618/GitUp.zip)

**Comment by alxsavard** [comment]
The build you gave me didn't seem to resolve the issue. Thanks for trying though! I'll try to build this w.e. when I get a change and hopefully I can see what's going on.

**Comment by lolgear** [comment]
@lucasderraugh Will you update libgit2 in next release?

**Comment by lucasderraugh** [comment]
Is it related to this issue @lolgear? It's probably something to do for 1.3

**Comment by lolgear** [comment]
@lucasderraugh It is related to the most annoying issue with corrupted stashes... Not sure about this issue. It could be.

**Comment by lucasderraugh** [comment]
@alxsavard Btw, we pushed 1.3.3 out to the continuous channel and it bumps libgit2 to a newer version. Let me know if you're even still using GitUp and figured out anything more 😅
