### ISSUE TITLE
Add clone option to startup menu

### ISSUE THREAD

**Issue by 11rchitwood** [git-up/GitUp#743]
It would be great to be able to clone a repository from GitHub, GitLab, Bitbucket, or any other URL right from the start menu.

**Comment by lucasderraugh** [comment]
It's already an option in the menu bar, are you just saying you'd like there to be a button on the welcome window?

**Comment by 11rchitwood** [comment]
I see that now! Apologies. But yes I was just looking for a way to do so at the welcome window. But it's not really necessary.

**Comment by lucasderraugh** [comment]
Sounds good. I think I'll close the ticket out if you don't mind.
