### ISSUE TITLE
GitUp hangs with private GitHub orgs when using HTTPS

### ISSUE THREAD

**Issue by stevetarver** [git-up/GitUp#75]
Love the GitUp, thank you very much. Want to introduce it at work where we use a private org to store many of our repos. I have zero problems/challenges with GitUp on my public repos but cannot interact with repos in our private org. 

When I try to push, I am prompted by the OSX keychain helper for user/pass and then it sits in a Remote operation in progress state.

**Comment by swisspol** [comment]
Try running GitUp from Terminal in verbose mode and copy-paste the log output:

    $ XLFacilityMinLogLevel=1 /Applications/GitUp.app/Contents/MacOS/GitUp

**Comment by crubier** [comment]
Same problem here...

```
00:00:01.767 [VERBOSE  ]> App is up-to-date at version 1012 on channel 'stable'
00:00:11.940 [VERBOSE  ]> History loaded for "/Users/xxx/yyy/zzz/.git" (38 commits scanned in 0.002 seconds)
00:00:11.975 [VERBOSE  ]> Graph regenerated for "/Users/xxx/yyy/zzz/.git" in 0.000 seconds
00:00:12.138 [VERBOSE  ]> Commit database for "/Users/xxx/yyy/zzz/.git" updated in 0.000 seconds (0 added, 0 removed)
00:00:18.883 [VERBOSE  ]> Skipping Keychain lookup for repeated authentication failures
Terminated: 15
```

**Comment by swisspol** [comment]
What's the *exact* URL of the private repo as specified in the Git config, what is the authentication scheme, and where are the credentials stored?

**Comment by swisspol** [comment]
See https://github.com/git-up/GitUp/blob/bbbc296908507eb3f6c5898b3850518450dcb19b/GitUp/Application/AppDelegate.m#L676 and https://github.com/git-up/GitUp/blob/bbbc296908507eb3f6c5898b3850518450dcb19b/GitUp/Application/AppDelegate.m#L95.

**Comment by crubier** [comment]
The exact URL as specified in the git config is https://github.com/Sterblue/Vision.git It is a private repository that belongs to an organisation I created.

I use two-factor authentication on Github, so when the GitUp user name / password window pops up, I fill it with my user name and a personal access token issued by Github instead of my password. I have no trouble with the same authentication scheme for my personal repositories.

I do not know where the credentials are stored, GitUp asked me for it initially, so I supposed they are stored at the default location defined for GitUp.

**Comment by swisspol** [comment]
Can you provide the entire log when running gitup from Terminal?

**Comment by crubier** [comment]
I am sorry to say that that was it.

Using `XLFacilityMinLogLevel=1`, The log was exactly the one above. It ends abruptly by termination of the program because as said in the first message, GitUp stays in the "Remote operation in progress" state forever (or at least more than 15minutes).

**Comment by swisspol** [comment]
I personally used private GitHub orgs with GitUp without problems but I'm using SSH, not HTTPS. You might wanna do this in the mean time.

To debug this further, one would need to build and run GitUp locally, break at https://github.com/git-up/GitUp/blob/bbbc296908507eb3f6c5898b3850518450dcb19b/GitUp/Application/AppDelegate.m#L69 and understand why the authentication window is not coming on screen.

**Comment by stevetarver** [comment]
Amazingly quick response :)
For me, the log is

```
$ XLFacilityMinLogLevel=1 /Applications/GitUp.app/Contents/MacOS/GitUp
2016-03-11 16:05:45.900 GitUp[33498:5122392] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8a0f, name = 'co.gitup.mac'
See /usr/include/servers/bootstrap_defs.h for the error codes.
00:00:00.093 [ERROR    ]> Failed creating message port for tool
00:00:00.776 [VERBOSE  ]> App is up-to-date at version 1012 on channel 'stable'
```
I click the pull button and get "GitUp wants to use your confidential information stored in "github.com" in your keychain."

Status bar shows "Remote operation in progress - Please wait..." for a pretty long time before I force quit GitUp.

In GitUp -> Repository -> Edit Configuration... `remote.origin.url = https://github.com/CenturyLinkCloud/ds-canary.git`

I am using HTTPS

I used KeyChain access to delete all github entries, restarted GitUp, and entered creds exactly as I do in the GitHub sign in page - same behavior as above.

**Comment by swisspol** [comment]
Well, at least there's a pattern... Can you check the Console app for any messages from the OS itself that would be relevant?

**Comment by stevetarver** [comment]
Nothing relevant. (meaning /var/log/system.log added no entries added except a periodic screenhero recv)

**Comment by crubier** [comment]
I confirm the problem disappears when using SSH.

**Comment by swisspol** [comment]
Do you both use MFA?

**Comment by crubier** [comment]
I do, what about you @stevetarver ?

**Comment by stevetarver** [comment]
user/pass stored in the OSX keychain with GitHub Keychain helper

**Comment by swisspol** [comment]
But do you use MFA?

**Comment by stevetarver** [comment]
I do not use Multi-Factor Authentication with GitUp. I do have a personal access token exported into my bash env for homebrew <- don't think that is relevant, but for completeness.

**Comment by swisspol** [comment]
Sorry, I don't understand. Do you have FMA enabled on your _GitHub_ account?

**Comment by stevetarver** [comment]
swisspol - sorry for my lack of clarity - I do appreciate your attention to this issue. I do not have access to the GitHub organization settings so I cannot verify that the org settings do not have 2FA enabled.

I have never had to enter anything but my user/pass for push/pull on repos I have access to. Can I infer that MFA is not enabled because of this?

**Comment by swisspol** [comment]
FYI this is GitHub MFA and it is set per user account, not per org: https://help.github.com/articles/about-two-factor-authentication, so I assume you don't have it.

**Comment by stevetarver** [comment]
Thanks for the clarification, verified 2FA is off for that account.

**Comment by weissazool** [comment]
I began experiencing this same issue when my organization asked me to switch to using 2FA.

**Comment by weissazool** [comment]
Was able to resolve using a workaround similar to what was described in #104. 

I checked my Keychain and removed the Internet password entry that was using my password, rather than the personal token. SourceTree had been able to generate one using the token, so I just added GitUp to access control to that key.

**Comment by swisspol** [comment]
So maybe the bug is that you need to have 2 entries in the keychain for the password for that repo: the old password and the personal token. If GitUp ends up fetching the first one, the UI hangs, but the 2nd one works.

**Comment by steventarver** [comment]
I was able to resolve this by deleting all KeyChain Internet Password entries and creating a single one using my GitHub user id and password. Not sure if the problem was that the keychain item was using my email before, or that there was more than one keychain item.

All working now, so I am back the GitUp goodness.

**Comment by gihrig** [comment]
@stevetarver's tip worked for me, but only when I entered the name github.com/mac in the key chain entry. Just github.com resulted in GitUp hanging on push as described in the OP.

Keychain > info ('i' button)
Name: github.com/mac
Kind: Internet password
Account: (my email address)
Where: https://github.com
Comments: (blank)

OS X 10.11.4

**Comment by gihrig** [comment]
I have another machine (also OS X 10.11.4) that had this same problem where the above fix (delete and recreate keychain entries) did not work.

The solution there was to delete all github entries (there were several) from ~.ssh/known_hosts.
There were also many, many entries with a hash only, no domain. I deleted those also.

Now GitUp can push to origin as expected.

**Comment by swisspol** [comment]
Duo of #475
