### ISSUE TITLE
I need "Reverse Hunk" Button like SourceTree.

### ISSUE THREAD

**Issue by LittleWat** [git-up/GitUp#755]
I feel "Reverse Hunk" Button really useful in SourceTree.

<img width="2048" alt="スクリーンショット 2021-05-12 13 47 36" src="https://user-images.githubusercontent.com/8979377/117919961-faa34580-b328-11eb-88b0-f4f212e5a5dd.png">

I love the beautiful UI of GitUp more than SourceTree.

Do you have a plan to implement "Reverse Hunk" Button?

**Comment by lucasderraugh** [comment]
Yes this is the same as #413. Would be a great feature to add.
