### ISSUE TITLE
Using 2FA on Github

### ISSUE THREAD

**Issue by sjemmett** [git-up/GitUp#762]
I have 2FA on Github.  When I try to do a push from Gitup to my repository on Github, I get asked for username/password.  I enter my username and the token from Authy - The request gets rejected.  I enter my username and password - the request gets rejected.

I have to revert to Github desktop in order to do the push.

Is there something I'm missing on doing the authentication from Gitup?

**Comment by lucasderraugh** [comment]
You need to setup SSH keys which will bypass the auth challenge you'd get with HTTPS.

**Comment by jeremy-w** [comment]
HTTPS works too, using a PAT: https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication#authenticating-on-the-command-line-using-https
