### ISSUE TITLE
The logging system is outdated

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#765]
We have to update logging facility to os_log, because it is inconvenient to hook to logs.
This system also uses sqlite3 to gather logs, but at modern OSes it is not required anymore ( everything is done by os_log ).

**Comment by lolgear** [comment]
Yes, os_log is available at 10.12 and higher.
And it is ok to update minimum deployment target. ( 10.12 is pretty ancient ).

**Comment by lolgear** [comment]
Actually, deployment target has been updated to 10.10 several ( 3 years ) ago.
We can safely update deployment target to 10.12 or 10.13 nowadays.

**Comment by lucasderraugh** [comment]
I agree, I'll bump to 10.13 in the next update.

**Comment by lolgear** [comment]
Duplicate of #815

**Comment by lucasderraugh** [comment]
Addressed in 1.3.3.
