### ISSUE TITLE
Failed connecting to "origin" remote: SSH could not execute request: Timed out waiting on socket

### ISSUE THREAD

**Issue by BabaSalley** [git-up/GitUp#766]
Hello there,
I have been using this excellent tool for nearly two years.
As of today, I am getting: Failed connecting to "origin" remote: SSH could not execute request: Timed out waiting on socket whenever I try to pull or fetch.
Using git pull / git fetch in command line mode works. Restarting Gitup or the Mac doesn't help.
I did not change ssh key or update my OS so I do not know why all of a sudden this happened.
Any ideas I can try?
Thanks in advance!

**Comment by lucasderraugh** [comment]
I'm not sure what's wrong here, but seeing how re-generating the keys fixed it for @ruslankmlv, I'm going to close this out. @BabaSalley if you feel that you can't resolve it by doing this then feel free to reopen.
