### ISSUE TITLE
[Feature Request] Disable autoupdate

### ISSUE THREAD

**Issue by spartanhooah** [git-up/GitUp#773]
It would be nice to be able to disable the autoupdate checker for environments which require manual approval of new versions of software. That way we wouldn't get the "Autoupdate wants to make changes" dialog that users without admin access cannot do anything with.

**Comment by lucasderraugh** [comment]
This will be addressed in the 1.3 release.

**Comment by spartanhooah** [comment]
Fantastic, thank you!

**Comment by lucasderraugh** [comment]
Going to close this out fixed. It's currently in the continuous channel. We'll probably release this to the stable channel around November 29th.
