### ISSUE TITLE
GUI Tool not working in External Diff/Merge

### ISSUE THREAD

**Issue by andreineculau** [git-up/GitUp#78]
Error message:

```
Git diff tool requires both 'diff.tool' (or 'diff.guitool') and 'difftool.<tool>.cmd' to be defined in your Git configuration.
```

Although everything is fine with my `~/.gitconfig`. But you expect this configuration to be in the repo's local configuration `./.git/config` only

**Comment by swisspol** [comment]
It's not possible to see what's wrong unless you provide the content of both Git configs.

**Comment by andreineculau** [comment]
Yes, it is. I just told you what the problem is: gitup does the equivalent
of `git config --local diff.tool` instead of `git config --global diff.tool`

On Sun, Mar 13, 2016 at 12:17 AM, Pierre-Olivier Latour <
notifications@github.com> wrote:

> It's not possible to see what's wrong unless you provide the content of
> both Git configs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/git-up/GitUp/issues/78#issuecomment-195826173>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by swisspol** [comment]
FYI it wasn't clear at all in your issue description that "you" refers to GitUp. In any case, IIRC GitUp uses libgit2 config APIs that read from all configs: https://github.com/git-up/GitUp/blob/2bce9778bb46358240d0cdcada61914a83a5952c/GitUpKit/Core/GCRepository%2BConfig.m#L93.

**Comment by swisspol** [comment]
BTW the [configuration editor](https://github.com/git-up/GitUp/wiki/Using-GitUp-Configuration-Editor) will confirm that GitUp can see all your Git settings.

**Comment by andreineculau** [comment]
And I confirm that the configuration editor does not see any other
configuration than the local configuration.

On Sun, Mar 13, 2016 at 1:25 AM, Pierre-Olivier Latour <
notifications@github.com> wrote:

> BTW the configuration editor
> <https://github.com/git-up/GitUp/wiki/Using-GitUp-Configuration-Editor>
> will confirm that GitUp can see all your Git settings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/git-up/GitUp/issues/78#issuecomment-195838599>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by swisspol** [comment]
There must be something special with your global Git config as nobody else ever reported such a problem. If GitUp wasn't reading the global config, people wouldn't even be able to commit as that's where the user info typically is.

There is either something wrong with your Git configs, or something wrong with https://libgit2.github.com/, but this actually not something that can be fixed at the GitUp level, sorry.
