### ISSUE TITLE
font icon not displaying

### ISSUE THREAD

**Issue by AlabiBabatunde** [git-up/GitUp#780]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <i class="fab fa-500px"></i>
    
    <Script src="script.js"></Script>
</body>
</html>

**Comment by lucasderraugh** [comment]
Clearly spam
