### ISSUE TITLE
Bug: 1.3 crashes when selecting PDF file in Commit view

### ISSUE THREAD

**Issue by marchyman** [git-up/GitUp#782]
Selecting a pdf file in either the Working Directory pane or the Index pane of commit view crashes gitup using 1.3 (1039).

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [5711]

Zipped crash log (ips file) attached

[GitUp-2021-11-21-195535.ips.zip](https://github.com/git-up/GitUp/files/7578615/GitUp-2021-11-21-195535.ips.zip)

**Comment by lucasderraugh** [comment]
Yep, realized it over the weekend. Should be fixed in latest continuous build.
