### ISSUE TITLE
[High Priority] The file marked as removed, but can't discard changes.

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#783]
<img width="1531" alt="IOS_—_Commit" src="https://user-images.githubusercontent.com/16647690/142985357-66a66b94-f0b9-4fa4-9ff0-33937124b18d.png">

This file is marked as deleted, but:
1) Can't discard changes. After discarding there is a little blink and nothing changes.
2) In terminal `gst` tells: `nothing to commit, working tree clean`.
3) In folder file exists.

Tried Sourcetree and it work correctly.
The file shouldn't be marked as removed.

How can I help to give additional info about it?

**Comment by NikKovIos** [comment]
Found out

     workdirDiff = [self diffWorkingDirectoryWithRepositoryIndex:nil
                                                          options:(self.diffBaseOptions | kGCDiffOption_IncludeUntracked)
                                                maxInterHunkLines:_diffMaxInterHunkLines
                                                  maxContextLines:_diffMaxContextLines
                                                            error:&error];

Return 1, but should 0.

Maybe it's gitlib2 proplem like this https://github.com/libgit2/libgit2/issues/6091  
If so this lib should be updated.

**Comment by lucasderraugh** [comment]
Thanks for the investigation. I'll be looking into #772 soon. Needed to get 1.3 out the door first.

**Comment by NikKovIos** [comment]
@lucasderraugh really need this! How can I help?

**Comment by lucasderraugh** [comment]
@NikKovIos  If you want to test #772 to verify that it works that would be good. I have limited time to verify large change sets.

**Comment by NikKovIos** [comment]
@lucasderraugh ok. I should just build and use application in common way to test it?

**Comment by lucasderraugh** [comment]
@lolgear has made a ton of changes to that space, and I fear it's a bit too much to be reliably reviewable, but he did leave instructions for how to get it to work in #772. In my mind, I should be able to hit build and run though, otherwise we're making this too complicated. If his changes aren't just build and run then I don't think it will be merged in, but having other people test it before I have to look at is is very useful to me.

**Comment by lolgear** [comment]
@lucasderraugh
Modern approach in libgit2 is autogenerated features.h file which contains all necessary defines ( features ) of current library build ( actually, environment where this library was built ).
I don't believe that custom set of defines or committed `features.h` file would be a solution for "build and run". 

As an option:
We can add build step into xcodeproj and check if libgit2 is ready for use OR we need a run of `update-xcode.sh`.

If this is acceptable, yes, we can add another script ( or change `update-xcode.sh` ).

**Comment by NikKovIos** [comment]
@lolgear @lucasderraugh maybe you can check about merging at vacations?)

**Comment by lolgear** [comment]
Yeah, it would be nice, but I still don't know what we can do here.
A PR with fresh version of libgit2 is opened.
One concern is that developer have to run a script for installing libgit2 fork before his first build of GitUp. Ok, I don't think it is a big problem. If it is a problem, then, we have to consider my solution above ( a Script phase in Xcode which runs this script at first build and save "lock file" to determine "first build" ).
CI have to run this script every time. Ok, it is CI and it do a lot of wasteful things.

**Comment by NikKovIos** [comment]
Additional info:

...warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'UserInfoTask.swift'
  'UserinfoTask.swift'

UserinfoTask was renamed to MTSUserInfoTask and error was in system with apfs case insensitive

**Comment by lucasderraugh** [comment]
I'm going to close this issue out, as we have updated libgit2 to 1.4 (for better or worse). I assume this particular issue is resolved, though I've hit a different issue of being unable to discard certain files sometimes with #928.
