### ISSUE TITLE
[Feature request] Set upstream without popup.

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#784]
Duplicate of https://github.com/git-up/GitUp/issues/309  
Really annoying to select it every time. Please make a setting to set upstream automatically on push.

**Comment by NikKovIos** [comment]
I've created a PR. Check please. https://github.com/git-up/GitUp/pull/786/files

**Comment by lucasderraugh** [comment]
Fixed in #786

**Comment by lucasderraugh** [comment]
@NikKovIos Now available in 1.3.1 on continuous channel.
