### ISSUE TITLE
Unstaged diff for image files is broken

### ISSUE THREAD

**Issue by Stengo** [git-up/GitUp#788]
It seems like 8147b529e1858c1d9c8dd6c7ca547e9446eeb6c5 broke the visualization of unstaged image files.

The previous fallback behavior to the canonicalPath has been replaced by nilling out the property [here](https://github.com/git-up/GitUp/blob/master/GitUpKit/Interface/GIImageDiffView.m#L123).

FYI @lucasderraugh 

![Screenshot 2021-12-08 at 09 25 44](https://user-images.githubusercontent.com/12018882/145178684-d8781080-f5fe-4ba0-a07b-33cba7f5a7fc.png)

**Comment by lucasderraugh** [comment]
@Stengo Should be fixed in 1.3.1 on continuous channel.
