### ISSUE TITLE
Monterey clips NSToolbar mode switcher until window is resized

### ISSUE THREAD

**Issue by lucasderraugh** [git-up/GitUp#790]
For some reason the calculation isn't correct until the toolbar needs to be redrawn (if you adjust the window size it will resolve the issue). Might be worth refactoring the dual toolbar item stack into 2 separate simpler NSToolbarItems rather than the hybrid mode and navigation segmented control that exists today.
<img width="450" alt="Screen Shot 2021-12-09 at 9 20 13 PM" src="https://user-images.githubusercontent.com/714282/145506636-09cdf401-9736-4b68-89bb-81220b2ddf23.png">

**Comment by sesam** [comment]
I've seen this too recently. Could there be an easy workaround to just trigger a redraw early on?

**Comment by lucasderraugh** [comment]
#807 would address this.

**Comment by richardtop** [comment]
<img width="107" alt="image" src="https://user-images.githubusercontent.com/8013017/161877097-ed92b16c-5367-429d-9fa3-762bf18e1ad7.png">
Can confirm, happens to me too
