### ISSUE TITLE
SHA-1 RSA ssh key error

### ISSUE THREAD

**Issue by riggs** [git-up/GitUp#802]
Per https://github.blog/2021-09-01-improving-git-protocol-security-github/, Github is discontinuing support for SHA-1 RSA ssh keys as of 2022-1-11. Further [down](https://github.blog/2021-09-01-improving-git-protocol-security-github/#libgit2-and-other-git-clients) in that page it's mentioned that libssh2 doesn't have support for SHA-2 RSA keys yet (though [this PR](https://github.com/libssh2/libssh2/pull/626) adds it and was merged 4 days ago).

Given the prevalence of SHA-2 RSA ssh keys (the default for `ssh-keygen`), I suspect many will run into this. Github recommends switching to an ECDSA key.

[Edit] I can confirm that switching to an ECDSA key works (`ssh-keygen -t ecdsa`, update `.ssh/config`).

**Comment by sesam** [comment]
There's still no new release of https://github.com/libssh2/libssh2/releases that includes the SHA-2 support (merged Jan 6 2022) so this issue is likely blocked waiting on that.
And maybe upgrading to a new libssh2 once that's done would also solve this issue here?

**Comment by ajacquelin** [comment]
Hello, I am having the following error today (it was working fine few hour ago)
Is there any ETA on this ?
![Screenshot 2022-03-15 at 15 39 52](https://user-images.githubusercontent.com/1488200/158402559-ec4dc0ab-ab76-44eb-8c25-c89e7ee0eac5.png)

**Comment by lucasderraugh** [comment]
If you follow along in these instructions you should be able to generate a new SSH key for your use https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by slundy-ledger** [comment]
Same error
<img width="282" alt="Capture d’écran 2022-03-16 à 17 05 07" src="https://user-images.githubusercontent.com/96065469/158635478-2eacb02c-6ba6-4e11-983f-453f83d8d616.png">

The issue is not with my SSH key : I can use the git client in my terminal.

I suspect the issue is within the ssh lib GitUp is using : https://github.blog/2021-09-01-improving-git-protocol-security-github/
`libgit2 and other Git clients
If you’re using libgit2 or another piece of code using libssh2, we recommend you use libssh2 1.9.0 or newer and an ECDSA key, since it does not yet support RSA with SHA-2. Similarly, the Go SSH client also doesn’t yet support RSA with SHA-2, so we recommend using an Ed25519 key there.`

**Comment by lucasderraugh** [comment]
I'm currently using an `ed25519` key and have for some time with GitUp. Please try creating a new SSH keys using the `ssh-keygen -t ed25519 -C "your_email@example.com"` format and see how it goes.

**Comment by tahitithebob** [comment]
Unfortunatly the Xcode version I am using does not support `ed25519` encryption.
Is there a way to make gitup work with `SHA-2 RSA` ssh key ?

**Comment by lucasderraugh** [comment]
@tahitithebob I don’t think libssh2 has created a release that contains a fix for this, and I’m unlikely to create a build that isn’t using an official release of libssh2. I’m not sure how Xcode is an issue in this case unless you’re trying to push and pull in Xcode’s GUI.

**Comment by tahitithebob** [comment]
Ok thanks! Yes unfortunatly Xcode is using my git config under the hood  automatically to fetch the dependencies.
Have a nice day

**Comment by richardtop** [comment]
Any way to resolve this issue? I think I tried with `ed25519` key and still got this error.

**Comment by lucasderraugh** [comment]
I'm using that key (and only that key type) and GitUp does work with it.

**Comment by richardtop** [comment]
Have you added that key recently? They seem to allow it for the legacy-added keys (which have been uploaded to GitHub some time ago)

**Comment by lucasderraugh** [comment]
Recreated mine in the last 2 months.

**Comment by richardtop** [comment]
Thanks for checking up, regenerating the keys fixed my issues

**Comment by robinp-tw** [comment]
For the record, if you use gpg-agent as a replacement of ssh-agent, check its version with `gpg-agent --version`. https://superuser.com/a/1499705 points that `<2.2.6` doesn't support the new hash algos yet, and will just send back an SHA-1 hash to your ssh client (used by git).

Then, depending on your ssh version, either ssh itself will tell you that the agent sent the wrong hash type, or ssh doesn't check and just sends to git server, and then git will refuse to accept it, thus the message. Can check these with `ssh -v git@github.com`.

It also helps to debugging to pin the key used for github.com in your `~/.ssh/config` using something alike

```
Host github.com
    IdentitiesOnly yes  # Use only the explicit identity listed below
    IdentityFile ~/.ssh/key-on-card.pub  # note for non-smartcard keys this should be the private key instead!
```

**Comment by lucasderraugh** [comment]
I'm going to close this ticket out as resolved.

The official stance here is that we support ed25519 and it's replacing the old RSA keys (again we still support but GitHub will not) and so does the latest Xcode.

**Comment by edeca** [comment]
If using `plink.exe` from PuTTY then ensure version 0.75 or higher, which adds the following:

> Upgraded default SSH key fingerprint format to OpenSSH-style SHA-256.

**Comment by DannyRostami** [comment]
> I'm currently using an `ed25519` key and have for some time with GitUp. Please try creating a new SSH key using the `ssh-keygen -t ed25519 -C "your_email@example.com"` format and see how it goes.

Worked like a charm babe

**Comment by cvn** [comment]
Even after I created new ed25519 key, added it to GitHub, and updated the `~/.ssh/config` file, I was still getting the `You're using an RSA key with SHA-1` error. It started working after I removed my old RSA key from GitHub.
