### ISSUE TITLE
How to push with --force?

### ISSUE THREAD

**Issue by Attiv** [git-up/GitUp#806]
Sorry, I tried to find this option but couldn't find it

**Comment by lucasderraugh** [comment]
You just do a normal push and a prompt will ask you to override if the push would require force.

**Comment by Attiv** [comment]
> Collaborator

Thx, but how to do this:
`git reset --hard ***` and `git push --force`

**Comment by Attiv** [comment]
> 

Got it, thanks

**Comment by kwickramasekara** [comment]
Would be cool to have the option to do a force push when you know you have to do it anyway. Like in my case, we have a bunch of pre-push git hooks which takes a while. So, this two-step process seems unnecessary where you click push and then wait for it to prompt for the force push.
