### ISSUE TITLE
Can we drop outdated XLFacility?

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#815]
We have os_log for logging in modern macOS apps.
You can enable debug logging in console app very easily.

In current implementation we can do the following:

```objective-c
@import os.log;
os_log_t the_logger() {
  if (@available(macOS 10.11, *)) {
    return os_log_create("GitUp", "GitUp");
  } else {
    // Fallback on earlier versions
    return 0;
  }
}

#define XLOG_DEBUG(format, ...) os_log_debug(the_logger(), format, ##__VA_ARGS__)
#define XLOG_INFO(format, ...) os_log_info(the_logger(), format, ##__VA_ARGS__)
#define XLOG_WARNING(format, ...) os_log_warning(the_logger(), format, ##__VA_ARGS__)
#define XLOG_ABORT(format, ...) os_log_fatal(the_logger(), format, ##__VA_ARGS__)
```

Logs will be recorded to logs directory and sqlite store is unnecessary for logging.

**Comment by lolgear** [comment]
I guess we can raise deployment target to macOS 10.12 or even 10.13...

**Comment by lucasderraugh** [comment]
I'll bump to 10.13 for next release. Moving to os_log sounds good. Keeping the existing macros to avoid lots of code change would be ideal.

**Comment by lolgear** [comment]
@lucasderraugh 
I guess it may be closed due to https://github.com/git-up/GitUp/commit/67f2cc04d18800f5bfc9b0a82d2bd2fdf38b95d1
