### ISSUE TITLE
Bug: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. 

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#817]
ERROR: You're using an RSA key
with SHA-1, which is no longer
allowed. Please use a newer
client or a different key type.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/formore information.

<img width="372" alt="Screen Shot 2022-04-27 at 14 29 49" src="https://user-images.githubusercontent.com/8013017/165628238-0a26f8cb-b1ae-47e6-8d17-1ba6856df119.png">

Looks like this error applies to all the new keys generated for GitHub. Is something has to be updated on GitUp's end?

**Comment by lucasderraugh** [comment]
Same as #802.
