### ISSUE TITLE
1.3.2 asset zip creates alert on chrome download

### ISSUE THREAD

**Issue by morriswinkler** [git-up/GitUp#844]
<img width="407" alt="Screenshot 2022-06-08 at 12 25 23" src="https://user-images.githubusercontent.com/4302527/172594246-72170a80-91b4-4a1e-8412-487673b832fc.png">

Since 1.3.2 this alert is created when downloading the GitUp.zip from the github release page.

**Comment by lucasderraugh** [comment]
Zip files are dangerous now, huh? Not sure what formats are considered safe then.

**Comment by lucasderraugh** [comment]
Hmm, can't think of anything different I would have done, but I'll play around with it. Thanks!

**Comment by lucasderraugh** [comment]
Hmm, I tried this out on the latest chrome that I have which is Chrome Version 103.0.5060.53 (Official Build) (arm64). I didn't receive this warning and everything worked as expected. I downloaded from this URL https://github.com/git-up/GitUp/releases/tag/v1.3.2.

I'm going to close this ticket out as I'm not really sure what would be the issue.
