### ISSUE TITLE
Repository Won't Open - In Bad State - Error: Object Not Found - No Match for ID

### ISSUE THREAD

**Issue by stanfordstevens** [git-up/GitUp#849]
I was in the middle of either pulling/pushing a branch, and GitUp was unresponsive for many minutes.

I decided to Force Quit the application (which I think caused where I am at now), and now when I try to open up the same repository, I continuously get this same error:

![Screen Shot 2022-07-20 at 3 23 42 PM](https://user-images.githubusercontent.com/9700319/180065477-1bf597f8-3cec-4cd5-95c0-373253667908.png)

I tried deleting and re-installing GitUp with no luck. Something is clearly in a bad state, and wondering if there is cached data or something of the same sort that I could delete to remove this issue.

The repository itself is now fine and I am working from the terminal.

**Comment by lucasderraugh** [comment]
If you go into the .git folder there is GitUp specific information stored there. If you delete that and open in GitUp again, does that resolve your issue?

**Comment by stanfordstevens** [comment]
Unfortunately no. I tried that along with deleting any `co.gitup.mac` folder i could find on my Mac, and then re-installing GitUp, with still no luck.

I noticed that after doing all of that and then re-installing, GitUp still showed repositories under `Recently Opened...` indicating to me that some data may still be cached somewhere on my system.

**Comment by lucasderraugh** [comment]
Open recently is handled by AppKit, wouldn't affect what you're seeing. Usually this issue arrises on a bad stash or I think we've seen it with our local snapshots. Would be nice if our warnings was a bit more specific. If you do a fresh clone it should fix your issue I would expect, but would like to know if even that doesn't resolve it for you.

**Comment by stanfordstevens** [comment]
I did attempt clearing out all my stashes for the repository which didnt work.

I'll try a fresh clone and report back, thanks for the help.

**Comment by stanfordstevens** [comment]
Yep, a fresh clone did the trick. Thanks for the help!

**Comment by lucasderraugh** [comment]
@stanfordstevens In the interest of keeping issues actionable I'm going to close this out. How an oid lookup would fail is unclear to me and without anything to go off of this will likely stay open forever. Thanks!

**Comment by jaredp-openai** [comment]
I hit the same error and resolved with `git gc --prune=now --aggressive`

I don't entirely follow the details, but the object in question was
1. a valid commit I could `git log xxxxx`
2. not in `./git/objects/xx/xxxx`
3. was possibly in some kind of pack file, maybe corrupted, or maybe git cli could read but libgit2 couldn't. (The error message seems to come from libgit2's `git_odb_read`)

`git gc --prune=now --aggressive` does some kind of repacking, which seems to have fixed it!
