### ISSUE TITLE
makefiles

### ISSUE THREAD

**Issue by ehrenmann1977** [git-up/GitUp#859]
could you please add the makefiles generated by xcode to the repo, i am trying to compile under Linux, but the current way of compiling needs xcode. Xcode will generate makefiles, i wil try to compile the make files together with object c libraries under linux.

**Comment by lucasderraugh** [comment]
You won't be able to compile the frameworks necessary unless you have macOS. You can compile libgit2. I think there is another project that has made an offshoot for Linux though and I'll post a link when I find it (or somebody else does).

**Comment by lucasderraugh** [comment]
Here it is: https://github.com/codymikol/git-down
