### ISSUE TITLE
Can not open merge tool

### ISSUE THREAD

**Issue by pys1992** [git-up/GitUp#861]
Click the button, nothing happened.

gitup version:  Version 1.3.2 (1045)
file merge version: Version 2.11 (21012)
macos version: macos Monterey 12.5.1 Apple M1

<img width="622" alt="image" src="https://user-images.githubusercontent.com/44765369/191908554-35cc8f5c-b3f1-47b3-ab70-58eed096f10e.png">

**Comment by matv13v** [comment]
Hi!
As far as I know, you should to have a third-party tool for that kind of thing.

**Comment by lucasderraugh** [comment]
<img width="500" alt="Screenshot 2022-11-30 at 11 29 24 AM" src="https://user-images.githubusercontent.com/714282/204854076-bc03d067-0a59-4bd1-bae6-178e19fa8f2b.png">

@pys1992 Are your external diff and external merge set to `FileMerge`?

**Comment by pys1992** [comment]
> <img alt="Screenshot 2022-11-30 at 11 29 24 AM" width="500" src="https://user-images.githubusercontent.com/714282/204854076-bc03d067-0a59-4bd1-bae6-178e19fa8f2b.png">
> 
> @pys1992 Are your external diff and external merge set to `FileMerge`?

Of caurse. I haven't changed the settings.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/44765369/206634685-d91322d1-1e1d-4c05-8171-bf1a32622d44.png">

**Comment by pys1992** [comment]
![Kapture 2022-12-09 at 15 47 30](https://user-images.githubusercontent.com/44765369/206651739-1235d490-a298-424b-8646-716ef416415e.gif)

**Comment by lucasderraugh** [comment]
@pys1992 What is your output if you run `/usr/bin/opendiff` in Terminal?

**Comment by lucasderraugh** [comment]
@pys1992 Please follow the steps to fix your Command Line tools instance. https://stackoverflow.com/questions/41116584/error-xcode-select-error-tool-xcodebuild-requires-xcode

**Comment by pys1992** [comment]
Thanks. I fix the issue by this answer.
https://stackoverflow.com/a/17980786

**Comment by lucasderraugh** [comment]
Great! We throw alerts around most of these things, but we currently aren't doing anything when the task is run. It would be ideal if we could capture failure and present the output to the user so they can perhaps avoid debugging like we did here 😅.
