### ISSUE TITLE
GitUp fails to open a submodule placed in a sub-subdirectory

### ISSUE THREAD

**Issue by tim-ist** [git-up/GitUp#864]
If the submodule is located in a sub-subdirectory, GitUp does not open the submodule.
Example:
```
project/
    .git/
    my_submodules/submodule
```

If I `cd my_submodules/submodule` and try to launch gitup from there, it fails to open, saying `could not find repository from '/Users/.../project/.git/modules/my_submodules'`

**Comment by lucasderraugh** [comment]
Why are you opening from within the `.git` directory? Just navigate to the actual checked out repo and open it there.

**Comment by tim-ist** [comment]
I am not opening it from within the `.git` directory but from the actual checked out submodule repo. Sorry, probably the example directory structure that I posted is confusing.

Now I have recreated the example from scratch and apparently GitUp works fine with it, though not with my real project repo. I will investigate it further. Meanwhile we can probably close this issue, thank you for your quick response!
