### ISSUE TITLE
"Stage File" and "Cog Icon" spacing layout issue

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#874]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/8013017/202433330-cf133a8b-e434-4986-bebf-68d7c01f4af9.png">

Please refer to the screenshot to see the problem. The "Stage File" and the cog icon have too little of a spacing.

**Comment by lucasderraugh** [comment]
That's weird, doesn't appear that way for me. What OS are you running? Does this happen all the time / everywhere for you? @richardtop

**Comment by richardtop** [comment]
I think, part of the reason might be due to the fact that I have both retina (HiDPI) and non-retina screens and moving the window from one to another might have affected this.

**Comment by lucasderraugh** [comment]
@richardtop In the interest of trying to keep issues actionable, I'm going to close this out. If you do happen to reproduce how exactly this occurs for you, that would be much appreciated and then feel free to reopen. Thanks!
