### ISSUE TITLE
"Config value 'user.name' was not found" with custom .gitconfig.

### ISSUE THREAD

**Issue by andreinagy** [git-up/GitUp#875]
Hi, first of all I want to thank you for making gitup, it's awesome! 

### Preconditions
I recently started using a more complex setup, with different git identities per directory.
example ~/.gitconfig
```
[includeIf "gitdir:~/ABC/"]
	path = .gitconfig-ABC
[includeIf "gitdir:~/DEF/"]
	path = .gitconfig-DEF
```
example ~/.gitconfig-ABC:
```
[user]
	name = My Name
	email = my@email.com
```

### Steps to reproduce:
1. open a directory with changes in a terminal.
2. run `git config user.name` (the command correctly outputs a username)
3. open the directory in gitup and try to comit.

### Expected result:
The commit is successful. With my setup it's possible to commit using the command line or another git GUI.

### Actual result:
The bottom of the gitup window there is a message "Committing as NA".
![bottom identity N/A](https://user-images.githubusercontent.com/4987417/203385556-70d8d9ac-f775-48cb-bed8-478cba055d42.png)
The commit fails with "Config value 'user.name' was not found".
![error message](https://user-images.githubusercontent.com/4987417/203385523-52a70fa4-a772-41b5-9b6e-b255e6f7cdeb.png)

### Other notes:
- I found an older issue, but I have git properly set up [link](https://github.com/git-up/GitUp/issues/131)
- GitUp version 1.3.2 (1045)

**Comment by lucasderraugh** [comment]
Thanks, @andreinagy! I believe this isn't supported at the moment because of #315. Though in the master branch we have picked up a recent version of libgit2, so perhaps this works automatically now. I haven't tested.

Looking to push a build out to the continuous this week. You can either try building master to see if it fixes it or wait until the continuous release and let me know if it resolves anything.

**Comment by andreinagy** [comment]
Hi @lucasderraugh, sorry for the late reply,

It works by building on the latest main, in the app I didn't get an update yet.
![Screenshot 2022-11-30 at 11 10 58](https://user-images.githubusercontent.com/4987417/204755256-90c93cc6-00da-444a-8ea6-03113aff84b5.png)

Thanks for the help!

**Comment by lucasderraugh** [comment]
@andreinagy Just pushed 1.3.3 to continuous. I'm going to close this ticket out as hopefully being resolved. If it's not the case in 1.3.3, please let me know.
