### ISSUE TITLE
Modal dialogs no longer have focus with Mac Ventura

### ISSUE THREAD

**Issue by SteveEdson** [git-up/GitUp#879]
I'm 99% sure this changed with Ventura, but previously, dialogs/confirmations had focus when opening. For example, prior to Ventura, I could select a file, press backspace to discard those changes, and then press enter to confirm it, (as in the modal "discard" button had the focus I guess).

Now, I have to either click the discard button manually, pressing enter just triggers the warning bell sound.

**Comment by lucasderraugh** [comment]
Yes it did change with Ventura. I need to fix it as it drives me crazy 😅
