### ISSUE TITLE
Regression in 1.3.3 from 1.3.2: Rebasing with conflicts fails with internal error

### ISSUE THREAD

**Issue by swisspol** [git-up/GitUp#882]
When rebasing a topic branch with 2 commits on `master` and each commits has conflicts, the conflict resolution UI appears for the first commit, I resolve the conflicts, then commit, but instead of showing the UI for the 2nd commit and its conflicts (which is the case with 1.3.2), with 1.3.3, there's just this error:

![image](https://user-images.githubusercontent.com/627915/207271665-1c8dca43-862d-49f3-b4ee-50659e84f6b1.png)

```
% git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	guides/getting_started/apps_directory.md
	guides/getting_started/okta_groups.md
```

**Comment by lucasderraugh** [comment]
Sorry to have broken that flow @swisspol. It's most likely a change with libgit that caused this, but I'll try figuring out what the difference is today.

**Comment by iest** [comment]
Getting this issue a bunch!

I downloaded `v1.3.2` to revert but GitUp just loves to be up to date. Any way to disable that?

p.s. I absolutely love this tool and very much appreciate the hard work that goes into it! Have you considered opening a patreon for supporting this work?

**Comment by lucasderraugh** [comment]
Does anyone have easy reproducible steps for this bug? This is the one remaining bug I don't think I have a solution for and am trying to determine how to test it.

I've tried having a `test` branch and `main` that have 2 commits each that both contain conflicts in a single line in a single file, but I don't seem to hit an issue with this. I'll keep trying more complex cases, but any assistance on how people hit this would be really helpful!

<img width="161" alt="Screenshot 2023-01-05 at 2 56 23 PM" src="https://user-images.githubusercontent.com/714282/210868768-39e8b931-a4aa-4ab6-b51c-dc478b4398e5.png">

**Comment by marcboquet** [comment]
I believe you should be able to reproduce with this sample repo:
[gitup-rebase-issue.zip](https://github.com/git-up/GitUp/files/11054142/gitup-rebase-issue.zip)

Trying to rebase `changes` onto `main` ends up with conflicts.

The issue only started happening when I added a new file on `main` that didn't exist in `changes`, if that helps.

**Comment by lucasderraugh** [comment]
@marcboquet Thanks, I haven't hit it in my own work lately and so this sample will definitely be helpful.

**Comment by lapfelix** [comment]
I just tried the changes I made in https://github.com/git-up/GitUp/pull/990 with @marcboquet's sample repo and it seems to fix it:
https://github.com/git-up/GitUp/assets/4634735/85257747-60aa-49f1-8c34-446a4716dc68
