### ISSUE TITLE
Regression in 1.3.4: discarding file changes during rewrite deletes the whole file

### ISSUE THREAD

**Issue by jfirebaugh** [git-up/GitUp#885]
To reproduce:

1. Select "Rewrite..." on some commit
2. Click "Discard File Changes..."

Expected result: File is removed from diff
Actual result: File is deleted entirely in diff

Works as expected in 1.3.2.

**Comment by lucasderraugh** [comment]
Will be addressed in 1.3.5.

We made changes in e060ece1ef5c5d72c73800df3d4c6d70d0d8ae59 that was meant to assist in bulk discard/stage operations, but there were some bugs in the handling of that.

Thanks for reporting!
