### ISSUE TITLE
[Feature request] Create a hotkey for "save new stash" and "delete selected stash" buttons.

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#888]
![image](https://user-images.githubusercontent.com/16647690/208163165-5327c38c-3956-4a52-8306-b7af070eb75b.png)

**Comment by lucasderraugh** [comment]
We do actually have keys for that, delete key and `s`. https://github.com/git-up/GitUp/wiki/Using-GitUp-Stashes-View
