### ISSUE TITLE
Redundant remote branch labels

### ISSUE THREAD

**Issue by salutis** [git-up/GitUp#89]
I've been using _GitUp_ since day one and it's always worked 100%.

However, today I did _something_ and ended up with this:

<img width="333" alt="screen shot 2016-03-20 at 14 58 17" src="https://cloud.githubusercontent.com/assets/1158274/13904797/71530158-eeac-11e5-975e-e3fa19b9cdc5.png">

All branches are tracking and up-to-date with their remotes:

```
$ git branch -vv
* develop             7d9722e [origin/develop]
  feature/calibration 7d9722e [origin/feature/calibration]
  master              38cfdaa [origin/master]
  release/3.0.7       c8312f6 [origin/release/3.0.7]
```

```
$ git branch -r -vv
  origin/HEAD                -> origin/master
  origin/develop             7d9722e
  origin/feature/calibration 7d9722e
  origin/master              38cfdaa
  origin/release/3.0.7       c8312f6
```

Why is _GitUp_ showing all those `origin/...` labels without the tracking arrow symbol?

**Comment by swisspol** [comment]
GitUp shows local and remote branches. Local branches that have an upstream have a second line that start with the arrow indicating the name of the upstream.

**Comment by salutis** [comment]
The question was about labels **without** the arrows:

<img width="333" alt="screen shot 2016-03-20 at 14 58 17" src="https://cloud.githubusercontent.com/assets/1158274/13905187/88c79fd6-eeb8-11e5-9961-39679cd64269.png">

**Comment by swisspol** [comment]
These are simply remote branches.

**Comment by salutis** [comment]
I must be going crazy. Sorry for taking up your time.
