### ISSUE TITLE
regression in 1.3.4 - crash with lfs

### ISSUE THREAD

**Issue by FrancoisBlavoet** [git-up/GitUp#892]
Git-lfs used to work well with Gitup, now each time I have an uncommited image, Gitup just crashes until I manually commit it from the command line.

**Comment by lucasderraugh** [comment]
I'm learning that libgit2 1.4.4 is a disaster 😅. I think I'm ultimately going to end up reverting to what we used to have in the interim as there just seems to be a lot broken.

**Comment by lucasderraugh** [comment]
Could you also attach the crash report to this ticket?

**Comment by FrancoisBlavoet** [comment]
for sure, here you go: 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GitUp [7798]
Path:                  /Applications/GitUp.app/Contents/MacOS/GitUp
Identifier:            co.gitup.mac
Version:               1.3.4 (1047)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2022-12-19 18:43:26.0526 -0800
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        75D50561-922A-90EC-0AEC-A3336F75CD53

Sleep/Wake UUID:       9BF383A0-AC6F-4047-8DFD-2E7825007DFF

Time Awake Since Boot: 490000 seconds
Time Since Wake:       32651 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [7798]

VM Region Info: 0 is not in any region.  Bytes before following region: 4328538112
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102004000-10202c000    [  160K] r-x/r-x SM=COW  ...s/MacOS/GitUp

Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	               0x0 ???
1   GitUpKit                      	       0x1030e78a4 git_filter_list_stream_buffer + 100
2   GitUpKit                      	       0x1030e77f8 git_filter_list__apply_to_buffer + 92
3   GitUpKit                      	       0x1030e78f8 git_filter_list__convert_buf + 40
4   GitUpKit                      	       0x10310dc48 git_odb__hashfd_filtered + 112
5   GitUpKit                      	       0x1030dd1ec git_diff__oid_for_entry + 384
6   GitUpKit                      	       0x1030de228 git_diff__from_iterators + 3828
7   GitUpKit                      	       0x1030de8f0 git_diff_index_to_workdir + 200
8   GitUpKit                      	       0x103045818 __114-[GCRepository(GCDiff) diffWorkingDirectoryWithIndex:filePattern:options:maxInterHunkLines:maxContextLines:error:]_block_invoke + 88
9   GitUpKit                      	       0x1030451c8 -[GCRepository(GCDiff) _diffWithType:filePattern:options:maxInterHunkLines:maxContextLines:error:block:] + 436
10  GitUpKit                      	       0x103045774 -[GCRepository(GCDiff) diffWorkingDirectoryWithIndex:filePattern:options:maxInterHunkLines:maxContextLines:error:] + 224
11  GitUpKit                      	       0x10305106c -[GCLiveRepository _updateStatus:] + 304
12  GitUpKit                      	       0x10304f7e4 -[GCLiveRepository _notifyWorkingDirectoryChanged:gitDirectoryChanged:] + 124
13  GitUpKit                      	       0x10304ebc8 -[GCLiveRepository _timer:] + 112
14  GitUpKit                      	       0x10304f66c _TimerCallBack + 44
15  CoreFoundation                	       0x1823f7468 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
16  CoreFoundation                	       0x1823f7064 __CFRunLoopDoTimer + 1076
17  CoreFoundation                	       0x1823f6af0 __CFRunLoopDoTimers + 392
18  CoreFoundation                	       0x1823db66c __CFRunLoopRun + 1944
19  CoreFoundation                	       0x1823da734 CFRunLoopRunSpecific + 600
20  HIToolbox                     	       0x18af6cf68 RunCurrentEventLoopInMode + 292
21  HIToolbox                     	       0x18af6ccdc ReceiveNextEventCommon + 552
22  HIToolbox                     	       0x18af6ca9c _BlockUntilNextEventMatchingListInModeWithFilter + 72
23  AppKit                        	       0x184f30ce0 _DPSNextEvent + 844
24  AppKit                        	       0x184f2f584 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
25  AppKit                        	       0x184f215a4 -[NSApplication run] + 596
26  AppKit                        	       0x184ef2c78 NSApplicationMain + 1064
27  dyld                          	       0x1023610f4 start + 520

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1822d5954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1822d5d00 mach_msg + 76
2   CoreFoundation                	       0x1823dced8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1823db390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1823da734 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x18509dc90 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x182311240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18230c024 thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x18230c010 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18230c010 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18230c010 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600002848180   x1: 0x00006000048546d0   x2: 0x0000600015399858   x3: 0x0000600015399840
    x4: 0x0000000153ce1278   x5: 0x0000000000000020   x6: 0x00015301000153c0   x7: 0xffffffff00015300
    x8: 0x0000000000000000   x9: 0x0000000178440000  x10: 0x0000000000002026  x11: 0x0000000178007ffc
   x12: 0x000000000000cd78  x13: 0x0000000000000089  x14: 0x00000000ffff8001  x15: 0x00000000001c8800
   x16: 0x0000000182328110  x17: 0x00000000000008fd  x18: 0x00000001202e3940  x19: 0x0000600015399800
   x20: 0x0000000178380000  x21: 0x0000600015399840  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000008000  x25: 0x00006000984e9a68  x26: 0x00000001462d02b0  x27: 0x00006000984e9a40
   x28: 0x0000000000000003   fp: 0x000000016ddf89b0   lr: 0x00000001030e7f80
    sp: 0x000000016ddf8960   pc: 0x0000000000000000 cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0x82000006 (Instruction Abort) Translation fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x10303c000 -        0x1034a3fff co.gitup.kit (*) <5fa9665f-5ca0-34ff-81da-42df255f5ff8> /Applications/GitUp.app/Contents/Frameworks/GitUpKit.framework/Versions/A/GitUpKit
       0x182358000 -        0x18289bfff com.apple.CoreFoundation (6.9) <f5ea9592-4ef9-3d35-b23d-5c21283acc52> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x18af3a000 -        0x18b269fff com.apple.HIToolbox (2.1.1) <01b981b8-a2d8-374d-9a0e-c4ac8c1009da> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x184eef000 -        0x185da2fff com.apple.AppKit (6.9) <a8bbc643-113d-310f-96b6-77a973bf2dba> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x10235c000 -        0x1023bbfff dyld (*) <7e92b284-4b90-3b68-b31a-3ddc4c0e8d40> /usr/lib/dyld
       0x1822d4000 -        0x182309fff libsystem_kernel.dylib (*) <c8b3081a-5081-3a99-bbe3-01413de444c6> /usr/lib/system/libsystem_kernel.dylib
       0x18230a000 -        0x182316fff libsystem_pthread.dylib (*) <ed328b18-eeef-3b15-8858-798b19b0c2cd> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=6.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=6.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1152K        9 
Activity Tracing                   256K        1 
CG backing stores                 4032K        4 
CG image                           688K       32 
ColorSync                          576K       28 
CoreAnimation                     34.2M      183 
CoreGraphics                        32K        2 
CoreImage                           16K        1 
CoreUI image data                 3712K       29 
Foundation                          48K        2 
Image IO                           112K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             5.5G      337 
MALLOC guard page                  288K       14 
MALLOC_MEDIUM (reserved)         896.0M       11         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                   64K        1 
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                       1424K       14 
__AUTH                            2506K      302 
__AUTH_CONST                      19.0M      486 
__DATA                            14.6M      475 
__DATA_CONST                      17.4M      496 
__DATA_DIRTY                      1714K      206 
__FONT_DATA                          4K        1 
__LINKEDIT                       577.3M        9 
__OBJC_CONST                      3347K      265 
__OBJC_RO                         82.0M        1 
__OBJC_RW                         3104K        1 
__TEXT                           463.6M      514 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
libnetwork                         128K        8 
mapped file                        1.5G      131 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              9.6G     3591 
TOTAL, minus reserved VM space     8.3G     3591 



-----------
Full Report
-----------

{"app_name":"GitUp","timestamp":"2022-12-19 18:43:37.00 -0800","app_version":"1.3.4","slice_uuid":"c3c5302f-c0e1-3a2c-9a61-e5fe43d853ce","build_version":"1047","platform":1,"bundleID":"co.gitup.mac","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"94FC378F-8789-4BE2-8D28-85D05F08180C","name":"GitUp"}
{
  "uptime" : 490000,
  "procLaunch" : "2022-12-17 12:15:46.8416 -0800",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 503,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "procStartAbsTime" : 8604679388649,
  "coalitionID" : 88508,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2022-12-19 18:43:26.0526 -0800",
  "incident" : "94FC378F-8789-4BE2-8D28-85D05F08180C",
  "bug_type" : "309",
  "pid" : 7798,
  "procExitAbsTime" : 11841572597897,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "GitUp",
  "procPath" : "\/Applications\/GitUp.app\/Contents\/MacOS\/GitUp",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.4","CFBundleVersion":"1047","CFBundleIdentifier":"co.gitup.mac"},
  "storeInfo" : {"deviceIdentifierForVendor":"E2697489-ABB4-588A-AEDD-C48BEB3EBB1A","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "co.gitup.mac",
  "crashReporterKey" : "75D50561-922A-90EC-0AEC-A3336F75CD53",
  "wakeTime" : 32651,
  "sleepWakeUUID" : "9BF383A0-AC6F-4047-8DFD-2E7825007DFF",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4328538112\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102004000-10202c000    [  160K] r-x\/r-x SM=COW  ...s\/MacOS\/GitUp",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":7798},
  "ktriageinfo" : "VM - Compressor failed a blocking pager_get\nVM - Compressor failed a blocking pager_get\nVM - Compressor failed a blocking pager_get\nVM - Compressor failed a blocking pager_get\nVM - Compressor failed a blocking pager_get\n",
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4328538112\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102004000-10202c000    [  160K] r-x\/r-x SM=COW  ...s\/MacOS\/GitUp",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":8486685,"threadState":{"x":[{"value":105553158504832},{"value":105553192109776},{"value":105553472362584},{"value":105553472362560},{"value":5700981368},{"value":32},{"value":372738736870336},{"value":18446744069414671104},{"value":0},{"value":6312689664},{"value":8230},{"value":6308265980},{"value":52600},{"value":137},{"value":4294934529},{"value":1869824},{"value":6479315216,"symbolLocation":0,"symbol":"_platform_memmove"},{"value":2301},{"value":4834867520},{"value":105553472362496},{"value":6311903232},{"value":105553472362560},{"value":0},{"value":0},{"value":32768},{"value":105555671554664},{"value":5472322224},{"value":105555671554624},{"value":3}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4346249088},"cpsr":{"value":2147487744},"fp":{"value":6138333616},"sp":{"value":6138333536},"esr":{"value":2181038086,"description":"(Instruction Abort) Translation fault"},"pc":{"value":0},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":0,"imageIndex":0},{"imageOffset":702628,"symbol":"git_filter_list_stream_buffer","symbolLocation":100,"imageIndex":1},{"imageOffset":702456,"symbol":"git_filter_list__apply_to_buffer","symbolLocation":92,"imageIndex":1},{"imageOffset":702712,"symbol":"git_filter_list__convert_buf","symbolLocation":40,"imageIndex":1},{"imageOffset":859208,"symbol":"git_odb__hashfd_filtered","symbolLocation":112,"imageIndex":1},{"imageOffset":659948,"symbol":"git_diff__oid_for_entry","symbolLocation":384,"imageIndex":1},{"imageOffset":664104,"symbol":"git_diff__from_iterators","symbolLocation":3828,"imageIndex":1},{"imageOffset":665840,"symbol":"git_diff_index_to_workdir","symbolLocation":200,"imageIndex":1},{"imageOffset":38936,"symbol":"__114-[GCRepository(GCDiff) diffWorkingDirectoryWithIndex:filePattern:options:maxInterHunkLines:maxContextLines:error:]_block_invoke","symbolLocation":88,"imageIndex":1},{"imageOffset":37320,"symbol":"-[GCRepository(GCDiff) _diffWithType:filePattern:options:maxInterHunkLines:maxContextLines:error:block:]","symbolLocation":436,"imageIndex":1},{"imageOffset":38772,"symbol":"-[GCRepository(GCDiff) diffWorkingDirectoryWithIndex:filePattern:options:maxInterHunkLines:maxContextLines:error:]","symbolLocation":224,"imageIndex":1},{"imageOffset":86124,"symbol":"-[GCLiveRepository _updateStatus:]","symbolLocation":304,"imageIndex":1},{"imageOffset":79844,"symbol":"-[GCLiveRepository _notifyWorkingDirectoryChanged:gitDirectoryChanged:]","symbolLocation":124,"imageIndex":1},{"imageOffset":76744,"symbol":"-[GCLiveRepository _timer:]","symbolLocation":112,"imageIndex":1},{"imageOffset":79468,"symbol":"_TimerCallBack","symbolLocation":44,"imageIndex":1},{"imageOffset":652392,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":32,"imageIndex":2},{"imageOffset":651364,"symbol":"__CFRunLoopDoTimer","symbolLocation":1076,"imageIndex":2},{"imageOffset":649968,"symbol":"__CFRunLoopDoTimers","symbolLocation":392,"imageIndex":2},{"imageOffset":538220,"symbol":"__CFRunLoopRun","symbolLocation":1944,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":208744,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":208092,"symbol":"ReceiveNextEventCommon","symbolLocation":552,"imageIndex":3},{"imageOffset":207516,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":269536,"symbol":"_DPSNextEvent","symbolLocation":844,"imageIndex":4},{"imageOffset":263556,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1332,"imageIndex":4},{"imageOffset":206244,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":15480,"symbol":"NSApplicationMain","symbolLocation":1064,"imageIndex":4},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":5}]},{"id":8486974,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1764496,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":11208642,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":11211357,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":11211358,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4345544704,
    "CFBundleIdentifier" : "co.gitup.kit",
    "size" : 4620288,
    "uuid" : "5fa9665f-5ca0-34ff-81da-42df255f5ff8",
    "path" : "\/Applications\/GitUp.app\/Contents\/Frameworks\/GitUpKit.framework\/Versions\/A\/GitUpKit",
    "name" : "GitUpKit"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6479511552,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "f5ea9592-4ef9-3d35-b23d-5c21283acc52",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6626189312,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3342336,
    "uuid" : "01b981b8-a2d8-374d-9a0e-c4ac8c1009da",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6525218816,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15417344,
    "uuid" : "a8bbc643-113d-310f-96b6-77a973bf2dba",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.20.111"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4332044288,
    "size" : 393216,
    "uuid" : "7e92b284-4b90-3b68-b31a-3ddc4c0e8d40",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6478970880,
    "size" : 221184,
    "uuid" : "c8b3081a-5081-3a99-bbe3-01413de444c6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6479192064,
    "size" : 53248,
    "uuid" : "ed328b18-eeef-3b15-8858-798b19b0c2cd",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6476021760,
  "size" : 3089596416,
  "uuid" : "66c33c62-48a9-31e5-b8b5-7a71c9760d07"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=6.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=6.8G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              1152K        9 \nActivity Tracing                   256K        1 \nCG backing stores                 4032K        4 \nCG image                           688K       32 \nColorSync                          576K       28 \nCoreAnimation                     34.2M      183 \nCoreGraphics                        32K        2 \nCoreImage                           16K        1 \nCoreUI image data                 3712K       29 \nFoundation                          48K        2 \nImage IO                           112K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             5.5G      337 \nMALLOC guard page                  288K       14 \nMALLOC_MEDIUM (reserved)         896.0M       11         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                   64K        1 \nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                       1424K       14 \n__AUTH                            2506K      302 \n__AUTH_CONST                      19.0M      486 \n__DATA                            14.6M      475 \n__DATA_CONST                      17.4M      496 \n__DATA_DIRTY                      1714K      206 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       577.3M        9 \n__OBJC_CONST                      3347K      265 \n__OBJC_RO                         82.0M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           463.6M      514 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                        1.5G      131 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              9.6G     3591 \nTOTAL, minus reserved VM space     8.3G     3591 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000303
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "621d4d0f680160486b9e1c98"
      },
      "deploymentId" : 240000412
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000551
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000228
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,2, BootROM 7429.61.2, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Oct 25 2021 22:17:59 version 20.10.853.26.8.7.107 FWID 01-417a4935
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: Tailscale Tunnel, VPN (io.tailscale.ipn.macos), utun3
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by lucasderraugh** [comment]
Thanks, I will likely roll a 1.3.5 this week that reverts the changes for libgit2. There is more fallout than I expected and I don't think the benefits of the new version outweigh the regressions.

I'll try to revisit a new libgit2 version in the future, but my time to maintain this project is limited, therefore the focus is more on stability than feature work.

**Comment by lucasderraugh** [comment]
I think this is related to this: https://github.com/libgit2/libgit2/pull/6303

Looks like it is in the 1.5.0 build but not 1.4.4. I might try taking the change in to see if it resolves the issue.

**Comment by lucasderraugh** [comment]
@FrancoisBlavoet Please let me know if the 1.3.5 continuous build fixes your crash.

I was unable to reproduce the crash you observed, but applied the theoretical fix that seemed similar to your crash to the libgit2 1.4.4 changes.
