### ISSUE TITLE
Snapshot Preview titlebar item is selected when it now showing

### ISSUE THREAD

**Issue by japanese-goblinn** [git-up/GitUp#897]
This how it looks 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/33631005/208271902-60034843-fdd0-483f-a6d3-3fb0b708f567.png">

This is how it should look
<img width="257" alt="image" src="https://user-images.githubusercontent.com/33631005/208271912-041a55cd-7b2d-4809-b39a-6a7d443decd2.png">

**Comment by lucasderraugh** [comment]
How did you reproduce this, as I don't see this. Was it a one off? What version of macOS are you running?

**Comment by japanese-goblinn** [comment]
@lucasderraugh macOS 13.0.1, Its happening when I press the Snapshot Preview button and then close it with `esc`

**Comment by prostolyubo** [comment]
Yup, happens even if you close it normally by pressing the button again
