### ISSUE TITLE
v1.3.4 checks for updates multiple times per day, shows modal dialog that requires action each time

### ISSUE THREAD

**Issue by grempe** [git-up/GitUp#898]
Multiple times per day now that app, running in the background, will apparently check for updates and each time it pops up a modal dialog saying `GitUp is already up-to-date!`

Expected behavior is for background updates to happen, and notify me in-app that an update is needed when I next bring the app to the foreground.

The user should never have to track down the modal that is causing bouncing of the icon in the dock and requires them to click 'OK' each time.

**Comment by lucasderraugh** [comment]
Ya, I'm not sure why this has suddenly changed in this version as I didn't think anything changed with Sparkle, but I'll probably just remove that dialog in the next update.

Thanks!

**Comment by lucasderraugh** [comment]
Looks like there was an issue with how manual check for updates was performed. We now should be correctly resetting the flag on update.

Expect this fix in 1.3.5
