### ISSUE TITLE
Install via Homebrew?

### ISSUE THREAD

**Issue by MacDada** [git-up/GitUp#904]
I wanted to install GitUp today via Homebrew, but unfortunately [the package available](https://formulae.brew.sh/formula/gitup#default) was not _this_ GitUp…

**Comment by mriegler** [comment]
gitup is available as a cask. Since there is already a formula also named gitup, you need to explicitly ask for the cask:

`brew install homebrew/cask/gitup`

**Comment by MacDada** [comment]
Cool! Make a PR to document it in the docs? I've tried to google and searched this repo for `homebrew` before asking, and did find nothing about it.
