### ISSUE TITLE
How do I fully uninstall?

### ISSUE THREAD

**Issue by MacDada** [git-up/GitUp#905]
What are the files that GitUp creates, that I might want to delete, if I want to fully uninstall GitUp?

I've tried looking for something like `ls ~/Library/Application\ Support/GitUp`, but it isn't there.

I did find `ls ~/Library/Preferences/co.gitup.mac.plist` – anything else?

**Comment by lucasderraugh** [comment]
There isn't anything else that is particularly part of the system other than user defaults:
`defaults read co.gitup.mac`

There are some additional things added to the git repos opened inside `.git/co.gitup.mac`

**Comment by MacDada** [comment]
Thanks for your reply.

I've removed those files and did not help with my problem – but that's for another issue.

Anyway, I'd suggest adding info on how to uninstall GitUp completely to the docs. I can make a PR if you think it is a good idea.
