### ISSUE TITLE
https://gitup.co Download release button error

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#907]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/16647690/213676778-b508c5e7-025d-48b9-8d4a-d93d8dc29a42.png">

this button leads to https://s3-us-west-2.amazonaws.com/gitup-builds/stable/GitUp.zip and can't access to it

**Comment by lucasderraugh** [comment]
That's what the link has always been, and I don't seem to have any issue downloading it...

**Comment by NikKovIos** [comment]
Oh, really, I've enabled VPN and downloaded well 👍
