### ISSUE TITLE
Autoupdate not working

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#908]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/16647690/213676942-4c82e98f-c254-4b1d-9271-90cb5ca2e928.png">
<img width="312" alt="image" src="https://user-images.githubusercontent.com/16647690/213676969-3c846ed3-72eb-418e-af3d-275049e8c504.png">

After pressing check for updates - nothing happened.

**Comment by NikKovIos** [comment]
Perhaps it's because of VPN like this problem https://github.com/git-up/GitUp/issues/907

**Comment by lucasderraugh** [comment]
Seems likely

**Comment by NikKovIos** [comment]
@lucasderraugh Like a suggestion - hold release apps on github repo.
