### ISSUE TITLE
Merge tool is still not working with the latest update

### ISSUE THREAD

**Issue by OlgaRudina** [git-up/GitUp#911]
Version 1.3.5(1048)

**Comment by lucasderraugh** [comment]
I need more information to make this an actionable ticket. What are your exact steps, observed behavior, and expected behavior.

**Comment by OlgaRudina** [comment]
@lucasderraugh open repo -> merge one branch to another (with conflicts) -> click on the conflict file -> click on Resolve with merge tool -> nothing happens. Expected behaviour: Merge tool is opened.

**Comment by lucasderraugh** [comment]
What happens if you do the steps in #861?

**Comment by OlgaRudina** [comment]
@lucasderraugh this one helped https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786 Thanks!
