### ISSUE TITLE
How to disable automatic upgrade?

### ISSUE THREAD

**Issue by pys1992** [git-up/GitUp#916]
hi, I want to know how to disable automatic upgrade?

**Comment by lucasderraugh** [comment]
In Terminal, run "defaults read co.gitup.mac".

If you have enabled it previously then there should be an entry `SUAutomaticallyUpdate = 1;`

To make Sparkle ask again simply run `defaults delete co.gitup.mac SUAutomaticallyUpdate` and it will reset to prompt you for updates but not automatically install them.
