### ISSUE TITLE
How to use custom merge tool?

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#918]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/16647690/223434562-7bf122d2-be62-49d7-b74b-9f8a11d6ce8f.png">

Is there a possibility to set custom merge tool? For example https://www.sublimemerge.com/

**Comment by lucasderraugh** [comment]
I'd have to look at the code to see how we treat "Git Tool".

**Comment by prostolyubo** [comment]
I can confirm it works fine. You just need to configure your git tool in gitconfig and set the "Git tool" option in gitup. See the proper configuration in your software of choice. I for example use meld:
```
[merge]
  tool = meld
[mergetool]
  prompt = false
[mergetool "meld"]
  trustExitCode = true
  cmd = open -W -a Meld --args --auto-merge \"$LOCAL\" \"$BASE\" \"$REMOTE\" --output=\"$MERGED\"
```

**Comment by NikKovIos** [comment]
Did you place that code in git config? Where? Could you write more detail please?

**Comment by prostolyubo** [comment]
> Did you place that code in git config? Where? 

Yes, in the global gitconfig that can be found at ~/.gitconfig (if it is not there just create it). If it has some contents just append to it.

> Could you write more detail please?

There is not much more to add as the instructions vary sligntly per program. The best approach is just to google "How to set X as merge tool in git" and follow the instructions. Open (or create) the .gitconfig file and paste what's necessary. Here is the config for the mentioned sublime merge (the setup is even simplier than for meld)
https://forum.sublimetext.com/t/how-to-use-as-a-git-mergetool/39341
And you can also setup separate program for diff viewing too in the same way.

I suggest to close this issue as it has nothing to do with GitUp.
