### ISSUE TITLE
Problem connecting to repository with SSH

### ISSUE THREAD

**Issue by rwcope2** [git-up/GitUp#929]
I'm using GitUp 1.35 (1048) on MacOS Ventura (13.2.1), and I am unable to connect to a remote repository via SSH. The error I get is:

Failed connecting to "origin" remote: Failed to retrieve list of SSH authentication methods: Failed getting response

I have run `ssh-add  --apple-load-keychain`, which used to solve all of my SSH problems, but this is a new error.

Any thoughts?

Thanks,  
Rob

**Comment by lucasderraugh** [comment]
Not sure if it's any different, but I run this from my `zshrc` file: `ssh-add --apple-use-keychain -q`

**Comment by lucasderraugh** [comment]
Not sure if it's relevant either, but perhaps relevant if you're using an RSA key still: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by lucasderraugh** [comment]
One last thought was does doing a `git fetch` in Terminal change any aspect of GitUp working again? I've seen scenarios where restarting and then performing some underlying git operation seems to resolve some issues.

**Comment by rwcope2** [comment]
> Not sure if it's relevant either, but perhaps relevant if you're using an RSA key still: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

Thanks!  My problem was very similar to that. I am accessing a git repository on one of our servers, and after an update on the server, our old public keys stopped working.  We all regenerated our keys, updated those on the server, and that solved the problem.

**Comment by lucasderraugh** [comment]
@rwcope2 Good to close the issue then?
