### ISSUE TITLE
Can't undo files with special characters

### ISSUE THREAD

**Issue by hgezim** [git-up/GitUp#93]
As soon as I clone a git repo of mine, GitUp shows these two files as delete. However, I just can't get rid of them by typing Delete. They just sit there even after I accept the prompt.

<img width="557" alt="backend" src="https://cloud.githubusercontent.com/assets/124675/13968717/d6ce4d88-f043-11e5-85e0-15f57cda7fe1.png">

**Comment by hgezim** [comment]
That and git tells me nothing about these files, so something is not working as it should:

```bash
» git st                                 
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Comment by swisspol** [comment]
You most likely have 2 copies of these files in your repo but with different casing or equivalent. For instance a.txt and A.txt.Git CLI doesn't catch such problems but GitUp does.

**Comment by hgezim** [comment]
Doing an `ls` I get this:

```bash
------------------------------------------------------------
» ls -la test/support/files | grep wszystkim
-rwxr-xr-x   1 gezim  staff       64 22 Mar 15:34 .dziękuję wszystkim z południa - 阳光.txt.un~
-rwxr-xr-x   1 gezim  staff       64 22 Mar 15:34 dziękuję wszystkim z południa - 阳光.txt
------------------------------------------------------------
» 
```

It doesn't look like the files are deleted as GitUp reports. Also, these files show up as deleted as soon as I clone the project.

How can fix this?

BTW, GitUp rocks. You should charge for i! ;)

**Comment by swisspol** [comment]
You need to see what's exactly in the Git tree for this `files` folder. Start with `git ls-tree head`, then note the sha1 of the `test` folder, then go `git ls-tree head <sha1>` to list that folder and keep going until you reach `test/support/files`, then put the output of the command here. I'm suspecting you will have multiple entries for `dziękuję wszystkim...`.

**Comment by hgezim** [comment]
Thanks for your help, @swisspol!

You were right. Here is the result:

```bash
» git ls-tree b7dda4dc1d6c11e90ad4faf68195952e128d9a43 | grep dzi
100755 blob 541245b8994e29d560784f829ad654110e6c22e9	".dzie\314\250kuje\314\250 wszystkim z po\305\202udnia - \351\230\263\345\205\211.txt.un~"
100755 blob 541245b8994e29d560784f829ad654110e6c22e9	".dzi\304\231kuj\304\231 wszystkim z po\305\202udnia - \351\230\263\345\205\211.txt.un~"
100755 blob 541245b8994e29d560784f829ad654110e6c22e9	"dzie\314\250kuje\314\250 wszystkim z po\305\202udnia - \351\230\263\345\205\211.txt"
100755 blob 541245b8994e29d560784f829ad654110e6c22e9	"dzi\304\231kuj\304\231 wszystkim z po\305\202udnia - \351\230\263\345\205\211.txt"
------------------------------------------------------------
»  
```

How do I fix it?

**Comment by swisspol** [comment]
`git rm {exact_file_name_as_it_appears_in_ls_tree}` should work I think. If that doesn't work, do a checkout of your repo on a case-sensitive file system like Linux and fix it there.

GitUp shows these files as deleted because they're are not in the workdir on disk. And they can't be because HFS+ is cases-insensitive so it's impossible to have both `A.txt` and `a.txt` in the same folder.
