### ISSUE TITLE
Does't work with older Mac OS X/ OS X versions

### ISSUE THREAD

**Issue by TurtleWilly** [git-up/GitUp#943]
Website claims it works with 10.8 and up, Yosemite recommended (https://gitup.co/ , at the bottom under the download link)

But trying to run it on Yosemite (10.10.5):

```
Dyld Error Message:
  Library not loaded: @rpath/GitUpKit.framework/Versions/A/GitUpKit
  Referenced from: /Volumes/VOLUME/GitUp.app/Contents/MacOS/GitUp
  Reason: no suitable image found.  Did find:
	/Volumes/Foobar/GitUp.app/Contents/MacOS/../Frameworks/GitUpKit.framework/Versions/A/GitUpKit: code signature invalid for '/Volumes/Foobar/GitUp.app/Contents/MacOS/../Frameworks/GitUpKit.framework/Versions/A/GitUpKit'
```

after removing any code signatures:
```
Dyld Error Message:
  Symbol not found: ___NSArray0__
  Referenced from: /Volumes/VOLUME/GitUp.app/Contents/MacOS/../Frameworks/GitUpKit.framework/Versions/A/GitUpKit (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Volumes/VOLUME/GitUp.app/Contents/MacOS/../Frameworks/GitUpKit.framework/Versions/A/GitUpKit
```

Of course, that is after digging into the application bundle with Terminal already. There's a fat stop sign on the icon in Finder. 😥

IMHO at least the website should be updated, else folks will have wrong hope.

**Comment by lucasderraugh** [comment]
Yes, we've since bumped the minimum version to 10.13. I unfortunately don't have access to the website, but I'll inquire about potentially getting access to it so I can change that mention on the website.

**Comment by lucasderraugh** [comment]
@TurtleWilly I've updated the website to reflect the new 10.13 requirement.
