### ISSUE TITLE
Unify CLI

### ISSUE THREAD

**Issue by adius** [git-up/GitUp#95]
When GitUp is started via the command line, its behavior is very unusual.
It should be like this:

- `gitup` - Starts GitUp and shows start screen
- `gitup .` - Starts GitUp in the current directory
- `gitup ~/projects/some-app` - Starts GitUp in the `~/projects/some-app` directory
- `gitup -h` /  `gitup --help` - Shows usage instructions

**Comment by swisspol** [comment]
The CLI is intentionally designed for convenience and smooth integration with GitUp first, and not necessarily follow some of the Unix CLI conventions (which are just conventions since they are no official rules).

There are no plans to change this.

**Comment by adius** [comment]
Well, this sucks. … I can't see anything "convenient and smooth" about the current cli

**Comment by swisspol** [comment]
It would easy for you to write a wrapper script so it works the way you want. GitUp and its CLI tool have been available for more than a year now and AFAIK people like it the way it is.

**Comment by adius** [comment]
But a `gitup -h` would be good anyway

**Comment by naartjie** [comment]
bummer abou this, cli use is key
