### ISSUE TITLE
Option to hide tags

### ISSUE THREAD

**Issue by simonh1000** [git-up/GitUp#950]
Recently my company decided to tag all commits. the result in gitup is very busy and it would be great to have an option to hide all of these
![image](https://github.com/git-up/GitUp/assets/5256724/233a1508-a4f9-4669-8100-4a6e56061910)

**Comment by lucasderraugh** [comment]
@simonh1000 Don't we already have that?

<img width="258" alt="Screenshot 2023-10-01 at 10 10 10 AM" src="https://github.com/git-up/GitUp/assets/714282/c21e0249-9f2a-4e0c-b24f-185a928cd43e">

**Comment by simonh1000** [comment]
Ugh, hadn't found that
