### ISSUE TITLE
Use cmd + return instead of alt + return

### ISSUE THREAD

**Issue by adius** [git-up/GitUp#96]
Although I have the feeling like my time is totally wasted here,
I think it should be `cmd + return` instead of `alt + return`
to submit commit message.
Like it is common in most other applications…

**Comment by swisspol** [comment]
IIRC `Cmd + Return` doesn't work in modal dialogs due to Cocoa intercepting it and not distinguishing `Cmd+Return` from `Return`. `Alt + Return` is what is guaranteed to work everywhere.

**Comment by adius** [comment]
Mh, unfortunate, but good to know.

**Comment by beelsebob** [comment]
The behaviour seems backwards here.  Pretty much every other app uses alt-return to mean "insert a new line, instead of pushing the submit button", and return to mean "push the submit button".

**Comment by trss** [comment]
Also, I've rarely seen multi-line commit messages.

**Comment by beelsebob** [comment]
multiline commit messages are very common in companies that use bug tracking software.  Their commit messages are usually of the form

"<http://bugtracker/1956759> The Widget doesn't foozle with the doobery

Turns out the widget wasn't getting its foozle delegate set on initialisation.  Fix that and all is good."

**Comment by trss** [comment]
I see. They'll find alt-return for newline difficult then. I've not seen alt-return for newline whenever it's quite possible people use it often. Know any examples?

**Comment by salutis** [comment]
> The behaviour seems backwards here. Pretty much every other app uses alt-return to mean "insert a new line, instead of pushing the submit button", and return to mean "push the submit button".

This!
