### ISSUE TITLE
Pre Push Hook

### ISSUE THREAD

**Issue by hipstersmoothie** [git-up/GitUp#97]
Hey in my app I have a pre push hook that runs a gulp task for me, depending on whether this fails I allow the push. On the command line and source tree the push always works, but in gitup i am getting this error: 
 
      SecureTransport error: connection closed via error

For context I have been trying to use webpack in a gulp task, but for some reason this causes gitup to not push with the above message.

I looked at the logs on the command line and it looked like this:

00:00:00.775 [VERBOSE  ]> App is up-to-date at version 1012 on channel 'stable'
00:00:10.351 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git"
00:00:10.397 [VERBOSE  ]> History loaded for "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git" (4524 commits scanned in 0.049 seconds)
00:00:10.450 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git"
00:00:10.499 [VERBOSE  ]> Graph regenerated for "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git" in 0.015 seconds
00:00:10.669 [INFO     ]> SQLite (283): recovered 18 frames from WAL file /Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git/co.gitup.mac/cache.db-wal
00:00:10.677 [VERBOSE  ]> Commit database for "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git" updated in 0.007 seconds (0 added, 0 removed)
00:00:19.394 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git"
00:00:43.464 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git"
00:00:52.695 [VERBOSE  ]> Executed 'pre-push' hook in 36.135 seconds
00:00:52.745 [ERROR    ]> libgit2 error (-1): SecureTransport error: connection closed via error
00:00:52.747 [VERBOSE  ]> Ignoring reference "refs/stash" for history of "/Users/alisowski/Documents/Web-Player-Handlebars-Andrew/.git"

**Comment by swisspol** [comment]
I'm not sure the problem is the hook, it says it was executed in the log:
```
Executed 'pre-push' hook in 36.135 seconds
```

Anyway, some hooks might not work correctly under GitUp because of the fact it runs them directly and doesn't go through the Git tool: https://github.com/git-up/GitUp/wiki.

**Comment by hipstersmoothie** [comment]
The weird thing is the push goes through every few times. So i know it is close to working and it could work, I'm just getting an error in libgit. I'll take a look and maybe try to step through the gitup code tonight and see whats going wrong. Any suggestions where to start would be appreciated!
