### ISSUE TITLE
Backspace when searching

### ISSUE THREAD

**Issue by dario-f** [git-up/GitUp#98]
When I start typing in the search repository and press backspace many times in order to clear the TextField, it looses focus and asks to delete the commit or local branch. Maybe the ability to change the delete branch shortcut to alt+backspace in preferences would be helpful.

**Comment by swisspol** [comment]
I can't reproduce this issue, please provide steps.

**Comment by swisspol** [comment]
I see, you need to have something previously selected in the graph. Anyway, this happens because you typed `Backspace` one too many times. When the search field is empty, it closes automatically. This is all intended behavior and there are no plans to revise it.
