### ISSUE TITLE
Diff files not in a git repository? 

### ISSUE THREAD

**Issue by pouriaalmassi** [git-up/GitUp#980]
Is it possible to use GitUp to diff files not in a repository? If not would GitUpKit be able to support such functionality and where is the best place to start to enable that. Thanks in advance! 

Other editors and git clients allow this. 

VSCode `code -d file.a.txt file.b.txt`

Sublime Merge `smerge mgergetool file.a.txt file.b.txt`

FileMerge `opendiff file.a.txt file.b.txt`

**Comment by lucasderraugh** [comment]
Currently, no. We're not really a text editor and have no way of resolving conflicts, so it's not a huge priority.
