### ISSUE TITLE
What  🚫  stands for in gitup file comparison view?

### ISSUE THREAD

**Issue by TeaTimeForever** [git-up/GitUp#985]
I just noticed that in some files I see 🚫  symbol, and it is not in original file, so I assume that GitUp tries to say something. What could it be?

<img width="266" alt="Screenshot 2024-04-10 at 15 29 27" src="https://github.com/git-up/GitUp/assets/1087032/b738fe61-09c9-48b2-90a0-52b05ad544ad">

**Comment by lapfelix** [comment]
Indicates that there's no empty line at the end of the file
