### ISSUE TITLE
Are the Brew install instructions out of date?

### ISSUE THREAD

**Issue by notnotno** [git-up/GitUp#986]
When trying to use the installation instructions in the README by running:
`brew install homebrew/cask/gitup`

Brew returns the following message:
"Warning: No available formula with the name "homebrew/cask/gitup"

But I was able to install using this command instead:
`brew install git-up/gitup/git-gui`

Is this the correct way to install on Linux?

**Comment by notnotno** [comment]
Never mind, I see Linux is not supported either way.

**Comment by lucasderraugh** [comment]
There is GitDown that was a cross-platform offshoot. @codymikol might be able to help you.

https://github.com/codymikol/git-down

**Comment by codymikol** [comment]
Its not quite stable yet, but we're getting close 😄
